CREATE TABLE [Fact].[ContactNote]
(
	[ContactNoteKey]                     INT			  IDENTITY (1, 1) NOT FOR REPLICATION,
	[ContactNoteSourceId]                UNIQUEIDENTIFIER NOT NULL,
	[ContactNoteCustomerKey]             INT              NOT NULL,
	[ContactNoteCustomerName]            NVARCHAR (60)    NOT NULL,
	[ContactNoteContactPersonKey]        INT              NOT NULL, 
	[ContactNoteContactPersonName]       NVARCHAR (100)   NOT NULL,
	[ContactNoteCreatedByEmployeeKey]    INT              NOT NULL,
	[ContactNoteCreatedByEmployeeName]   NVARCHAR (60)    NOT NULL,
	[ContactNoteCreatedByTeam]           NVARCHAR (60)    NOT NULL,
	[ContactNoteModifiedByEmployeeKey]   INT              NOT NULL,
	[ContactNoteModifiedByEmployeeName]  NVARCHAR (60)    NOT NULL,
	[ContactNoteModifiedByTeam]          NVARCHAR (60)    NOT NULL,
	[ContactNoteBusinessUnitKey]         INT              NOT NULL,
	[ContactNoteBusinessUnitName]        NVARCHAR (60)    NOT NULL,
	[ContactNoteAcquisitiongoal]         NVARCHAR (60)    NOT NULL,
	[ContactNoteDateTimeCreated]         DATETIME2(0)     NOT NULL,
	[ContactNoteDateCreated]             DATE             NOT NULL,
	[ContactNoteTimeCreated]             TIME(0)          NOT NULL,
	[ContactNoteDateTimeModified]        DATETIME2(0)     NOT NULL,
	[ContactNoteDateModified]            DATE             NOT NULL,
	[ContactNoteTimeModified]            TIME(0)          NOT NULL,
	[ContactNoteType]                    NVARCHAR (60)    NOT NULL,
	[ContactNoteCategory]                NVARCHAR (60)    NOT NULL,
	[ContactNoteContactLevel]            NVARCHAR (20)    NOT NULL,
	CONSTRAINT [FK_ContactNote_CustomerKey] FOREIGN KEY ([ContactNoteCustomerKey]) REFERENCES [Dim].[Customer] ([CustomerKey]),
	CONSTRAINT [FK_ContactNote_ContactPersonKey] FOREIGN KEY ([ContactNoteContactPersonKey]) REFERENCES [Dim].[ContactPerson] ([ContactPersonKey]),
	CONSTRAINT [FK_ContactNote_CreatedByEmployeeKey_EmployeeKey] FOREIGN KEY ([ContactNoteCreatedByEmployeeKey]) REFERENCES [Dim].[Employee] ([EmployeeKey]),
	CONSTRAINT [FK_ContactNote_ModifiedByEmployeeKey_EmployeeKey] FOREIGN KEY ([ContactNoteModifiedByEmployeeKey]) REFERENCES [Dim].[Employee] ([EmployeeKey]),
)