CREATE TABLE [Fact].[EmployeeContract]
(
	[EmployeeContractKey]          INT              IDENTITY (70000000, 1) NOT FOR REPLICATION,
	[unid]                         UNIQUEIDENTIFIER NULL,
	[EmployeeKey]                  INT              NOT NULL DEFAULT -1,
	[EmployeeFullName]             NVARCHAR(62)     NOT NULL DEFAULT '[unknown]',
	[BusinessUnit]                 NVARCHAR(35)     NOT NULL DEFAULT '[unknown]',
	[Function]                     NVARCHAR(35)     NOT NULL DEFAULT '[unknown]',
	[ManagerKey]                   INT              NOT NULL DEFAULT -1,
	[ManagerFullName]              NVARCHAR(62)     NOT NULL DEFAULT '[unknown]',
	[HRRepresentativeKey]          INT              NOT NULL DEFAULT -1,
	[HRRepresentativeFullName]     NVARCHAR(35)     NOT NULL DEFAULT '[unknown]', 
	[ContractCreationDate]         DATETIME         NULL,
	[ContractChangeDate]           DATETIME         NULL,
	[ContractStatus]               INT              NULL,
	[ContractType]                 NVARCHAR (30)    NULL,
	[Percentage]                   DECIMAL (5,2)    NULL,
	[ContractStartDate]            DATE             NULL,
	[ContractEndDate]              DATE             NULL,
	[ContractDuration]             SMALLINT         NULL,
	[SuggestedHourlyRate]          DECIMAL (19,4)   NULL,
	CONSTRAINT [PK_EmployeeContractKey] PRIMARY KEY CLUSTERED ([EmployeeContractKey]),
	CONSTRAINT [FK_EmployeeContract_EmployeeKey] FOREIGN KEY ([EmployeeKey]) REFERENCES [Dim].[Employee] ([EmployeeKey]),
    CONSTRAINT [FK_EmployeeContract_ManagerKey] FOREIGN KEY ([ManagerKey]) REFERENCES [Dim].[Employee] ([EmployeeKey]),
	CONSTRAINT [FK_EmployeeContract_HRRepresentativeKey] FOREIGN KEY ([HRRepresentativeKey]) REFERENCES [Dim].[Employee] ([EmployeeKey])
)