CREATE TABLE [Fact].[Hour]
(
	[unid]              UNIQUEIDENTIFIER NULL,
	[ProjectKey]        INT              NOT NULL,
	[CustomerKey]       INT              NOT NULL,
	[EmployeeKey]       INT              NOT NULL,
	[HourTypeKey]       INT              NOT NULL,
	[ServiceKey]        INT              NOT NULL,
	[LedgerKey]         INT              NOT NULL,
	[NominationKey]     INT              NOT NULL,
	[TaskKey]           INT              NOT NULL,
	[HourInvoiceKey]    INT              NOT NULL DEFAULT -1,
	[Hours]             DECIMAL (19, 6)  NULL,
	[Day]               DATE             NULL,
	[ChangeDate]        DATE             NULL,
	[Rate]              DECIMAL (19, 4)  NULL,
	[Percentage]        DECIMAL (19, 4)  NULL,
	[Turnover]          AS               CONVERT(decimal(19,4), [Hours] * Rate * [Percentage] / 100) PERSISTED,
	[TurnoverBillable]  AS               (CONVERT([decimal](19,4),(([Hours]*[Rate])*[Percentage]*[Billable])/(100.0))) PERSISTED,
	[Billable]          BIT              NULL,
	[InvoiceProcessed]  BIT              NULL,
	CONSTRAINT [FK_Hour_CustomerKey] FOREIGN KEY ([CustomerKey]) REFERENCES [Dim].[Customer] ([CustomerKey]),
	CONSTRAINT [FK_Hour_Day] FOREIGN KEY ([Day]) REFERENCES [Dim].[Date] ([Date]),
	CONSTRAINT [FK_Hour_EmployeeKey] FOREIGN KEY ([EmployeeKey]) REFERENCES [Dim].[Employee] ([EmployeeKey]),
	CONSTRAINT [FK_Hour_ProjectKey] FOREIGN KEY ([ProjectKey]) REFERENCES [Dim].[Project] ([ProjectKey]),
	CONSTRAINT [FK_Hour_HourTypeKey] FOREIGN KEY ([HourTypeKey]) REFERENCES [Dim].[HourType] ([HourTypeKey]),
	CONSTRAINT [FK_Hour_ServiceKey] FOREIGN KEY ([ServiceKey]) REFERENCES [Dim].[Service] ([ServiceKey]),
	CONSTRAINT [FK_Hour_LedgerKey] FOREIGN KEY ([LedgerKey]) REFERENCES [Dim].[Ledger] ([LedgerKey]),
	CONSTRAINT [FK_Hour_NominationKey] FOREIGN KEY ([NominationKey]) REFERENCES [Dim].[Nomination] ([NominationKey]),
	CONSTRAINT [FK_Hour_TaskKey] FOREIGN KEY ([TaskKey]) REFERENCES [Dim].[Task] ([TaskKey]),
	--CONSTRAINT [FK_Hour_InvoiceKey] FOREIGN KEY ([HourInvoiceKey]) REFERENCES [Dim].[Invoice] ([InvoiceKey])							--At the next release, this constraint should be enabled.
)