CREATE TABLE [TOPdesk].[change] (
    [aanmelderafdelingid]  VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [aanmelderemail]       NVARCHAR (255)                                     NULL,
    [aanmeldernaam]        NVARCHAR (255)                                     NULL,
    [aanmeldertelefoon]    NVARCHAR (255)                                     NULL,
    [aanmeldervestigingid] VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [briefdescription]     NVARCHAR (255)                                     NULL,
    [calc_type_authdate]   INT                                                NULL,
    [calc_type_finaldate]  INT                                                NULL,
    [calc_type_impldate]   INT                                                NULL,
    [calldate]             DATETIME2 (7)                                      NULL,
    [categoryid]           VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [changetype]           INT                                                NULL,
    [closed]               BIT                                                NULL,
    [closeddate]           DATETIME2 (7)                                      NULL,
    [completed]            BIT                                                NULL,
    [completeddate]        DATETIME2 (7)                                      NULL,
    [currentphase]         INT                                                NULL,
    [dataanmk]             DATETIME2 (7)                                      NULL,
    [datwijzig]            DATETIME2 (7)                                      NULL,
    [finaldate]            DATETIME2 (7)                                      NULL,
    [externalnumber]       NVARCHAR (255)                                     NULL,
    [impactid]             VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [incidentid]           VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [isurgent]             BIT                                                NULL,
    [managerid]            VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [number]               NVARCHAR (255)                                     NULL,
    [objectid]             VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [operatorgroupid]      VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [plannedauthdate]      DATETIME2 (7)                                      NULL,
    [plannedfinaldate]     DATETIME2 (7)                                      NULL,
    [plannedimpldate]      DATETIME2 (7)                                      NULL,
    [implementationdate]   DATETIME2 (7)                                      NULL,
    [rejecteddate]         DATETIME2 (7)                                      NULL,
    [authorizationdate]    DATETIME2 (7)                                      NULL,
    [started]              BIT                                                NULL,
    [starteddate]          DATETIME2 (7)                                      NULL,
    [statusid]             VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [subcategoryid]        VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [submitdate]           DATETIME2 (7)                                      NULL,
    [templateid]           VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [timetaken]            BIGINT                                             NULL,
    [typeid]               VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [uidaanmk]             VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [uidwijzig]            VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [withevaluation]       BIT                                                NULL,
    [plannedstartdate]     DATETIME2 (7)                                      NULL,
    [canceledbypersonid]   VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [canceledbyoperatorid] VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [canceldate]           DATETIME2 (7)                                      NULL,
    [priorityid]           VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [rejected]             BIT                                                NULL,
    [pro_rejecteddate]     DATETIME2 (7)                                      NULL,
    [status]               INT                                                NULL,
    [vrijelogisch3]        BIT                                                NULL,
    [vrijememo1]           NVARCHAR (MAX)                                     NULL,
    [vrijememo2]           NVARCHAR (MAX)                                     NULL,
    [unid]                 VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
    [AuditDWKey]           INT                                                NOT NULL,
    [SourceDatabaseKey]    INT                                                NOT NULL,
    [ValidFrom]            DATETIME2 (0) GENERATED ALWAYS AS ROW START HIDDEN CONSTRAINT [DF_TOPdeskchangeSysStart] DEFAULT (CONVERT([datetime2](0),'0000-01-01 00:00:00')) NOT NULL,
    [ValidTo]              DATETIME2 (0) GENERATED ALWAYS AS ROW END HIDDEN   CONSTRAINT [DF_TOPdeskchangeSysEnd] DEFAULT (CONVERT([datetime2](0),'9999-12-31 23:59:59')) NOT NULL,
    [vrijelogisch2]        BIT                                                NULL,
    [vrijeopzoek3]         VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [aanmelderlokatieid]   VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    CONSTRAINT [pk_TOPdeskchange] PRIMARY KEY CLUSTERED ([unid] ASC, [AuditDWKey] ASC) WITH (DATA_COMPRESSION = PAGE),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[history].[change], DATA_CONSISTENCY_CHECK=ON));

