CREATE TABLE [TOPdesk].[herhaling] (
    [unid]              VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
    [planningid]        VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [periode]           NVARCHAR (255)                                     NOT NULL,
    [jaarinterval]      INT                                                NOT NULL,
    [jaarperiode]       NVARCHAR (255)                                     NOT NULL,
    [maandvanjaar]      INT                                                NOT NULL,
    [weekvanjaar]       INT                                                NOT NULL,
    [dagvanjaar]        INT                                                NOT NULL,
    [maandinterval]     INT                                                NOT NULL,
    [maandperiode]      NVARCHAR (255)                                     NOT NULL,
    [weekvanmaand]      INT                                                NOT NULL,
    [dagvanmaand]       INT                                                NOT NULL,
    [weekinterval]      INT                                                NOT NULL,
    [maandag]           BIT                                                NOT NULL,
    [dinsdag]           BIT                                                NOT NULL,
    [woensdag]          BIT                                                NOT NULL,
    [donderdag]         BIT                                                NOT NULL,
    [vrijdag]           BIT                                                NOT NULL,
    [zaterdag]          BIT                                                NOT NULL,
    [zondag]            BIT                                                NOT NULL,
    [daginterval]       INT                                                NOT NULL,
    [starttijd]         BIGINT                                             NOT NULL,
    [dataanmk]          DATETIME2 (7)                                      NOT NULL,
    [datwijzig]         DATETIME2 (7)                                      NOT NULL,
    [doorlooptijd]      BIGINT                                             NULL,
    [uidaanmk]          VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [uidwijzig]         VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [dagvanweek]        INT                                                NOT NULL,
    [AuditDWKey]        INT                                                NOT NULL,
    [SourceDatabaseKey] INT                                                NULL,
    [ValidFrom]         DATETIME2 (0) GENERATED ALWAYS AS ROW START HIDDEN CONSTRAINT [DF_TOPdeskherhalingSysStart] DEFAULT (CONVERT([datetime2](0),'0000-01-01 00:00:00')) NOT NULL,
    [ValidTo]           DATETIME2 (0) GENERATED ALWAYS AS ROW END HIDDEN   CONSTRAINT [DF_TOPdeskherhalingSysEnd] DEFAULT (CONVERT([datetime2](0),'9999-12-31 23:59:59')) NOT NULL,
    CONSTRAINT [pk_TOPdeskherhaling] PRIMARY KEY CLUSTERED ([unid] ASC, [AuditDWKey] ASC) WITH (DATA_COMPRESSION = PAGE),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[history].[herhaling], DATA_CONSISTENCY_CHECK=ON));

