CREATE TABLE [TOPdesk].[incident] (
    [aanmelderafdelingid]    VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [aanmeldertelefoon]      NVARCHAR (255)                                     NULL,
    [aanmeldervestigingid]   VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [afgemeld]               BIT                                                NULL,
    [afhandelingstatusid]    VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [configuratieid]         VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [configuratieobjectid]   VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [dnoid]                  VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [doorlooptijdid]         VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [gereed]                 BIT                                                NULL,
    [persoonid]              VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [ref_dnocontractid]      VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [ref_domein]             NVARCHAR (255)                                     NULL,
    [ref_impact]             NVARCHAR (255)                                     NULL,
    [ref_soortmelding]       NVARCHAR (255)                                     NULL,
    [ref_specificatie]       NVARCHAR (255)                                     NULL,
    [soortbinnenkomstid]     VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [status]                 INT                                                NULL,
    [uidaanmk]               VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [dataanmk]               DATETIME2 (7)                                      NULL,
    [datumaangemeld]         DATETIME2 (7)                                      NULL,
    [datumafgemeld]          DATETIME2 (7)                                      NULL,
    [datumafspraak]          DATETIME2 (7)                                      NULL,
    [datumgereed]            DATETIME2 (7)                                      NULL,
    [datwijzig]              DATETIME2 (7)                                      NULL,
    [lijn1tijdbesteed]       BIGINT                                             NULL,
    [tijdbesteed]            BIGINT                                             NULL,
    [totaletijd]             BIGINT                                             NULL,
    [minutendoorlooptijd]    BIGINT                                             NULL,
    [dnostatus]              INT                                                NULL,
    [korteomschrijving]      NVARCHAR (255)                                     NULL,
    [datumafspraaksla]       DATETIME2 (7)                                      NULL,
    [oplossingid]            VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [naam]                   NVARCHAR (255)                                     NULL,
    [aanmeldernaam]          NVARCHAR (255)                                     NULL,
    [ismajorincident]        BIT                                                NULL,
    [majorincidentid]        VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [servicewindowid]        VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [externnummer]           NVARCHAR (255)                                     NULL,
    [aanmelderemail]         NVARCHAR (255)                                     NULL,
    [onhold]                 BIT                                                NULL,
    [onholdduration]         BIGINT                                             NULL,
    [ref_operatorgroup]      NVARCHAR (255)                                     NULL,
    [ref_operatordynanaam]   NVARCHAR (255)                                     NULL,
    [onholddatum]            DATETIME2 (7)                                      NULL,
    [adjusteddurationonhold] BIGINT                                             NULL,
    [priorityid]             VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [supplierid]             VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [vrijememo1]             NVARCHAR (MAX)                                     NULL,
    [vrijememo2]             NVARCHAR (MAX)                                     NULL,
    [vrijememo3]             NVARCHAR (MAX)                                     NULL,
    [unid]                   VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
    [AuditDWKey]             INT                                                NOT NULL,
    [SourceDatabaseKey]      INT                                                NOT NULL,
    [ValidFrom]              DATETIME2 (0) GENERATED ALWAYS AS ROW START HIDDEN CONSTRAINT [DF_TOPdeskincidentSysStart] DEFAULT (CONVERT([datetime2](0),'0000-01-01 00:00:00')) NOT NULL,
    [ValidTo]                DATETIME2 (0) GENERATED ALWAYS AS ROW END HIDDEN   CONSTRAINT [DF_TOPdeskincidentSysEnd] DEFAULT (CONVERT([datetime2](0),'9999-12-31 23:59:59')) NOT NULL,
    [aanmelderlokatieid]     VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [uidwijzig]              VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [vrijetekst1]            NVARCHAR (255)                                     NULL,
    [impactid]               VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [incident_domeinid]      VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [incident_specid]        VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [operatorgroupid]        VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [operatorid]             VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [soortmeldingid]         VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    CONSTRAINT [pk_TOPdeskincident] PRIMARY KEY CLUSTERED ([unid] ASC, [AuditDWKey] ASC) WITH (DATA_COMPRESSION = PAGE),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[history].[incident], DATA_CONSISTENCY_CHECK=ON));




GO
CREATE NONCLUSTERED INDEX [NCIX_TOPdeskIncident_SDK]
    ON [TOPdesk].[incident]([SourceDatabaseKey] ASC)
    INCLUDE([naam], [AuditDWKey]);

