CREATE TABLE [TOPdesk].[probleem] (
    [afgemeld]                     BIT                                                NULL,
    [afgemeldbf]                   BIT                                                NULL,
    [archiefredenid]               VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [categorieid]                  VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [doorlooptijdbfid]             VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [doorlooptijdid]               VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [gereed]                       BIT                                                NULL,
    [gereedbf]                     BIT                                                NULL,
    [impactbfid]                   VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [impactid]                     VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [oorzaakid]                    VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [ref_domein]                   NVARCHAR (255)                                     NULL,
    [ref_specificatie]             NVARCHAR (255)                                     NULL,
    [status]                       INT                                                NULL,
    [statusid]                     VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [uidaanmk]                     VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [uidwijzig]                    VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [vrijeopzoek1]                 VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [aanmaakdatum]                 DATETIME2 (7)                                      NULL,
    [aanmaakdatumbf]               DATETIME2 (7)                                      NULL,
    [dataanmk]                     DATETIME2 (7)                                      NULL,
    [datumafgemeld]                DATETIME2 (7)                                      NULL,
    [datumafgemeldbf]              DATETIME2 (7)                                      NULL,
    [datumgereed]                  DATETIME2 (7)                                      NULL,
    [datumgereedbf]                DATETIME2 (7)                                      NULL,
    [datwijzig]                    DATETIME2 (7)                                      NULL,
    [streefdatum]                  DATETIME2 (7)                                      NULL,
    [streefdatumbf]                DATETIME2 (7)                                      NULL,
    [kostenbegroot]                MONEY                                              NULL,
    [kostenverwacht]               MONEY                                              NULL,
    [onkosten]                     MONEY                                              NULL,
    [onkostenbf]                   MONEY                                              NULL,
    [tijdbegroot]                  BIGINT                                             NULL,
    [tijdbesteed]                  BIGINT                                             NULL,
    [tijdbesteedbf]                BIGINT                                             NULL,
    [tijdverwacht]                 BIGINT                                             NULL,
    [totalekosten]                 MONEY                                              NULL,
    [totaletijd]                   BIGINT                                             NULL,
    [refcombi_afgemeld]            BIT                                                NULL,
    [refcombi_datumafgemeld]       DATETIME2 (7)                                      NULL,
    [refcombi_datumgereed]         DATETIME2 (7)                                      NULL,
    [refcombi_gereed]              BIT                                                NULL,
    [refcombi_beheerder]           NVARCHAR (255)                                     NULL,
    [refcombi_tijdbesteed]         BIGINT                                             NULL,
    [minutendoorlooptijd]          BIGINT                                             NULL,
    [minutendoorlooptijdbf]        BIGINT                                             NULL,
    [refcombi_minutendoorlooptijd] BIGINT                                             NULL,
    [korteomschrijvingbf]          NVARCHAR (255)                                     NULL,
    [refcombi_korteomschrijving]   NVARCHAR (255)                                     NULL,
    [ref_behandelaar]              NVARCHAR (255)                                     NULL,
    [ref_domeinprobleem]           NVARCHAR (255)                                     NULL,
    [ref_specificatieprobleem]     NVARCHAR (255)                                     NULL,
    [operatorgroupid]              VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [urgencyid]                    VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [priorityid]                   VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [naam]                         VARCHAR (36)                                       NOT NULL,
    [AuditDWKey]                   INT                                                NOT NULL,
    [SourceDatabaseKey]            INT                                                NOT NULL,
    [ValidFrom]                    DATETIME2 (0) GENERATED ALWAYS AS ROW START HIDDEN CONSTRAINT [DF_TOPdeskprobleemSysStart] DEFAULT (CONVERT([datetime2](0),'0000-01-01 00:00:00')) NOT NULL,
    [ValidTo]                      DATETIME2 (0) GENERATED ALWAYS AS ROW END HIDDEN   CONSTRAINT [DF_TOPdeskprobleemSysEnd] DEFAULT (CONVERT([datetime2](0),'9999-12-31 23:59:59')) NOT NULL,
    [unid]                         VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [actiedoorid]                  VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [domeinid]                     VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [domeinprobleemid]             VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [specificatieid]               VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [specificatieprobleemid]       VARCHAR (36)                                       COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    CONSTRAINT [pk_TOPdeskprobleem] PRIMARY KEY CLUSTERED ([naam] ASC, [AuditDWKey] ASC) WITH (DATA_COMPRESSION = PAGE),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[history].[probleem], DATA_CONSISTENCY_CHECK=ON));



