CREATE TABLE [Dim].[Date]
(
	[DateKey]          INT          NOT NULL,
	[Date]             DATE         NOT NULL,
	[DayOfWeek]        SMALLINT     NULL,
	[NL_Weekdag]       VARCHAR (10) NULL,
	[EN_Weekday]       VARCHAR (10) NULL,
	[DayInMonth]       SMALLINT     NULL,
	[DayOfYear]        SMALLINT     NULL,
	[WeekOfYear]       TINYINT      NULL,
	[Weeknumber]       TINYINT      NULL,
	[EN_Month]         VARCHAR (10) NULL,
	[NL_Maand]         VARCHAR (10) NULL,
	[MonthOfYear]      TINYINT      NULL,
	[CalendarQuarter]  TINYINT      NULL,
	[CalendarYear]     SMALLINT     NULL,
	[DWDayNumber]      SMALLINT     NULL,
	[CalendarSemester] TINYINT      NULL,
	[DWWeekNumber]     SMALLINT     NULL,
	[NL_WeekdayShort]  AS           CONVERT(char(2), LEFT(NL_Weekdag,(2))) PERSISTED,
	[NL_MonthShort]    AS           CONVERT(char(3), LEFT(NL_Maand,(3))) PERSISTED,
	[WeekStartYear]    SMALLINT     NULL,
	[WeekStartDate]    DATE         NULL,
	[WeekYear]         SMALLINT     NULL,
	[DWMonthNumber]    SMALLINT     NULL,
	[Holiday]          BIT          NULL,
	[DWWorkDayNumber]  SMALLINT     DEFAULT 0 NULL,
	CONSTRAINT [PK_Date] PRIMARY KEY CLUSTERED ([Date] ASC)
)