CREATE TABLE [FileImport].[ChangeActivities] (
    [ActivityCreatedBy]              NVARCHAR (255) NULL,
    [ActivityNumber]                 NVARCHAR (255) NULL,
    [ActivityTemplate]               NVARCHAR (255) NULL,
    [ActivityResolved]               BIT            NULL,
    [ActivityProcessingStatus]       NVARCHAR (255) NULL,
    [ActivityOperatorName]           NVARCHAR (255) NULL,
    [ActivityOperatorGroup]          NVARCHAR (255) NULL,
    [ActivityTimeTaken]              BIGINT         NULL,
    [ActivityCategory]               NVARCHAR (255) NULL,
    [ActivityDatAanmk]               DATETIME       NULL,
    [ActivityDatWijzig]              DATETIME       NULL,
    [ActivityResolvedDate]           DATETIME       NULL,
    [ActivityRejectedDate]           DATETIME       NULL,
    [ActivityApprovedDate]           DATETIME       NULL,
    [ActivitySkippedDate]            DATETIME       NULL,
    [ActivityChangePhase]            NVARCHAR (255) NULL,
    [ActivityPlannedFinalDate]       DATETIME       NULL,
    [ActivityPlannedStartDate]       DATETIME       NULL,
    [ActivityStarted]                BIT            NULL,
    [ActivityCurrentPlanTimeTaken]   BIGINT         NULL,
    [ActivityApproved]               BIT            NULL,
    [ActivityBriefDescription]       NVARCHAR (255) NULL,
    [ActivityChangeBriefDescription] NVARCHAR (255) NULL,
    [ActivityRejected]               BIT            NULL,
    [ActivityOriginalPlanTimeTaken]  BIGINT         NULL,
    [ActivitySkipped]                BIT            NULL,
    [ActivityStartedDate]            DATETIME       NULL,
    [ActivityStatus]                 NVARCHAR (255) NULL,
    [ActivitySubcategory]            NVARCHAR (255) NULL,
    [ActivityChangedBy]              NVARCHAR (255) NULL,
    [ActivityChange]                 NVARCHAR (255) NULL,
    [AuditDWKey]                     BIGINT         NOT NULL
);

