CREATE TABLE [FileImport].[Changes]
(
	[CardCreatedBy]                NVARCHAR (85)  NULL,
	[RequestDate]                  DATETIME       NULL,
	[Department]                   NVARCHAR (60)  NULL,
	[Rejected]                     BIT            NULL,
	[ProcessingStatus]             NVARCHAR (50)  NULL,
	[RejectionDate]                DATETIME       NULL,
	[AuthorizationDate]            DATETIME       NULL,
	[OperatorSimpleChange]         NVARCHAR (80)  NULL,
	[OperatorEvaluationExtChange]  NVARCHAR (80)  NULL,
	[OperatorProgressExtChange]    NVARCHAR (80)  NULL,
	[OperatorRequestChange]        NVARCHAR (80)  NULL,
	[OperatorGroup]                NVARCHAR (93)  NULL,
	[Category]                     NVARCHAR (30)  NULL,
	[Coordinator]                  NVARCHAR (93)  NULL,
	[CreationDate]                 DATETIME       NULL,
	[ChangeDate]                   DATETIME       NULL,
	[ClosureDateSimpleChange]      DATETIME       NULL,
	[SubmissionDateRequestChange]  DATETIME       NULL,
	[NoGoDateExtChange]            DATETIME       NULL,
	[CancelDateExtChange]          DATETIME       NULL,
	[DateCalcTypeEvaluation]       NVARCHAR (30)  NULL,
	[DateCalcTypeProgress]         NVARCHAR (30)  NULL,
	[DateCalcTypeRequestChange]    NVARCHAR (30)  NULL,
	[CallerEmail]                  NVARCHAR (100) NULL,
	[Evaluation]                   BIT            NULL,
	[ExternalNumber]               NVARCHAR (60)  NULL,
	[CancelledByOperator]          NVARCHAR (93)  NULL,
	[CancelledByManager]           NVARCHAR (93)  NULL,
	[Implemented]                  BIT            NULL,
	[PlannedAuthDateRequestChange] DATETIME       NULL,
	[PlannedFinalDate]             DATETIME       NULL,
	[PlannedImplDate]              DATETIME       NULL,
	[PlannedStartDateSimpleChange] DATETIME       NULL,
	[TimeSpent]                    BIGINT         NULL,
	[EndDateExtChange]             DATETIME       NULL,
	[StartDateSimpleChange]        DATETIME       NULL,
	[Closed]                       BIT            NULL,
	[Started]                      BIT            NULL,
	[CurrentPhase]                 NVARCHAR (50)  NULL,
	[Impact]                       NVARCHAR (30)  NULL,
	[ImplDateSimpleChange]         DATETIME       NULL,
	[ImplDateExtChange]            DATETIME       NULL,
	[CustomerName]                 NVARCHAR (60)  NULL,
	[DescriptionBrief]             NVARCHAR (80)  NULL,
	[CallerName]                   NVARCHAR (93)  NULL,
	[ObjectID]                     NVARCHAR (60)  NULL,
	[OriginalIncident]             NVARCHAR (30)  NULL,
	[Priority]                     NVARCHAR (30)  NULL,
	[Template]                     NVARCHAR (80)  NULL,
	[Type]                         NVARCHAR (40)  NULL,
	[ChangeType]                   NVARCHAR (50)  NULL,
	[Status]                       NVARCHAR (30)  NULL,
	[Subcategory]                  NVARCHAR (30)  NULL,
	[CallerTelephoneNumber]        NVARCHAR (25)  NULL,
	[Urgency]                      BIT            NULL,
	[CallerBranch]                 NVARCHAR (60)  NULL,
	[CardChangedBy]                NVARCHAR (85)  NULL,
	[ChangeNumber]                 NVARCHAR (30)  NULL,
	[AuditDWKey]                   BIGINT         NOT NULL,
	[CallerLocation]               NVARCHAR (50)  NULL,
	[IsUrgent]                     BIT            NULL
)
GO

CREATE NONCLUSTERED INDEX [IX_Changes_AuditDWKey]
	ON [FileImport].[Changes] ([AuditDWKey])
	INCLUDE ([ChangeNumber])
GO