CREATE TABLE [FileImport].[Incidents]
(
	[DurationAdjusted]      BIGINT         NULL,
	[CardCreatedBy]         NVARCHAR (85)  NULL,
	[NumberOfDaysCurrent]   INT            NULL,
	[Department]            NVARCHAR (60)  NULL,
	[Closed]                BIT            NULL,
	[OperatorName]          NVARCHAR (93)  NULL,
	[OperatorGroup]         NVARCHAR (93)  NULL,
	[TimeSpentFirstLine]    BIGINT         NULL,
	[TimeSpentSecondLine]   BIGINT         NULL,
	[Category]              NVARCHAR (30)  NULL,
	[ConfigurationID]       NVARCHAR (30)  NULL,
	[CreationDate]          DATETIME       NULL,
	[ChangeDate]            DATETIME       NULL,
	[IncidentDate]          DATETIME       NULL,
	[ClosureDate]           DATETIME       NULL,
	[TargetDate]            DATETIME       NULL,
	[CompletionDate]        DATETIME       NULL,
	[OnHoldDate]            DATETIME       NULL,
	[Duration]              NVARCHAR (60)  NULL,
	[DurationOnHold]        BIGINT         NULL,
	[CallerEmail]           NVARCHAR (100) NULL,
	[ExternalNumber]        NVARCHAR (60)  NULL,
	[SlaAchieved]           NVARCHAR (50)  NULL,
	[DurationActual]        BIGINT         NULL,
	[Completed]             BIT            NULL,
	[TotalTime]             BIGINT         NULL,
	[CallerGender]          NVARCHAR (10)  NULL,
	[Impact]                NVARCHAR (30)  NULL,
	[IsMajorIncident]       BIT            NULL,
	[CustomerName]          NVARCHAR (60)  NULL,
	[IncidentDescription]   NVARCHAR (80)  NULL,
	[Supplier]              NVARCHAR (60)  NULL,
	[Line]                  NVARCHAR (50)  NULL,
	[MajorIncident]         NVARCHAR (30)  NULL,
	[IncidentNumber]        NVARCHAR (30)  NULL,
	[CallerMobileNumber]    NVARCHAR (25)  NULL,
	[CallerName]            NVARCHAR (93)  NULL,
	[ObjectID]              NVARCHAR (60)  NULL,
	[Onhold]                BIT            NULL,
	[CallerCity]            NVARCHAR (30)  NULL,
	[Priority]              NVARCHAR (30)  NULL,
	[ServiceWindow]         NVARCHAR (100) NULL,
	[Sla]                   NVARCHAR (75)  NULL,
	[SlaTargetDate]         DATETIME       NULL,
	[SlaContract]           NVARCHAR (40)  NULL,
	[SlaLevel]              NVARCHAR (20)  NULL,
	[EntryType]             NVARCHAR (30)  NULL,
	[IncidentType]          NVARCHAR (30)  NULL,
	[StandardSolution]      NVARCHAR (80)  NULL,
	[Status]                NVARCHAR (30)  NULL,
	[Subcategory]           NVARCHAR (30)  NULL,
	[CallerTelephoneNumber] NVARCHAR (25)  NULL,
	[CallerBranch]          NVARCHAR (60)  NULL,
	[CardChangedBy]         NVARCHAR (85)  NULL,
	[AuditDWKey]            BIGINT         NOT NULL,
	[CallerLocation]        NVARCHAR (50)  NULL
)
GO

CREATE NONCLUSTERED INDEX [IX_Incidents_AuditDWKey]
	ON [FileImport].[Incidents] ([AuditDWKey])
	INCLUDE ([IncidentNumber])
GO