CREATE TABLE [Inspectie].[TA_2017_PO_SO_VO] (
    [Peildatum]               DATE           NULL,
    [Sector]                  NVARCHAR (255) NULL,
    [OVT]                     NVARCHAR (255) NULL,
    [OVTNaam]                 NVARCHAR (255) NULL,
    [Elementtype]             NVARCHAR (255) NULL,
    [Onderzoeksnummer]        INT            NULL,
    [TypeOnderzoekCode]       NVARCHAR (255) NULL,
    [TypeOnderzoek]           NVARCHAR (255) NULL,
    [OordeelKwaliteit]        NVARCHAR (255) NULL,
    [Toezichtarrangement]     NVARCHAR (255) NULL,
    [ToezichtarrangementSvhO] NVARCHAR (255) NULL,
    [VaststellingsdatumTA]    DATE           NULL,
    [PublicatiedatumTA]       DATE           NULL,
    [DUOinstellingstype]      NVARCHAR (255) NULL,
    [DenominatieInstelling]   NVARCHAR (255) NULL,
    [BetrokkenVestigingen]    NVARCHAR (255) NULL,
    [BRIN]                    NVARCHAR (4)   NULL,
    [vestiging]               INT            NULL,
    [Vestigingsnaam]          NVARCHAR (255) NULL,
    [Bezoekadres]             NVARCHAR (255) NULL,
    [Postcode]                NVARCHAR (255) NULL,
    [Plaats]                  NVARCHAR (255) NULL,
    [Gemeente]                NVARCHAR (255) NULL,
    [Provincie]               NVARCHAR (255) NULL,
    [Bestuursnummer]          INT            NULL,
    [NaamBestuur]             NVARCHAR (255) NULL
);

