CREATE TABLE [Security].[UserPrincipalName]
(
	[ID]   INT            IDENTITY (1, 1),
	[Name] NVARCHAR (255) NOT NULL,
	CONSTRAINT [PK_UserPrincipalName] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO