CREATE TABLE [Dim].[Employee]
(
	[EmployeeKey]         INT              IDENTITY (20000000, 1) NOT FOR REPLICATION,
	[unid]                UNIQUEIDENTIFIER NULL,
	[EmployeeNumber]      NVARCHAR (9)     NULL,
	[LastName]            NVARCHAR (30)    NULL,
	[GivenName]           NVARCHAR (20)    NULL,
	[Prefixes]            NVARCHAR (10)    NULL,
	[Initials]            NVARCHAR (10)    NULL,
	[LastNameFirst]       AS               LastName + ', ' + GivenName + CASE WHEN Prefixes <> '' THEN ' ' + Prefixes ELSE '' END,
	[FullName]            AS               GivenName + ' ' + CASE WHEN Prefixes <> '' THEN Prefixes + ' ' ELSE '' END + LastName,
	[BirthYear]           INT              NULL,
	[EmailAddress]        NVARCHAR (120)   NULL,
	[PostalCode]          NVARCHAR (4)     NULL,
	[City]                NVARCHAR (30)    NULL,
	[PhoneNumber]         NVARCHAR (20)    NULL,
	[BusinessTeam]        NVARCHAR (35)    NULL,
	[BusinessUnit]        NVARCHAR (35)    NULL,
	[Function]            NVARCHAR (35)    NULL,
	[Team]                NVARCHAR (35)    NULL,
	[ManagerKey]          INT              NULL,
	[Manager]             NVARCHAR (35)    NULL,
	[HRRepresentativeKey] INT              NULL,
	[HRRepresentative]    NVARCHAR (35)    NULL,
	[JoinDate]            DATE             NULL,
	[ContractStartDate]   DATE             NULL,
	[ContractEndDate]     DATE             NULL,
	[ContractType]        NVARCHAR (60)    NULL,
	[ContractHours]       SMALLINT         NULL,
	[HasActiveContract]   BIT              NOT NULL,
	[NextAppointment]     NVARCHAR (60)    NULL,
	[ExternalRate]        MONEY            NULL,
	[OwnsCar]             BIT              NULL,
	[HasDriversLicense]   BIT              NULL,
	[Availability]        INT              NULL,
	[EmployeeOffice]      NVARCHAR (40)    NOT NULL DEFAULT '[unknown]',        --Default is required for first deployment (because 'NOT NULL'). When this column is filled on PROD, the default can be removed.
	CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED ([EmployeeKey] ASC),
	CONSTRAINT [FK_Employee_HRRepresentativeKey] FOREIGN KEY ([HRRepresentativeKey]) REFERENCES [Dim].[Employee] ([EmployeeKey]),
	CONSTRAINT [FK_Employee_ManagerKey] FOREIGN KEY ([ManagerKey]) REFERENCES [Dim].[Employee] ([EmployeeKey])
)