CREATE TABLE [Dim].[Nomination]
(
	[NominationKey]             INT              IDENTITY (110000000, 1) NOT FOR REPLICATION,
	[unid]                      UNIQUEIDENTIFIER NULL,
	[ProjectKey]                INT              NOT NULL DEFAULT -1,
	[RequestKey]                INT              NOT NULL DEFAULT -1,
	[CustomerKey]               INT              NOT NULL DEFAULT -1,
	[EmployeeKey]               INT              NOT NULL DEFAULT -1,
	[ActivityGroupKey]          INT              NOT NULL DEFAULT -1,
	[LedgerKey]                 INT              NOT NULL DEFAULT -1,
	[TaskKey]                   INT              NOT NULL DEFAULT -1,
	[RequestNumber]             NVARCHAR (20)    NULL,
	[NominationName]            NVARCHAR (30)    NULL,
	[PlanningStartDate]         DATE             NULL,
	[PlanningEndDate]           DATE             NULL,
	[WorkloadWeekly]            INT              NULL,
	[HourlyRate]                MONEY            NULL,
	[ChangeDate]                DATE             NULL,
	[Internal]                  BIT              NULL,
	[NominationType]            CHAR (14)        NULL,
	[Status]                    INT              NULL,
	[ProductGroup]              NVARCHAR (30)    NOT NULL,
	[Product]                   NVARCHAR (30)    NOT NULL,
	CONSTRAINT [PK_Nomination] PRIMARY KEY (NominationKey),
	CONSTRAINT [FK_Nomination_CustomerKey] FOREIGN KEY ([CustomerKey]) REFERENCES [Dim].[Customer] ([CustomerKey]),
	CONSTRAINT [FK_Nomination_EmployeeKey] FOREIGN KEY ([EmployeeKey]) REFERENCES [Dim].[Employee] ([EmployeeKey]),
	CONSTRAINT [FK_Nomination_ActivityGroupKey] FOREIGN KEY ([ActivityGroupKey]) REFERENCES [Dim].[ActivityGroup] ([ActivityGroupKey]),
	CONSTRAINT [FK_Nomination_ProjectKey] FOREIGN KEY ([ProjectKey]) REFERENCES [Dim].[Project] ([ProjectKey]),
	CONSTRAINT [FK_Nomination_RequestKey] FOREIGN KEY ([RequestKey]) REFERENCES [Dim].[Request] ([RequestKey]),
	CONSTRAINT [FK_Nomination_LedgerKey] FOREIGN KEY ([LedgerKey]) REFERENCES [Dim].[Ledger] ([LedgerKey]),
	CONSTRAINT [FK_Nomination_TaskKey] FOREIGN KEY ([TaskKey]) REFERENCES [Dim].[Task] ([TaskKey]),
)