TRUNCATE TABLE setup.CustomMetadata
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','Aanmelding.Begindatum','leerlinggegevens','Begindatum','date',1
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','Aanmelding.Einddatum','leerlinggegevens','Einddatum','date',2
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','Aanmelding.Vertrekdatum','leerlinggegevens','Vertrekdatum','date',3
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','Aanmelding.Iltberek','leerlinggegevens','BerekendeIltCode','varchar(4)',4
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','Aanmelding.Externe_instromer','leerlinggegevens','ExterneInstromer','bit',5
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','Aanmelding.Externe_uitstromer','leerlinggegevens','ExterneUitstromer','bit',6
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','Aanmelding.LWOOindicatie','leerlinggegevens','LWOO_indicatie','bit',7
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','Aanmelding.Niet_meetellen_met_officile_tellingen','leerlinggegevens','NietMeetellenMetOfficieleTellingen','bit',8
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','Aanmelding.PRO_indicatie','leerlinggegevens','PRO_indicatie','bit',9
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','Aanmelding.Zittenblijver','leerlinggegevens','Zittenblijver','bit',10
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','Administratieve_eenheid.BRIN','leerlinggegevens','BRINnummer','varchar(4)',11
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','Administratieve_eenheid.Officile_code_nevenvestiging','leerlinggegevens','CodeNevenvestiging','varchar(2)',12
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','datum1eaanmelding','leerlinggegevens','DatumEersteAanmelding','date',13
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','Klas','leerlinggegevens','Klas','varchar(16)',14
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','Leerfase.Leerjaar','leerlinggegevens','Leerjaar','varchar(1)',15
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','Lesperiode.Korte_omschrijving','leerlinggegevens','LesperiodeOmschrijving','varchar(1)',16
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','Relatieschooltype.Omschrijving','leerlinggegevens','TypeVervolgschool','varchar(32)',17
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','sis_bvrd0.sis_bvrd0.sis_bvrd0__behaald','leerlinggegevens','BehaaldBevorderingsresultaat','bit',18
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','sis_bvrd0.sis_bvrd0.sis_bvrd0__omschr','leerlinggegevens','Bevorderingsresultaat','varchar(16)',19
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','sis_rsch0.sis_rsch0.sis_rsch0__naam','leerlinggegevens','Basisschool','varchar(64)',20
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','Stamnr','leerlinggegevens','Stamnummer','char(6)',21
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','Studie','leerlinggegevens','Studie','varchar(16)',22
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','Vertrekreden.Omschrijving','leerlinggegevens','Vertrekreden','varchar(32)',23
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','Vertrekreden.VSV','leerlinggegevens','VertrekredenVSV','bit',24
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','Vooropleiding.Omschrijving','leerlinggegevens','Vooropleiding','varchar(1)',25
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','Administratieve_eenheid.Volledige_omschrijving','leerlinggegevens','LocatieOmschrijving','varchar(32)',26
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','sis_rtyp0.sis_rtyp0.sis_rtyp0__omschr','leerlinggegevens','TypeBasisschool','varchar(32)',27
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','sis_rtyp1.sis_rtyp1.sis_rtyp1__omschr','leerlinggegevens','TypeVorigeschool','varchar(32)',28
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','Administratieve_eenheid.Adm._Eenheid','leerlinggegevens','LocatieCode','char(6)',29
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','sis_blok0.sis_blok0.sis_blok0__brin_nr','leerlinggegevens','BRINnummer2','varchar(4)',30
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','sis_blok0.sis_blok0.sis_blok0__c_nevenvst','leerlinggegevens','CodeNevenvestiging2','varchar(2)',31
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','Vertrekreden','leerlinggegevens','Vertrekreden2','varchar(32)',32
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','sis_blok0.sis_blok0.sis_blok0__Naam','leerlinggegevens','LocatieOmschrijving2','varchar(32)',33
INSERT INTO setup.CustomMetadata SELECT 'Magister','leerlinggegevens','sis_blok0.sis_blok0.sis_blok0__c_lokatie','leerlinggegevens','LocatieCode2','char(6)',34