CREATE TABLE [Dim].[Dienstverband]
(
	[DienstverbandKey]			INT					IDENTITY (1,1) NOT FOR REPLICATION,
	[MedewerkerKey]				int					NOT NULL,
	[Dienstverband]				int					NOT NULL,
	[IsVervanging]				BIT					NOT NULL,
	[IsPoolVervanging]			BIT					NOT NULL,
	[IsUitbreiding]				BIT					NOT NULL,
	[IsHoofddienstverband]		BIT					NOT NULL,
	[BegindatumContract]		DATE				NOT NULL,
	[EinddatumContract]			DATE		  		NULL,
	[Dienstbetrekking]			nvarchar(100)		NOT NULL,
	[VervangtMedewerkerKey]		int					NOT NULL,
	[VervangtMedewerkerNaam]    NVARCHAR (255)		NOT NULL,
	[Arbeidsrelatie]			nvarchar(100)		NOT NULL,
	[CAO]						nvarchar(15)		NOT NULL,
	[ContractType]				nvarchar(100)		NOT NULL,
	[ContractOmschrijving]		nvarchar(203)		NOT NULL,
	[ContractVolgnummer]		int					NOT NULL,
	[RedenEindeDienstverband]	nvarchar(100)		NOT NULL,
	[Ketennummer]				nvarchar(100)		NOT NULL,
	[FTE_Dienstverband]			decimal(8, 4)		NULL,
	CONSTRAINT [PK_Dienstverband] PRIMARY KEY ([DienstverbandKey]),
	CONSTRAINT [FK_Dienstverband_MedewerkerKey] FOREIGN KEY ([MedewerkerKey]) REFERENCES [Dim].[Medewerker]([MedewerkerKey]),
)