CREATE TABLE [Afas].[DWH_HR_Medewerkers] (
    [Medewerker]                                NVARCHAR (15)  NULL,
    [Postcode]                                  NVARCHAR (15)  NULL,
    [Geslacht]                                  NVARCHAR (54)  NULL,
    [Woonplaats]                                NVARCHAR (50)  NULL,
    [In_dienst_dienstjaren]                     DATETIME2 (0)  NULL,
    [Geboortejaar]                              INT            NULL,
    [Geboortemaand]                             INT            NULL,
    [Geboortedag]                               INT            NULL,
    [Achternaam_init_voorvoegsel_voornaam]      NVARCHAR (54)  NULL,
    [Werkgever]                                 NVARCHAR (15)  NULL,
    [Naam]                                      NVARCHAR (255) NULL,
    [Achternaam]                                NVARCHAR (80)  NULL,
    [Volledige_achternaam]                      NVARCHAR (54)  NULL,
    [Initialen_volledige_achternaam]            NVARCHAR (54)  NULL,
    [Naamregel_tbv_adressering]                 NVARCHAR (54)  NULL,
    [Zoeknaam]                                  NVARCHAR (8)   NULL,
    [Achternaam_init_voorvoegsel_roepnaam]      NVARCHAR (255) NULL,
    [Initialen_voorvoegsel_achternaam_voornaam] NVARCHAR (255) NULL,
    [Initialen_voorvoegsel_achternaam_roepnaam] NVARCHAR (255) NULL,
    [Initialen_voorvoegsel_achternaam]          NVARCHAR (255) NULL,
    [In_dienst_ivm_signalering]                 DATETIME2 (0)  NULL,
    [In_dienst_incl_rechtsvoorganger]           DATETIME2 (0)  NULL,
    [Cao]                                       NVARCHAR (15)  NULL,
    [Omschrijving]                              NVARCHAR (80)  NULL,
    [Caotype]                                   NVARCHAR (100) NULL,
    [Telefoonnr_werk]                           NVARCHAR (255) NULL,
    [Email_werk]                                NVARCHAR (255) NULL
);

