CREATE TABLE [Afas].[DWH_HR_Dienstverbanden] (
    [Medewerker]                                       NVARCHAR (15)  NULL,
    [Vervangingsdienstverband]                         BIT            NULL,
    [Declareren_bij_Vervangingsfonds]                  BIT            NULL,
    [Poolvervanger]                                    BIT            NULL,
    [Vervangt]                                         NVARCHAR (15)  NULL,
    [Volgnummer_dienstverband_2]                       INT            NULL,
    [Uitbreidingsdienstverband]                        BIT            NULL,
    [Vervanging_binnen_eigen_FTE_bij_vrijwillige_verz] BIT            NULL,
    [Cao]                                              NVARCHAR (15)  NULL,
    [Reden]                                            NVARCHAR (100) NULL,
    [Dienstbetrekking]                                 NVARCHAR (100) NULL,
    [Aantal_FTE]                                       DECIMAL (8, 4) NULL,
    [Aard_arbeidsrelatie]                              NVARCHAR (100) NULL,
    [Dienstverband]                                    INT            NULL,
    [Type_contract]                                    NVARCHAR (100) NULL,
    [Financieringsbron_code]                           NVARCHAR (20)  NULL,
    [Volgnummer_contract]                              INT            NULL,
    [Begindatum_contract]                              DATETIME2 (0)  NULL,
    [Type_contract_code]                               NVARCHAR (20)  NULL,
    [Financieringsbron]                                NVARCHAR (100) NULL,
    [Aard_arbeidsrelatie_code]                         NVARCHAR (20)  NULL,
    [soortmedewerker]                                  NVARCHAR (100) NULL,
    [Type_verzekering_code]                            NVARCHAR (20)  NULL,
    [Type_verzekering]                                 NVARCHAR (100) NULL,
    [Dienstbetrekkingoms]                              NVARCHAR (100) NULL,
    [Arbeidsvoorwaarde_code]                           NVARCHAR (15)  NULL,
    [Omschrijving]                                     NVARCHAR (80)  NULL,
    [Dienstbetrekking_code]                            NVARCHAR (20)  NULL,
    [Einddatum_contract]                               DATETIME2 (0)  NULL,
    [soortmedewerker_code]                             NVARCHAR (20)  NULL,
    [Naam_werkgever]                                   NVARCHAR (255) NULL,
    [Datum_in_dienst]                                  DATETIME2 (0)  NULL,
    [Datum_uit_dienst]                                 DATETIME2 (0)  NULL,
    [Werkgever]                                        NVARCHAR (15)  NULL,
    [Reden_einde_dienstverband_code]                   NVARCHAR (20)  NULL,
    [Reden_einde_dienstverband]                        NVARCHAR (100) NULL,
    [Reden_uit_dienst_code]                            NVARCHAR (20)  NULL,
    [Reden_uit_dienst]                                 NVARCHAR (100) NULL,
    [Omschrijving_2]                                   NVARCHAR (80)  NULL,
    [Ketennummer_code]                                 NVARCHAR (20)  NULL,
    [Dienstverband_is_hoofddienstverband]              BIT            NULL,
    [Ketennummer]                                      NVARCHAR (100) NULL
);

