CREATE TABLE [Afas].[DWH_HR_Organigram_incl_historie] (
    [Laag_0]                       NVARCHAR (10) NULL,
    [Laag_1]                       NVARCHAR (10) NULL,
    [Laag_2]                       NVARCHAR (10) NULL,
    [Laag_3]                       NVARCHAR (10) NULL,
    [Laag_4]                       NVARCHAR (10) NULL,
    [Laag_5]                       NVARCHAR (10) NULL,
    [Laag_6]                       NVARCHAR (10) NULL,
    [Laag_7]                       NVARCHAR (10) NULL,
    [Laag_8]                       NVARCHAR (10) NULL,
    [Laag_9]                       NVARCHAR (10) NULL,
    [Bovenliggende_org_eenheid]    NVARCHAR (10) NULL,
    [Organisatorische_eenheid_oms] NVARCHAR (50) NULL,
    [Begindatum_organigram]        DATETIME2 (0) NULL,
    [Einddatum_organigram]         DATETIME2 (0) NULL,
    [Omschrijving]                 NVARCHAR (40) NULL,
    [Organisatorische_eenheid]     NVARCHAR (10) NULL,
    [Laag]                         NVARCHAR (10) NULL,
    [Koppeling_organigram]         INT           NULL,
    [Laag0_omsch]                  NVARCHAR (50) NULL,
    [Laag1_omsch]                  NVARCHAR (50) NULL,
    [Laag2_omsch]                  NVARCHAR (50) NULL,
    [Laag3_omsch]                  NVARCHAR (50) NULL,
    [Laag4_omsch]                  NVARCHAR (50) NULL,
    [Laag5_omsch]                  NVARCHAR (50) NULL,
    [Laag6_omsch]                  NVARCHAR (50) NULL,
    [Laag7_omsch]                  NVARCHAR (50) NULL,
    [Laag8_omsch]                  NVARCHAR (50) NULL,
    [Laag9_omsch]                  NVARCHAR (50) NULL,
    [Org_eenheid_type]             NVARCHAR (10) NULL,
    [Org_eenheid_type_oms]         NVARCHAR (50) NULL,
    [Leidinggevende]               NVARCHAR (15) NULL
);

