CREATE TABLE [Afas].[DWH_HR_Organigram] (
    [Actuele_hoofdleidinggevende]               NVARCHAR (15) NULL,
    [Actuele_vervanger_van_hoofdleidinggevende] NVARCHAR (15) NULL,
    [Laag_0]                                    NVARCHAR (10) NULL,
    [Laag_1]                                    NVARCHAR (10) NULL,
    [Laag_2]                                    NVARCHAR (10) NULL,
    [Laag_3]                                    NVARCHAR (10) NULL,
    [Laag_4]                                    NVARCHAR (10) NULL,
    [Laag_5]                                    NVARCHAR (10) NULL,
    [Laag_6]                                    NVARCHAR (10) NULL,
    [Laag_7]                                    NVARCHAR (10) NULL,
    [Laag_8]                                    NVARCHAR (10) NULL,
    [Laag_9]                                    NVARCHAR (10) NULL,
    [Bovenliggende_org_eenheid]                 NVARCHAR (10) NULL,
    [Koppeling_organigram]                      INT           NULL,
    [Begindatum_organigram]                     DATETIME2 (0) NULL,
    [Einddatum_organigram]                      DATETIME2 (0) NULL,
    [Omschrijving_organigram]                   NVARCHAR (40) NULL,
    [Organisatorische_eenheid]                  NVARCHAR (10) NULL,
    [Laag]                                      NVARCHAR (10) NULL,
    [Laag1_omsch]                               NVARCHAR (50) NULL,
    [Laag2_omsch]                               NVARCHAR (50) NULL,
    [Laag3_omsch]                               NVARCHAR (50) NULL,
    [Omschrijving_organisatorische_eenheid]     NVARCHAR (50) NULL,
    [Laag4_omsch]                               NVARCHAR (50) NULL,
    [Werkgever]                                 NVARCHAR (10) NULL,
    [Laag5_omsch]                               NVARCHAR (50) NULL,
    [Laag6_omsch]                               NVARCHAR (50) NULL,
    [Laag7_omsch]                               NVARCHAR (50) NULL,
    [Laag8_omsch]                               NVARCHAR (50) NULL,
    [Laag9_omsch]                               NVARCHAR (50) NULL,
    [Rapportage_org_eenheid]                    NVARCHAR (10) NULL
);

