CREATE VIEW dwh.[contactpersoon] AS
SELECT
    c.[unid],
    c.[dataanmk],
    c.[datwijzig],
    c.[uidaanmk],
    c.[uidwijzig],
    c.[klantid],
    c.[status],
    c.[attentieid],
    c.[attentiemelding],
    c.[bedrijfarchief],
    c.[anaam],
    c.[tvoegsel],
    c.[rnaam],
    c.[vletters],
    c.[titel],
    c.[achtervoegsel],
    c.[geslacht],
    c.[geboren],
    c.[voertaalid],
    c.[afdeling],
    c.[functie],
    c.[spec2],
    c.[verantwoordingid],
    c.[rolid],
    r.[tekst] AS [rol],
    c.[tel1],
    c.[teloms1],
    c.[tel2],
    c.[teloms2],
    c.[fax1],
    c.[faxoms1],
    c.[email],
    c.[email_opt_in],
    c.[email_hoofdpersoon],
    [datexport] = null,
    c.[tel1p],
    c.[teloms1p],
    c.[tel2p],
    c.[teloms2p],
    c.[emailp],
    [kingcpnummer] = null,
    c.[linkedin],
    c.[foto],
    c.[personid],
    c.[straat1p],
    c.[nummer1p],
    c.[postcode1p],
    c.[staat1p],
    c.[plaats1p],
    c.[land1pid],
    c.[exveld002]  -- used as secondary [linkedin] address
FROM dbo.[contactpersoon] c
    LEFT JOIN dbo.[rol] r ON r.[unid] = c.[rolid];
