CREATE VIEW dwh.[klant] AS
SELECT
    k.[unid],
    k.[dataanmk],
    k.[datwijzig],
    k.[uidaanmk],
    k.[uidwijzig],
    k.[status],
    k.[archiefid],
    k.[archiefdatum],
    k.[ag_vnr],
    k.[pg_vnr],
    k.[pl_vnr],
    k.[bedrijf],
    [accountviewzoekcode] = null,
    [cashzoekcode] = null,
    [exactzoekcode] = null,
    [financialszoekcode] = null,
    [kingzoekcode] = null,
    k.[betalingsconditieid],
    k.[spec1],
    k.[tel1],
    k.[fax1],
    k.[fac_gebruiken],
    k.[fac_bedrijf],
    k.[fac_spec1],
    k.[fac_tav],
    k.[fac_spec2],
    k.[fac_tel1],
    [fac_aantal_kopien] = null,
    k.[fac_andereklantid],
    k.[g_rekening_procent],
    k.[grootteid],
    bg.[tekst] AS [grootte],
    k.[debnr],
    k.[potnr],
    k.[www],
    k.[email],
    [datexport] = null,
    k.[behandelaarid],
    k.[oprichtingsjaar],
    k.[rechtsvormid],
    k.[kvknr],
    k.[rektype],
    k.[reknr],
    k.[btwnr],
    k.[typeringid],
    k.[foto],
    [verwerktcoda] = null,
    k.[attentieid],
    k.[attentiemelding],
    k.[geocode_lat],
    k.[geocode_lon],
    [afkorting] = null,
    [print_invoice] = null,
    [use_invoice_email] = k.[invoice_send_option],
    k.[special_debtor],
    k.[invoiceemailtemplateid],
    k.[invoice_stationeryid],
    k.[regioid],
    r.[tekst] AS [regio],
    k.[straat1],
    k.[nummer1],
    k.[postcode1],
    k.[staat1],
    k.[plaats1],
    k.[land1id],
    l1.[landnaam] AS [land1],
    k.[straat2],
    k.[nummer2],
    k.[postcode2],
    k.[staat2],
    k.[plaats2],
    k.[land2id],
    l2.[landnaam] AS [land2],
    k.[fac_straat1],
    k.[fac_nummer1],
    k.[fac_postcode1],
    k.[fac_staat1],
    k.[fac_plaats1],
    k.[fac_land1id],
    k.[rek_biccode],
    k.[invoice_mail_combine_invoice_attachments],
    k.[geocode_state],
    k.[use_invoicereminder_email],
    k.[invoice_reminder_planid],
    k.[invoice_document_format],
    k.[default_invoicing_style_person],
    k.[default_invoicing_style_article],
    k.[default_invoicing_style_free_product],
    k.[default_invoice_shift_span_type],
    k.[default_invoice_shift_span_amount],
    k.[default_invoice_shift_span_relative_to]
FROM dbo.[klant] k
    LEFT JOIN dbo.[bedrijfgrootte] bg ON bg.[unid] = k.[grootteid]
    LEFT JOIN dbo.[land] l1 ON l1.[unid] = k.[land1id]
    LEFT JOIN dbo.[land] l2 ON l2.[unid] = k.[land2id]
    LEFT JOIN dbo.[regio] r ON r.[unid] = k.[regioid];
