CREATE VIEW dwh.[project] AS
SELECT
    p.[unid],
    p.[dataanmk],
    p.[datwijzig],
    p.[uidaanmk],
    p.[uidwijzig],
    p.[status],
    p.[archiefid],
    p.[archiefdatum],
    p.[acquisition_goalid],
    p.[attentieid],
    p.[attentiemelding],
    p.[projectgroepid],
    p.[heeft_andere_eindklant],
    p.[eindklantid],
    p.[contactpersoon_eindklant],
    p.[las_tonen_cp_eindklant],
    p.[is_template],
    p.[template_name],
    p.[fgbkid],
    p.[projectnr],
    p.[vestigingid],
    ves.[tekst] AS [vestiging],
    p.[projectnaam],
    p.[productgroepid],
    p.[productid],
    p.[behandeldid],
    p.[projecttype],
    p.[periodetype],
    p.[datacceptatie],
    p.[leverdatum],
    p.[startdatum],
    p.[einddatum],
    p.[beeindigddatum],
    p.[workflow_verstuurd],
    p.[beeindigd],
    p.[fklantkenmerk],
    p.[fandereklant],
    p.[fklantnaam],
    p.[fspec1],
    p.[ftav],
    p.[fspec2],
    p.[cklantnaam],
    p.[cspec1],
    p.[ctav],
    p.[cspec2],
    p.[aklantnaam],
    p.[aspec1],
    p.[atav],
    p.[aspec2],
    p.[ftel1],
    p.[f_andere_dot],
    p.[f_product_andere_dot],
    p.[invoice_templateid],
    p.[f_btwid],
    p.[f_bijlage],
    p.[f_nd_op_bijlage],
    p.[f_comm_op_bijlage],
    p.[f_proj_naam_op_bijlage],
    p.[f_proj_nr_op_bijlage],
    p.[f_opslagpercentage_op_bijlage],
    p.[f_tariefnaam_op_bijlage],
    p.[f_email],
    p.[fprojecttype],
    p.[fper],
    p.[fsoort],
    p.[fprojectmin],
    p.[fprojectmax],
    p.[fheeftprojectmax],
    p.[ink_in_mnd_lim],
    p.[ink_in_project_lim],
    p.[fprojectprijs],
    p.[factuurdatum],
    p.[fmoederproject],
    p.[fmoederprojectid],
    p.[falleen_moeder_tonen],
    p.[f_uurtabel_weergave],
    p.[holdfactuur],
    p.[uurtypen_op_factuur],
   [cmoederproject] = null,
   [cmoederprojectid] = CAST(null AS UNIQUEIDENTIFIER),
    p.[cklant1],
    p.[cklant2],
    p.[cogdid],
    p.[contractstatusid],
    p.[aanvraag_vnr],
    p.[interessecijferid],
    p.[interessefaseid],
    p.[nultarief],
    p.[verschotten],
    p.[las_uren_on_hold],
    [verwerktcoda] = null,
    p.[invuldatum],
    [afkorting] = null,
    [use_invoice_email] = p.[invoice_send_option] ,
    [print_invoice] = null,
    p.[invoice_stationeryid],
    p.[betalingsconditieid],
    p.[invoiceemailtemplateid],
    p.[astraat],
    p.[anummer],
    p.[apostcode],
    p.[astaat],
    p.[aplaats],
    p.[alandid],
    p.[cstraat],
    p.[cnummer],
    p.[cpostcode],
    p.[cstaat],
    p.[cplaats],
    p.[clandid],
    p.[fstraat],
    p.[fnummer],
    p.[fpostcode],
    p.[fstaat],
    p.[fplaats],
    p.[flandid],
    p.[lift3_invoicedate],
    p.[sales_target],
    p.[use_customer_approval],
    p.[deviating_approval_contactid],
    p.[invoice_mail_combine_invoice_attachments],
    p.[hour_note_required],
    p.[customer_approval_salutation],
    p.[invoice_shift_span_type],
    p.[invoice_shift_span_amount],
    p.[invoice_shift_span_relative_to],
    p.[customer_approval_empty_periods],
    p.[lead_sourceid],
    p.[invoice_document_format],
    p.[invoice_ubl_configurationid],
    vo1.[tekst] AS [sales_channel]
FROM dbo.[project] p
    LEFT JOIN dbo.[vestiging] ves ON ves.[unid] = p.[vestigingid]
    LEFT JOIN dbo.[vrijopzoek] vo1 ON vo1.[Kaartcode] = 'EXTRAOPZ1PROJ' AND vo1.[unid] = p.[extraopz1]
    LEFT JOIN dbo.[ChecklistProjectLink] cp
    ON cp.[projectid] = p.[unid]
        AND cp.[gechecked] = 1
        AND cp.[checkid] = '674DB883-62F0-4CA2-A950-ED67D639E246';
