CREATE VIEW dwh.[wcontract] AS
SELECT
    wc.[unid],
    wc.[dataanmk],
    wc.[datwijzig],
    wc.[uidaanmk],
    wc.[uidwijzig],
    wc.[status],
    wc.[archiefid],
    wc.[archiefdatum],
    wc.[contractsoortid],
    cs.[tekst] AS [contractsoort],
   [procent_naar_0] = null,
    wc.[procent],
    wc.[retour],
    wc.[pensioengegevens_volledig],
    wc.[verzekeringen_volledig],
    wc.[salaris],
    wc.[nettobruto],
    wc.[salperiodeid],
    wc.[salaris_schaal],
    wc.[toeslag],
    wc.[toeslag_bn],
    wc.[toeslag_periodeid],
    wc.[toeslag_typeid],
    wc.[lvnloop_rek_bedrag],
    wc.[lvnloop_rek_perc],
    wc.[lvnloop_rek_levid],
    wc.[lvnloop_rekening],
    wc.[spaarloon],
    wc.[spaarloon_bn],
    wc.[spaarloon_periodeid],
    wc.[premiespaarloon],
    wc.[premiespaarloon_bn],
    wc.[premiespaarloon_periodeid],
    wc.[pensioen],
    wc.[pensioen_bn],
    wc.[pensioen_periodeid],
    wc.[pensioen_type],
    wc.[pensioen_leverancierid],
    wc.[wao_gat],
    wc.[wao_gat_bn],
    wc.[wao_gat_periodeid],
    wc.[wao_gat_type],
    wc.[wao_gat_leverancierid],
    wc.[ziektekosten],
    wc.[ziektekosten_bn],
    wc.[ziektekosten_periodeid],
    wc.[ziektekosten_type],
    wc.[ziektekn_leverancierid],
    wc.[onkostenvergoeding],
    wc.[onkostenvergoeding_bn],
    wc.[onkostenvergoeding_periodeid],
    wc.[reiskosten],
    wc.[reiskosten_bn],
    wc.[reiskosten_periodeid],
    [functie] = f.tekst,
    wc.[vestigingid],
    ves.[tekst] AS [vestiging],
    wc.[startdatum],
    wc.[einddatum],
    wc.[oplbudget],
    wc.[oplperiodeid],
    wc.[oplbudget_bn],
    [vakdagen] = null,
    wc.[bonusregeling],
    wc.[bonusregeling_bn],
    wc.[bonusregeling_periodeid],
    wc.[eb_auto],
    wc.[eb_auto_bn],
    wc.[eb_auto_periodeid],
    wc.[eb_auto_type],
    wc.[eb_auto_kenteken],
    wc.[eb_tel],
    wc.[eb_tel_bn],
    wc.[eb_tel_periodeid],
    wc.[eb_tel_type],
    wc.[eb_tel_nr],
    wc.[eb_pc],
    wc.[eb_pc_bn],
    wc.[eb_pc_periodeid],
    wc.[eb_pc_type],
    wc.[eb_pc_nr],
    wc.[eb_reisvergoeding],
    wc.[eb_reisvergoeding_bn],
    wc.[eb_reisvergoeding_periodeid],
    [begin_overuren] = null,
    [begin_per_overuren] = null,
    wc.[vakperiodeid],
    [studentenregeling] = null,
    wc.[procesid],
    wc.[budgethouderid],
    wc.[proeftijdid],
    wc.[opzegtermijnid],
    [belastinggroep] = null,
    wc.[uurtarief],
    wc.[inkoopprijs],
    wc.[vorig_wcontractid],
    [adv_regeling] = null,
    [adv_percentage] = null,
    [verwerktcoda] = null,
    wc.[prive_km_quotum],
    wc.[interne_mw],
    wc.[taxcredit],
    wc.[employee_contract_groupid],
    wc.[werknemerid]
FROM dbo.[wcontract] wc
    INNER JOIN dbo.[contractsoort] cs ON cs.[unid] = wc.[contractsoortid]
    LEFT JOIN dbo.[vestiging] ves ON ves.[unid] = wc.[vestigingid]
	left join dbo.[functie] f on (f.unid = wc.job_descriptionid);