CREATE VIEW dwh.[werknemer] AS
SELECT
    w.[unid],
    w.[dataanmk],
    w.[datwijzig],
    w.[uidaanmk],
    w.[uidwijzig],
    w.[status],
    w.[archiefid],
    w.[archiefdatum],
    w.[anaam],
    w.[vnaam],
    w.[tussen],
    w.[rnaam],
    w.[inits],
    w.[titel],
    w.[achtervoegsel],
    w.[meisjesnaam],
    w.[tel1],
    w.[teloms1],
    w.[tel2],
    w.[teloms2],
    w.[tel3],
    w.[teloms3],
    w.[email],
    [datexport] = null,
    w.[geslacht],
    w.[geboren],
    DATEPART(YEAR, w.[geboren]) AS [geboortejaar],
    w.[gebplaats],
    w.[sollicitatie_aanleidingid],
    sa.[tekst] AS [sollicitatie_aanleiding],
    w.[gesolliciteerd_op_functieid],
    sf.[tekst] AS [gesolliciteerd_op_functie],
    w.[geblandid],
    w.[nationaliteitid],
    w.[opleidingid],
    w.[richtingid],
    w.[rijbewijs],
    w.[auto],
    w.[ovid],
    w.[cvref],
    w.[persnr],
    w.[pmwnr],
    w.[paspoorttypeid],
    w.[paspoortnr],
    w.[paspoortgeldigtot],
   [belastinggroep] = null,
    w.[sofinr],
    w.[sofinummer_buitenland],
    w.[uurtarief],
    w.[inkoopprijs],
    w.[reknr1],
    w.[rektype1],
    w.[rek1banknaam],
    w.[rek1bankplaats],
    w.[reknr2],
    w.[rektype2],
    w.[rek2banknaam],
    w.[rek2bankplaats],
    w.[studiestatusid],
    w.[leefsituatieid],
    w.[stdbeschikbaarheid],
    w.[invuldatum],
    w.[wn_invuldatum],
    w.[leverancierid],
    w.[vestigingid],
    ves.[tekst] AS [vestiging],
    w.[budgethouderid],
    w.[datumindienst],
    w.[hi_datumindienst],
    w.[datumuitdienst],
    w.[datpotwn],
    w.[datpotwn] AS [Datum_PotentieelWerknemer],
    w.[datwn],
    w.[datwn] AS [Datum_StartDatumContract],
    w.[foto],
    [las_toon_in_smoelenboek] = null,
    [verwerktcoda] = null,
    w.[attentieid],
    w.[attentiemelding],
    w.[sos_naam],
    w.[sos_relatieid],
    w.[sos_tel1],
    w.[sos_tel1_omschrijving],
    w.[sos_tel2],
    w.[sos_tel2_omschrijving],
    w.[regeling1],
    w.[regeling1nr],
    w.[regeling1van],
    w.[regeling1tot],
    w.[regeling2],
    w.[regeling2nr],
    w.[regeling2van],
    w.[regeling2tot],
    w.[regeling3],
    w.[regeling3nr],
    w.[regeling3van],
    w.[regeling3tot],
    w.[regeling4],
    w.[regeling4nr],
    w.[regeling4van],
    w.[regeling4tot],
    w.[urenmanagerid],
    w.[linkedin],
    w.[boekhoud_url],
    w.[geocode_lat],
    w.[geocode_lon],
    w.[beschikbaar_vanaf],
    w.[straat1],
    w.[nummer1],
    w.[postcode1],
    w.[staat1],
    w.[plaats1],
    w.[land1id],
    w.[sos_straat],
    w.[sos_nummer],
    w.[sos_postcode],
    w.[sos_plaats],
    w.[sos_landid],
    w.[rek1biccode],
    w.[graduation_date],
    w.[geocode_state],
    w.[extra_niveau] AS [extra_niveauid],
    exniveau.[tekst] AS [extra_niveau],
    w.[km_submitdate],
    w.[employeetypeid],
    w.[extra_team] AS [extra_teamid],
    exteam.[tekst] AS [extra_team],
    w.[recruiterid],
    w.[hr_managerid],
    w.[informerid],
    w.[informername],
    w.[exveld002] AS [nextappointment_jaarid],
    ex02.[tekst] AS [nextappointment_jaar],
    w.[extraopz5] AS [nextappointment_maandid],
    vo5.[tekst] AS [nextappointment_maand],
    w.[extraopz6] AS [HR_ContactPersoonid],
    vo6.[tekst] AS [HR_ContactPersoon],
    w.[exveld003] AS [leidinggevendeid],
    ex03.[tekst] AS [Leidinggevende],
    w.[exveld004] AS [business_unitid],
    ex04.[tekst] AS [business_unit],
    w.[exveld005]  AS [functieid],
    ex05.[tekst] AS [functie]
FROM dbo.[werknemer] w
    -- Leidinggevende
    LEFT JOIN dbo.[vrijopzoek] ex03 ON ex03.[Kaartcode] = 'TBL01EXVELD003' AND ex03.[unid] = w.[exveld003]
    -- Business Unit
    LEFT JOIN dbo.[vrijopzoek] ex04 ON ex04.[Kaartcode] = 'TBL01EXVELD004' AND ex04.[unid] = w.[exveld004]
    -- Functie
    LEFT JOIN dbo.[vrijopzoek] ex05 ON ex05.[Kaartcode] = 'TBL01EXVELD005' AND ex05.[unid] = w.[exveld005]
    -- Team
    LEFT JOIN dbo.[vrijopzoek] exteam ON exteam.[Kaartcode] = 'EXTRATEAMEMPL' AND exteam.[unid] = w.[extra_team]
    -- Niveau
    LEFT JOIN dbo.[vrijopzoek] exniveau ON exniveau.[Kaartcode] = 'EXTRANIVEAUEMPL' AND exniveau.[unid] = w.[extra_niveau]

    -- jaartal volgend gesprek
    LEFT JOIN dbo.[vrijopzoek] ex02 ON ex02.[Kaartcode] = 'TBL01EXVELD002' AND ex02.[unid] = w.[exveld002]
    -- maandtal volgend gesprek
    LEFT JOIN dbo.[vrijopzoek] vo5 ON vo5.[Kaartcode] = 'EXTRAOPZ5WER' AND vo5.[unid] = w.[extraopz5]

    -- P&O'er
    LEFT JOIN dbo.[vrijopzoek] vo6 ON vo6.[Kaartcode] = 'EXTRAOPZ6WER' AND vo6.[unid] = w.[extraopz6]
    -- Vestiging
    LEFT JOIN dbo.[vestiging] ves ON ves.[unid] = w.[vestigingid]
    -- Solicitatieaanleiding
    LEFT JOIN dbo.[sollicitatie_aanleiding] sa ON sa.[unid] = w.[sollicitatie_aanleidingid]
    -- Sollicatatiefunctie
    LEFT JOIN dbo.[functie] sf ON sf.[unid] = w.[gesolliciteerd_op_functieid];
