#
# Module manifest for module 'CustomFunctions'
#
# Generated by: Frank Hartgring
#
# Generated on: 08-Aug-16
#
# PLEASE NOTE: LINES BELOW THIS ONE ARE UPDATED BY 'THE PIPELINE' (Update-PSD1.ps1)
# ModuleVersion Number bumping rules: Major: only changed manually; Minor: hash over 'Pipeline' files changed or hash over function names changed; Build: more than 1 Function/test pair has changed hash; Revision: hash changed for 1 function / test

# FunctionNamesHash = '38ce5b4d67b8f2ff2261dd4ed4cd5da3'
# InfraFilesContentHashes = 'db0452aff6e4355b38455a0b6485106c', '36fee99aabebee75d2e6b6a58269f2c5', '29dcfa817429158129472cde7f792714', '3bc209735190cf214a92abd116f89f67', '2518b3eb5d4f6fa89c14b8ba0b031950', '4a2ce56eda840e67ba62e5bcf825951a', '6b39598842fafb1dbdb7f98451e5db90'
# FunctionContentHashes = 'b0a93e1e500078d0ed6af1c7e3743a0f', 'ecba22e57945493962bce745b96f59c9', '62b2e141d132a9a951b39118fc9b1e36', '2730f63b70ca6116efdc721e1aa956b4aa7eda1aa1d55c8af86c26c7d7ba74ad', '76757bf6df2eab092cfcd60924180cc9', '5a74aa537c067f9229c7abe9c47e3490', '64ba3e6fe56be3ea5e71f602fc09407eba920bcda3ac463f5daa224fc50bb3fb', '69b3adeadad71ec5dcf74e731705aab3', '4412e305c7ae8fcd62f5e4de5fbed05b', 'c9596e751f4ce35ddf3c3f73aa48e7173fb900b24587f421e5b1b2b9d1eb0b93', '89b21b89a8f2d9cd15e40dba0f3e50528b69cf38fef47b08bdfe2730b486c2c9', '137a51bb8b6777f7766948228c887c18', '742021e2cabb50e6df71fddad582b3cb3bcae34f58e09befff7a448b56b63ba9', '9ecbcf97407fb57e1a1d71cf40b776eac50741d738dcc4b54b6d74b967c9998f', '66fe6b8cff2a99b7a7b2db18e40ce328776c2dd26d848db5240aa6ee96bfd3dc', '5aed70234e2132574f264c43f84e6521', '4de0870e18fccd93bef6bc74fdcbed15', 'f817d436a5b3c53b93419d0106cfc3a260668a3f2330ac1ce9f10606ab04d13e', 'b23aef95f6cc0abc468737b488b4d2c641f851aaf66bcee5f85e29ee945c61c4', 'a01e0880441863c5138764756534add3187c554a0aa9f9162fea315466b59508', 'b5e600fbe62168c31f9a229e8d8dc8fddc4d5193f30c20ebcafecbdc44d05b2a', '28774e572bdbfc8f60c7f2d931f319d1249e06066454b97c02259cdc285c30a3', 'efdbe9db2ab11fe2def7d1cd3630c933', '01553bb535edc9160e897ed9592e1e04', '75ab154c1c466a8e717a94c12203ca1d', '4b260c5602ae461c749f55c2a28292c008b678f06a6eaba5f81ceaf5e6679461', '4db3366e790b2c9287545917628cdd7bdf8e9a14250e1002bcb6ed317902827d'

# FunctionsToExport and all hashes updated by frodo.bouw / D:\git\CustomFunctions\CustomFunctions\Update-PSD1.ps1 at 2017-06-08 13:48:38
# ModuleVersion Number bumped from 0.3.1 to '0.4.2'

@{

# Script module or binary module file associated with this manifest.
RootModule = 'CustomFunctions.psm1'

# Version number of this module.
ModuleVersion = '0.4.2'

# ID used to uniquely identify this module
GUID = '6d5bdf5e-b21d-4d31-bff0-6f91153d1b00'

# Author of this module
Author = 'Frank Hartgring et al'

# Company or vendor of this module
CompanyName = 'OGD ict-diensten'

# Copyright statement for this module
Copyright = '(c) 2017 OGD. All rights reserved.'

# Description of the functionality provided by this module
Description = 'this module contains functions which are commonly used by OGD Business Team Operations'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = '3.0'

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'CustomFunctions.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = 'Connect-ExchangeOnline', 'Connect-ExchangeOnlinePartner', 'Connect-SCCM', 'Convert-PSObjectToHashtable', 'Disable-RemoteDesktop', 'Enable-RemoteDesktop', 'Get-ADUserLastLogon', 'Get-LockedOutLocation', 'Get-password', 'Get-PendingReboot', 'Get-RemoteSession', 'Get-SCEPMalwareDetected', 'Get-StoredCredential', 'Get-Uptime', 'Get-WindowsServiceTag', 'Get-WordPass', 'Invoke-RemoveDiacritic', 'Invoke-TouchFile', 'New-Password', 'Out-Eventlog', 'Out-LogFile', 'Remove-Diacritic', 'Remove-ItemTooLongPath', 'Remove-RemoteSession', 'Remove-StoredCredential', 'Save-StoredCredential', 'Show-StoredCredential'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

