CREATE TABLE [TOPdesk].[changeactivity] (
    [approved]                     BIT            NOT NULL,
    [approveddate]                 DATETIME       NULL,
    [briefdescription]             NVARCHAR (255) NOT NULL,
    [categoryid]                   VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [changeid]                     VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [currentplantimetaken]         BIGINT         NOT NULL,
    [dataanmk]                     DATETIME       NULL,
    [datwijzig]                    DATETIME       NULL,
    [number]                       NVARCHAR (255) NOT NULL,
    [operatorgroupid]              VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [operatorid]                   VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [originalplantimetaken]        BIGINT         NOT NULL,
    [changephase]                  INT            NOT NULL,
    [plannedfinaldate]             DATETIME       NULL,
    [plannedstartdate]             DATETIME       NULL,
    [rejected]                     BIT            NOT NULL,
    [rejecteddate]                 DATETIME       NULL,
    [resolved]                     BIT            NOT NULL,
    [resolveddate]                 DATETIME       NULL,
    [skipped]                      BIT            NOT NULL,
    [skippeddate]                  DATETIME       NULL,
    [started]                      BIT            NOT NULL,
    [starteddate]                  DATETIME       NULL,
    [status]                       INT            NULL,
    [subcategoryid]                VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [timetaken]                    BIGINT         NOT NULL,
    [uidaanmk]                     VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [uidwijzig]                    VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [unid]                         VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [activitystatusid]             VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [maystart]                     BIT            NOT NULL,
    [ref_change_brief_description] NVARCHAR (255) NOT NULL,
    [AuditDWKey]                   INT            NOT NULL,
    [SourceDatabaseKey]            INT            NULL,
    [activitytemplateid]           VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL
);

