CREATE TABLE [TOPdesk].[change] (
    [aanmelderafdelingid]  VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [aanmelderemail]       NVARCHAR (255) CONSTRAINT [DF_change_aanmelderemail] DEFAULT (N'[Onbekend]') NOT NULL,
    [aanmelderlokatieid]   VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [aanmeldertelefoon]    NVARCHAR (255) CONSTRAINT [DF_change_aanmeldertelefoon] DEFAULT (N'[Onbekend]') NOT NULL,
    [aanmeldervestigingid] VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [briefdescription]     NVARCHAR (255) NOT NULL,
    [calc_type_authdate]   INT            NOT NULL,
    [calc_type_finaldate]  INT            NOT NULL,
    [calc_type_impldate]   INT            NOT NULL,
    [calldate]             DATETIME       NULL,
    [categoryid]           VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [changetype]           INT            NOT NULL,
    [closed]               BIT            NOT NULL,
    [closeddate]           DATETIME       NULL,
    [completed]            BIT            NOT NULL,
    [completeddate]        DATETIME       NULL,
    [currentphase]         INT            NOT NULL,
    [dataanmk]             DATETIME       NULL,
    [datwijzig]            DATETIME       NULL,
    [finaldate]            DATETIME       NULL,
    [externalnumber]       NVARCHAR (255) NOT NULL,
    [impactid]             VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [incidentid]           VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [isurgent]             BIT            NOT NULL,
    [managerid]            VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [number]               NVARCHAR (255) NOT NULL,
    [objectid]             VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [operatorgroupid]      VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [plannedauthdate]      DATETIME       NULL,
    [plannedfinaldate]     DATETIME       NULL,
    [plannedimpldate]      DATETIME       NULL,
    [implementationdate]   DATETIME       NULL,
    [rejecteddate]         DATETIME       NULL,
    [authorizationdate]    DATETIME       NULL,
    [started]              BIT            NOT NULL,
    [starteddate]          DATETIME       NULL,
    [statusid]             VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [subcategoryid]        VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [submitdate]           DATETIME       NULL,
    [templateid]           VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [timetaken]            BIGINT         NOT NULL,
    [typeid]               VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [uidaanmk]             VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [uidwijzig]            VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [unid]                 VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [withevaluation]       BIT            NOT NULL,
    [vrijelogisch2]        BIT            NULL,
    [vrijeopzoek3]         VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [plannedstartdate]     DATETIME       NULL,
    [canceledbypersonid]   VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [canceledbyoperatorid] VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [canceldate]           DATETIME       NULL,
    [priorityid]           VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [rejected]             BIT            NOT NULL,
    [pro_rejecteddate]     DATETIME       NULL,
    [aanmeldernaam]        NVARCHAR (255) CONSTRAINT [DF_change_aanmeldernaam] DEFAULT (N'[Onbekend]') NOT NULL,
    [status]               INT            NULL,
    [vrijelogisch3]        BIT            NULL,
    [vrijememo1]           NVARCHAR (MAX) NULL,
    [vrijememo2]           NVARCHAR (MAX) NULL,
    [AuditDWKey]           INT            NOT NULL,
    [SourceDatabaseKey]    INT            NULL
);



