CREATE TABLE [TOPdesk].[herhaling] (
    [unid]              VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [planningid]        VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [periode]           NVARCHAR (255) NOT NULL,
    [jaarinterval]      INT            NOT NULL,
    [jaarperiode]       NVARCHAR (255) NOT NULL,
    [maandvanjaar]      INT            NOT NULL,
    [weekvanjaar]       INT            NOT NULL,
    [dagvanjaar]        INT            NOT NULL,
    [maandinterval]     INT            NOT NULL,
    [maandperiode]      NVARCHAR (255) NOT NULL,
    [weekvanmaand]      INT            NOT NULL,
    [dagvanmaand]       INT            NOT NULL,
    [weekinterval]      INT            NOT NULL,
    [maandag]           BIT            NOT NULL,
    [dinsdag]           BIT            NOT NULL,
    [woensdag]          BIT            NOT NULL,
    [donderdag]         BIT            NOT NULL,
    [vrijdag]           BIT            NOT NULL,
    [zaterdag]          BIT            NOT NULL,
    [zondag]            BIT            NOT NULL,
    [daginterval]       INT            NOT NULL,
    [starttijd]         BIGINT         NOT NULL,
    [dataanmk]          DATETIME       NOT NULL,
    [datwijzig]         DATETIME       NOT NULL,
    [doorlooptijd]      BIGINT         NULL,
    [uidaanmk]          VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [uidwijzig]         VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [dagvanweek]        INT            NOT NULL,
    [AuditDWKey]        INT            NOT NULL,
    [SourceDatabaseKey] INT            NULL
);

