CREATE TABLE [TOPdesk].[object_zonder_dubbele_regels] (
    [ref_aanspreekpuntid]     VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [ref_budgethouderid]      VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [ref_configuratieid]      VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [ref_groepid]             VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [ref_leverancier]         NVARCHAR (255) NULL,
    [ref_licentiesoortid]     VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [ref_plaats]              NVARCHAR (255) NULL,
    [ref_soort]               NVARCHAR (255) NULL,
    [ref_vestiging]           NVARCHAR (255) NULL,
    [statusid]                VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [type]                    NVARCHAR (255) NULL,
    [unid]                    VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [ref_ordernummer]         NVARCHAR (255) NULL,
    [ref_leasecontractnummer] NVARCHAR (255) NULL,
    [ref_leaseperiode]        INT            NULL,
    [ref_persoongroep]        NVARCHAR (255) NULL,
    [ref_aanschafdatum]       DATETIME       NULL,
    [ref_leaseaanvangsdatum]  DATETIME       NULL,
    [ref_leaseeinddatum]      DATETIME       NULL,
    [ref_aankoopbedrag]       MONEY          NULL,
    [ref_leaseprijs]          MONEY          NULL,
    [ref_restwaarde]          MONEY          NULL,
    [ref_hostnaam]            NVARCHAR (255) NULL,
    [ref_ipadres]             NVARCHAR (255) NULL,
    [ref_type]                NVARCHAR (255) NULL,
    [ref_specificatie]        NVARCHAR (255) NULL,
    [ref_attentieid]          VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [ref_opmerking]           NVARCHAR (255) NULL,
    [ref_gebruiker]           NVARCHAR (255) NULL,
    [ref_persoon]             NVARCHAR (255) NULL,
    [ref_naam]                NVARCHAR (255) NULL,
    [ref_lokatie]             NVARCHAR (255) NULL,
    [ref_serienummer]         NVARCHAR (255) NULL,
    [AuditDWKey]              INT            NOT NULL,
    [SourceDatabaseKey]       INT            NULL
);

