CREATE TABLE [TOPdesk].[probleem] (
    [afgemeld]                     BIT            NOT NULL,
    [afgemeldbf]                   BIT            NOT NULL,
    [archiefredenid]               VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [categorieid]                  VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [doorlooptijdbfid]             VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [doorlooptijdid]               VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [gereed]                       BIT            NOT NULL,
    [gereedbf]                     BIT            NOT NULL,
    [impactbfid]                   VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [impactid]                     VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [oorzaakid]                    VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [ref_domein]                   NVARCHAR (255) NOT NULL,
    [ref_specificatie]             NVARCHAR (255) NOT NULL,
    [status]                       INT            NOT NULL,
    [statusid]                     VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [uidaanmk]                     VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [uidwijzig]                    VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [vrijeopzoek1]                 VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [aanmaakdatum]                 DATETIME       NULL,
    [aanmaakdatumbf]               DATETIME       NULL,
    [dataanmk]                     DATETIME       NULL,
    [datumafgemeld]                DATETIME       NULL,
    [datumafgemeldbf]              DATETIME       NULL,
    [datumgereed]                  DATETIME       NULL,
    [datumgereedbf]                DATETIME       NULL,
    [datwijzig]                    DATETIME       NULL,
    [streefdatum]                  DATETIME       NULL,
    [streefdatumbf]                DATETIME       NULL,
    [kostenbegroot]                MONEY          NOT NULL,
    [kostenverwacht]               MONEY          NOT NULL,
    [onkosten]                     MONEY          NOT NULL,
    [onkostenbf]                   MONEY          NOT NULL,
    [tijdbegroot]                  BIGINT         NOT NULL,
    [tijdbesteed]                  BIGINT         NOT NULL,
    [tijdbesteedbf]                BIGINT         NOT NULL,
    [tijdverwacht]                 BIGINT         NOT NULL,
    [totalekosten]                 MONEY          NOT NULL,
    [totaletijd]                   BIGINT         NOT NULL,
    [refcombi_afgemeld]            BIT            NOT NULL,
    [refcombi_datumafgemeld]       DATETIME       NULL,
    [refcombi_datumgereed]         DATETIME       NULL,
    [refcombi_gereed]              BIT            NOT NULL,
    [refcombi_beheerder]           NVARCHAR (255) NOT NULL,
    [refcombi_tijdbesteed]         BIGINT         NOT NULL,
    [minutendoorlooptijd]          BIGINT         NOT NULL,
    [minutendoorlooptijdbf]        BIGINT         NOT NULL,
    [refcombi_minutendoorlooptijd] BIGINT         NOT NULL,
    [korteomschrijvingbf]          NVARCHAR (255) NOT NULL,
    [refcombi_korteomschrijving]   NVARCHAR (255) NOT NULL,
    [ref_behandelaar]              NVARCHAR (255) NOT NULL,
    [ref_domeinprobleem]           NVARCHAR (255) NOT NULL,
    [ref_specificatieprobleem]     NVARCHAR (255) NOT NULL,
    [naam]                         NVARCHAR (255) NOT NULL,
    [operatorgroupid]              VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [urgencyid]                    VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [priorityid]                   VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [AuditDWKey]                   INT            NOT NULL,
    [SourceDatabaseKey]            INT            NULL,
    [unid]                         VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [actiedoorid]                  VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [domeinid]                     VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [domeinprobleemid]             VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [specificatieid]               VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
    [specificatieprobleemid]       VARCHAR (36)   COLLATE SQL_Latin1_General_CP1_CS_AS NULL
);






GO
CREATE NONCLUSTERED INDEX [NCIX_TopdeskProbleem]
    ON [TOPdesk].[probleem]([AuditDWKey] ASC, [naam] ASC) WITH (FILLFACTOR = 90);

