CREATE TABLE [Lift313].[activiteitgroep_voordracht] (
    [unid]              UNIQUEIDENTIFIER NULL,
    [dataanmk]          DATETIME         NULL,
    [datwijzig]         DATETIME         NULL,
    [uidaanmk]          UNIQUEIDENTIFIER NULL,
    [uidwijzig]         UNIQUEIDENTIFIER NULL,
    [status]            INT              NULL,
    [projectid]         UNIQUEIDENTIFIER NULL,
    [aanvraagid]        UNIQUEIDENTIFIER NULL,
    [uurprijs]          MONEY            NULL,
    [utv]               NVARCHAR (1)     NULL,
    [nultarief]         BIT              NULL,
    [btwid]             UNIQUEIDENTIFIER NULL,
    [intern]            BIT              NULL,
    [productid]         UNIQUEIDENTIFIER NULL,
    [grootboekid]       UNIQUEIDENTIFIER NULL,
    [datacceptatie]     DATETIME         NULL,
    [toeslag]           MONEY            NULL,
    [activiteitgroepid] UNIQUEIDENTIFIER NULL,
    [employeetypeid]    UNIQUEIDENTIFIER NULL,
    [budget_uren]       INT              NULL,
    [totale_werklast]   INT              NULL,
    [startdatum_groep]  DATETIME         NULL,
    [sdv_groep]         NVARCHAR (1)     NULL,
    [einddatum_groep]   DATETIME         NULL,
    [edv_groep]         NVARCHAR (1)     NULL,
    [AuditDWKey]    INT              NULL
);

