CREATE TABLE [Lift313].[artikel] (
    [unid]              UNIQUEIDENTIFIER NULL,
    [dataanmk]          DATETIME         NULL,
    [datwijzig]         DATETIME         NULL,
    [uidaanmk]          UNIQUEIDENTIFIER NULL,
    [uidwijzig]         UNIQUEIDENTIFIER NULL,
    [status]            INT              NULL,
    [archiefid]         UNIQUEIDENTIFIER NULL,
    [archiefdatum]      DATETIME         NULL,
    [artikelnr]         NVARCHAR (20)    NULL,
    [naam]              NVARCHAR (45)    NULL,
    [adviesprijs]       MONEY            NULL,
    [omschrijving]      NVARCHAR (MAX)   NULL,
    [btwid]             UNIQUEIDENTIFIER NULL,
    [productgroepid]    UNIQUEIDENTIFIER NULL,
    [productid]         UNIQUEIDENTIFIER NULL,
    [inkoopprijs]       MONEY            NULL,
    [minvoorraad]       INT              NULL,
    [minbestelling]     INT              NULL,
    [levertijd]         INT              NULL,
    [levertijdid]       UNIQUEIDENTIFIER NULL,
    [leverancierid]     UNIQUEIDENTIFIER NULL,
    [extraopz1]         UNIQUEIDENTIFIER NULL,
    [extraopz2]         UNIQUEIDENTIFIER NULL,
    [extraopz3]         UNIQUEIDENTIFIER NULL,
    [extraopz4]         UNIQUEIDENTIFIER NULL,
    [extraopz5]         UNIQUEIDENTIFIER NULL,
    [extraopz6]         UNIQUEIDENTIFIER NULL,
    [extramemo]         NVARCHAR (MAX)   NULL,
    [extravrij4]        NVARCHAR (40)    NULL,
    [extravrij3]        NVARCHAR (40)    NULL,
    [extravrij2]        NVARCHAR (40)    NULL,
    [extravrij1]        NVARCHAR (40)    NULL,
    [recurring_invoice] INT              NULL,
    [AuditDWKey]    INT              NULL
);

