CREATE TABLE [Lift313].[email_template] (
    [unid]           UNIQUEIDENTIFIER NULL,
    [dataanmk]       DATETIME         NULL,
    [datwijzig]      DATETIME         NULL,
    [uidaanmk]       UNIQUEIDENTIFIER NULL,
    [uidwijzig]      UNIQUEIDENTIFIER NULL,
    [status]         INT              NULL,
    [name]           NVARCHAR (250)   NULL,
    [subject]        NVARCHAR (250)   NULL,
    [header_from]    NVARCHAR (MAX)   NULL,
    [header_to]      NVARCHAR (MAX)   NULL,
    [header_cc]      NVARCHAR (MAX)   NULL,
    [header_bcc]     NVARCHAR (MAX)   NULL,
    [body]           NVARCHAR (MAX)   NULL,
    [cardcode]       INT              NULL,
    [cardstate]      INT              NULL,
    [mailbehavior]   INT              NULL,
    [allow_import]   BIT              NULL,
    [allow_send]     BIT              NULL,
    [save_instances] BIT              NULL,
    [font_family]    NVARCHAR (50)    NULL,
    [font_size]      NVARCHAR (5)     NULL,
    [locale]         NVARCHAR (10)    NULL,
    [AuditDWKey]     INT              NULL
);

