CREATE TABLE [Lift313].[inkoopverplichting] (
    [unid]                UNIQUEIDENTIFIER NULL,
    [dataanmk]            DATETIME         NULL,
    [datwijzig]           DATETIME         NULL,
    [uidaanmk]            UNIQUEIDENTIFIER NULL,
    [uidwijzig]           UNIQUEIDENTIFIER NULL,
    [status]              INT              NULL,
    [archiefid]           UNIQUEIDENTIFIER NULL,
    [archiefdatum]        DATETIME         NULL,
    [facturabel]          BIT              NULL,
    [factuurdatum]        DATETIME         NULL,
    [fprijs]              MONEY            NULL,
    [faantal]             INT              NULL,
    [grootboekid]         UNIQUEIDENTIFIER NULL,
    [btwid]               UNIQUEIDENTIFIER NULL,
    [projectid]           UNIQUEIDENTIFIER NULL,
    [naam]                NVARCHAR (60)    NULL,
    [zit_in_projectprijs] BIT              NULL,
    [kostprijs]           MONEY            NULL,
    [verkoopprijs]        MONEY            NULL,
    [inknr]               NVARCHAR (9)     NULL,
    [inkoopid]            UNIQUEIDENTIFIER NULL,
    [budget_lineid]       UNIQUEIDENTIFIER NULL,
    [amount]              MONEY            NULL,
    [AuditDWKey]      INT              NULL
);

