CREATE TABLE [Lift313].[invoice] (
    [unid]                      UNIQUEIDENTIFIER NULL,
    [dataanmk]                  DATETIME         NULL,
    [datwijzig]                 DATETIME         NULL,
    [uidaanmk]                  UNIQUEIDENTIFIER NULL,
    [uidwijzig]                 UNIQUEIDENTIFIER NULL,
    [companyid]                 UNIQUEIDENTIFIER NULL,
    [motherprojectid]           UNIQUEIDENTIFIER NULL,
    [debtorid]                  UNIQUEIDENTIFIER NULL,
    [contactpersonid]           UNIQUEIDENTIFIER NULL,
    [start_span]                DATETIME         NULL,
    [end_span]                  DATETIME         NULL,
    [document_date]             DATETIME         NULL,
    [price_ex_vat]              MONEY            NULL,
    [span_type]                 INT              NULL,
    [span_amount]               INT              NULL,
    [span_description]          INT              NULL,
    [hour_table_grouping]       INT              NULL,
    [group_by_week]             BIT              NULL,
    [use_email]                 BIT              NULL,
    [invoicenr]                 NVARCHAR (20)    NULL,
    [corrected_invoiceid]       UNIQUEIDENTIFIER NULL,
    [specify_per_child_project] BIT              NULL,
    [payment_conditionid]       UNIQUEIDENTIFIER NULL,
    [free_invoiceid]            UNIQUEIDENTIFIER NULL,
    [nr_of_intervals]           INT              NULL,
    [show_hourtypename]         BIT              NULL,
    [vat_price]                 MONEY            NULL,
    [AuditDWKey]            INT              NULL
);

