CREATE TABLE [Lift313].[orcp] (
    [unid]             UNIQUEIDENTIFIER NULL,
    [dataanmk]         DATETIME         NULL,
    [datwijzig]        DATETIME         NULL,
    [uidaanmk]         UNIQUEIDENTIFIER NULL,
    [uidwijzig]        UNIQUEIDENTIFIER NULL,
    [orid]             UNIQUEIDENTIFIER NULL,
    [status]           INT              NULL,
    [attentieid]       UNIQUEIDENTIFIER NULL,
    [attentiemelding]  NVARCHAR (200)   NULL,
    [bedrijfarchief]   BIT              NULL,
    [voertaalid]       UNIQUEIDENTIFIER NULL,
    [functie]          NVARCHAR (50)    NULL,
    [spec2]            NVARCHAR (50)    NULL,
    [verantwoordingid] UNIQUEIDENTIFIER NULL,
    [vrijvelda]        UNIQUEIDENTIFIER NULL,
    [vrijveldb]        NVARCHAR (40)    NULL,
    [vrijveldc]        NVARCHAR (40)    NULL,
    [vrijveldd]        NVARCHAR (40)    NULL,
    [vrijvelde]        NVARCHAR (40)    NULL,
    [datexport]        DATETIME         NULL,
    [aantekening]      NVARCHAR (MAX)   NULL,
    [memop]            NVARCHAR (MAX)   NULL,
    [personid]         UNIQUEIDENTIFIER NULL,
    [land1pid]         UNIQUEIDENTIFIER NULL,
    [extraopz1]        UNIQUEIDENTIFIER NULL,
    [extraopz2]        UNIQUEIDENTIFIER NULL,
    [extraopz3]        UNIQUEIDENTIFIER NULL,
    [extraopz4]        UNIQUEIDENTIFIER NULL,
    [extramemo]        NVARCHAR (MAX)   NULL,
    [extravrij4]       NVARCHAR (40)    NULL,
    [extravrij3]       NVARCHAR (40)    NULL,
    [extravrij2]       NVARCHAR (40)    NULL,
    [extravrij1]       NVARCHAR (40)    NULL,
    [AuditDWKey]   INT              NULL
);

