CREATE TABLE [Lift313].[projectlead] (
    [unid]               UNIQUEIDENTIFIER NULL,
    [dataanmk]           DATETIME         NULL,
    [datwijzig]          DATETIME         NULL,
    [uidaanmk]           UNIQUEIDENTIFIER NULL,
    [uidwijzig]          UNIQUEIDENTIFIER NULL,
    [status]             INT              NULL,
    [attentieid]         UNIQUEIDENTIFIER NULL,
    [attentiemelding]    NVARCHAR (200)   NULL,
    [leadnumber]         NVARCHAR (20)    NULL,
    [leadname]           NVARCHAR (70)    NULL,
    [vestigingid]        UNIQUEIDENTIFIER NULL,
    [behandeldid]        UNIQUEIDENTIFIER NULL,
    [projecttype]        INT              NULL,
    [bewaakdatum]        DATETIME         NULL,
    [klantid]            UNIQUEIDENTIFIER NULL,
    [notes]              NVARCHAR (MAX)   NULL,
    [contactpersoonid]   UNIQUEIDENTIFIER NULL,
    [acquisition_goalid] UNIQUEIDENTIFIER NULL,
    [productgroepid]     UNIQUEIDENTIFIER NULL,
    [productid]          UNIQUEIDENTIFIER NULL,
    [sales_target]       MONEY            NULL,
    [informerid]         UNIQUEIDENTIFIER NULL,
    [informername]       NVARCHAR (60)    NULL,
    [archiefid]          UNIQUEIDENTIFIER NULL,
    [archiefdatum]       DATETIME         NULL,
    [AuditDWKey]     INT              NULL
);

