CREATE TABLE [Lift313].[werknemer] (
    [km_submitdate]               DATETIME         NULL,
    [anaam]                       NVARCHAR (30)    NULL,
    [email]                       NVARCHAR (75)    NULL,
    [plaats1]                     NVARCHAR (30)    NULL,
    [postcode1]                   NVARCHAR (15)    NULL,
    [rnaam]                       NVARCHAR (20)    NULL,
    [tel1]                        NVARCHAR (25)    NULL,
    [tussen]                      NVARCHAR (10)    NULL,
    [vnaam]                       NVARCHAR (50)    NULL,
    [unid]                        UNIQUEIDENTIFIER NULL,
    [dataanmk]                    DATETIME         NULL,
    [datwijzig]                   DATETIME         NULL,
    [uidaanmk]                    UNIQUEIDENTIFIER NULL,
    [uidwijzig]                   UNIQUEIDENTIFIER NULL,
    [status]                      INT              NULL,
    [archiefid]                   UNIQUEIDENTIFIER NULL,
    [archiefdatum]                DATETIME         NULL,
    [inits]                       NVARCHAR (10)    NULL,
    [titel]                       NVARCHAR (15)    NULL,
    [datexport]                   DATETIME         NULL,
    [geslacht]                    INT              NULL,
    [geboren]                     DATETIME         NULL,
    [sollicitatie_aanleidingid]   UNIQUEIDENTIFIER NULL,
    [gesolliciteerd_op_functieid] UNIQUEIDENTIFIER NULL,
    [geblandid]                   UNIQUEIDENTIFIER NULL,
    [nationaliteitid]             UNIQUEIDENTIFIER NULL,
    [opleidingid]                 UNIQUEIDENTIFIER NULL,
    [richtingid]                  UNIQUEIDENTIFIER NULL,
    [rijbewijs]                   BIT              NULL,
    [auto]                        BIT              NULL,
    [ovid]                        UNIQUEIDENTIFIER NULL,
    [cvref]                       NVARCHAR (10)    NULL,
    [persnr]                      NVARCHAR (6)     NULL,
    [pmwnr]                       NVARCHAR (6)     NULL,
    [belastinggroep]              INT              NULL,
    [uurtarief]                   MONEY            NULL,
    [employeetypeid]              UNIQUEIDENTIFIER NULL,
    [inkoopprijs]                 MONEY            NULL,
    [reknr1]                      NVARCHAR (40)    NULL,
    [rektype1]                    INT              NULL,
    [studiestatusid]              UNIQUEIDENTIFIER NULL,
    [leefsituatieid]              UNIQUEIDENTIFIER NULL,
    [stdbeschikbaarheid]          INT              NULL,
    [invuldatum]                  DATETIME         NULL,
    [wn_invuldatum]               DATETIME         NULL,
    [leverancierid]               UNIQUEIDENTIFIER NULL,
    [vestigingid]                 UNIQUEIDENTIFIER NULL,
    [budgethouderid]              UNIQUEIDENTIFIER NULL,
    [datumindienst]               DATETIME         NULL,
    [hi_datumindienst]            BIT              NULL,
    [datumuitdienst]              DATETIME         NULL,
    [datpotwn]                    DATETIME         NULL,
    [datwn]                       DATETIME         NULL,
    [las_memo]                    NVARCHAR (MAX)   NULL,
    [attentieid]                  UNIQUEIDENTIFIER NULL,
    [attentiemelding]             NVARCHAR (200)   NULL,
    [urenmanagerid]               UNIQUEIDENTIFIER NULL,
    [boekhoud_url]                NVARCHAR (120)   NULL,
    [geocode_lat]                 FLOAT (53)       NULL,
    [geocode_lon]                 FLOAT (53)       NULL,
    [beschikbaar_vanaf]           DATETIME         NULL,
    [extraopz1]                   UNIQUEIDENTIFIER NULL,
    [extraopz2]                   UNIQUEIDENTIFIER NULL,
    [extraopz3]                   UNIQUEIDENTIFIER NULL,
    [extraopz4]                   UNIQUEIDENTIFIER NULL,
    [extraopz5]                   UNIQUEIDENTIFIER NULL,
    [extraopz6]                   UNIQUEIDENTIFIER NULL,
    [pmwopz3]                     UNIQUEIDENTIFIER NULL,
    [pmwopz4]                     UNIQUEIDENTIFIER NULL,
    [pmwopz5]                     UNIQUEIDENTIFIER NULL,
    [pmwvrij2]                    NVARCHAR (40)    NULL,
    [pmwopz6]                     UNIQUEIDENTIFIER NULL,
    [pmwvrij1]                    NVARCHAR (40)    NULL,
    [pmwvrij4]                    NVARCHAR (40)    NULL,
    [pmwvrij3]                    NVARCHAR (40)    NULL,
    [pmwvrij6]                    NVARCHAR (40)    NULL,
    [pmwopz1]                     UNIQUEIDENTIFIER NULL,
    [pmwopz2]                     UNIQUEIDENTIFIER NULL,
    [pmwvrij5]                    NVARCHAR (40)    NULL,
    [exveld003]                   UNIQUEIDENTIFIER NULL,
    [exveld002]                   UNIQUEIDENTIFIER NULL,
    [exveld005]                   UNIQUEIDENTIFIER NULL,
    [extra_team]                  UNIQUEIDENTIFIER NULL,
    [exveld004]                   UNIQUEIDENTIFIER NULL,
    [extravrij5]                  NVARCHAR (40)    NULL,
    [extravrij4]                  NVARCHAR (40)    NULL,
    [extravrij3]                  NVARCHAR (40)    NULL,
    [extravrij2]                  NVARCHAR (40)    NULL,
    [graduation_date]             DATETIME         NULL,
    [geocode_state]               INT              NULL,
    [extra_niveau]                UNIQUEIDENTIFIER NULL,
    [AuditDWKey]              INT              NULL
);

