CREATE TABLE [Fact].[Problem]
(
	[Problem_Id]                       INT             IDENTITY (1,1) NOT FOR REPLICATION,
	[SourceDatabaseKey]                INT             NOT NULL,
	[AuditDWKey]                       INT             NOT NULL,
	[CustomerKey]                      INT             NOT NULL,
	[OperatorGroupKey]                 INT             NOT NULL,
	[OperatorKey]                      INT             NOT NULL,
	[ChangeDate]                       DATE            NULL,
	[ChangeTime]                       TIME (0)        NULL,
	[KnownErrorDate]                   DATE            NULL,
	[KnownErrorTime]                   TIME (0)        NULL,
	[ProblemDate]                      DATE            NULL,
	[ProblemTime]                      TIME (0)        NULL,
	[CardCreatedBy]                    NVARCHAR (255)  NULL,
	[Closed]                           BIT             NULL,
	[ClosedKownError]                  BIT             NULL,
	[ClosedProblem]                    BIT             NULL,
	[EstimatedTimeSpent]               BIGINT          NULL,
	[EstimatedCosts]                   MONEY           NULL,
	[TimeSpent]                        BIGINT          NULL,
	[TimespentKnownError]              BIGINT          NULL,
	[TimespentProblem]                 BIGINT          NULL,
	[CategoryKnownError]               NVARCHAR (255)  NULL,
	[CategoryProblem]                  NVARCHAR (255)  NULL,
	[CreationDate]                     DATE            NULL,
	[CreationTime]                     TIME (0)        NULL,
	[ClosureDate]                      DATE            NULL,
	[ClosureTime]                      TIME (0)        NULL,
	[ClosureDateKnownError]            DATE            NULL,
	[ClosureTimeKnownError]            TIME (0)        NULL,
	[ClosureDateProblem]               DATE            NULL,
	[ClosureTimeProblem]               TIME (0)        NULL,
	[CompletionDate]                   DATE            NULL,
	[CompletionTime]                   TIME (0)        NULL,
	[CompletionDateKnownError]         DATE            NULL,
	[CompletionTimeKnownError]         TIME (0)        NULL,
	[CompletionDateProblem]            DATE            NULL,
	[CompletionTimeProblem]            TIME (0)        NULL,
	[DurationKnownError]               NVARCHAR (255)  NULL,
	[DurationProblem]                  NVARCHAR (255)  NULL,
	[ActualTimeSpent]                  BIGINT          NULL,
	[DurationActual]                   BIGINT          NULL,
	[DurationActualKnownError]         BIGINT          NULL,
	[DurationActualProblem]            BIGINT          NULL,
	[ActualCosts]                      MONEY           NULL,
	[Completed]                        BIT             NULL,
	[CompletedKnownError]              BIT             NULL,
	[CompletedProblem]                 BIT             NULL,
	[ImpactKnownError]                 NVARCHAR (255)  NULL,
	[Impact]                           NVARCHAR (255)  NULL,
	[Type]                             INT             NULL,
	[KnownErrorDescription]            NVARCHAR (255)  NULL,
	[ProblemDescription]               NVARCHAR (255)  NULL,
	[Manager]                          NVARCHAR (255)  NULL,
	[RemainingCosts]                   MONEY           NULL,
	[CostsKnownError]                  MONEY           NULL,
	[Costs]                            MONEY           NULL,
	[CostsProblem]                     MONEY           NULL,
	[ProblemCause]                     NVARCHAR (255)  NULL,
	[Priority]                         NVARCHAR (255)  NULL,
	[Problemnumber]                    NVARCHAR (255)  NULL,
	[ReasonArchiving]                  NVARCHAR (255)  NULL,
	[TimeRemaining]                    BIGINT          NULL,
	[ProblemType]                      NVARCHAR (255)  NULL,
	[Status]                           NVARCHAR (255)  NULL,
	[StatusProcessFeedback]            NVARCHAR (255)  NULL,
	[TargetDateKnownError]             DATE            NULL,
	[TargetTimeKnownError]             TIME (0)        NULL,
	[TargetDate]                       DATE            NULL,
	[TargetTime]                       TIME (0)        NULL,
	[SubcategoryKnownError]            NVARCHAR (255)  NULL,
	[SubcategoryProblem]               NVARCHAR (255)  NULL,
	[Urgency]                          NVARCHAR (255)  NULL,
	[CardChangedBy]                    NVARCHAR (255)  NULL,
	[IncidentsCnt]                     INT             NULL,
	[IncidentsFirstReportedDate]       DATE            NULL,
	[IncidentsFirstReportedTime]       TIME (0)        NULL,
	[IncidentsLastReportedDate]        DATE            NULL,
	[IncidentsLastReportedTime]        TIME (0)        NULL,
	[Incidents]                        NVARCHAR (4000) NULL,
	[CausedByChangesCnt]               INT             NULL,
	[CausedByChangesFirstExecutedDate] DATE            NULL,
	[CausedByChangesFirstExecutedTime] TIME (0)        NULL,
	[CausedByChangesLastExecutedDate]  DATE            NULL,
	[CausedByChangesLastExecutedTime]  TIME (0)        NULL,
	[CausedByChanges]                  NVARCHAR (1024) NULL,
	[FixedByChangesCnt]                INT             NULL,
	[FixedByChangesFirstExecutedDate]  DATE            NULL,
	[FixedByChangesFirstExecutedTime]  TIME (0)        NULL,
	[FixedByChangesLastExecutedDate]   DATE            NULL,
	[FixedByChangesLastExecutedTime]   TIME (0)        NULL,
	[FixedByChanges]                   NVARCHAR (1024) NULL,
	[ObjectsImpactedCnt]               INT             NULL,
	[ObjectsImpacted]                  NVARCHAR (1024) NULL,
	[AgeDays]                          AS              CONVERT(smallint, DATEDIFF(DAY, CreationDate, COALESCE(CompletionDate, GETUTCDATE()))), 
	[AgeWorkDays]                      AS              CONVERT(smallint, CASE WHEN CreationDate = COALESCE(CompletionDate, GETUTCDATE()) THEN 0 WHEN CreationDate > COALESCE(CompletionDate, GETUTCDATE()) THEN NULL ELSE (DATEDIFF(DD, CreationDate, COALESCE(CompletionDate, GETUTCDATE()))) - (DATEDIFF(WW, CreationDate, COALESCE(CompletionDate, GETUTCDATE())) * 2) + (CASE WHEN DATENAME(DW, CreationDate) = 'Saturday' THEN 1 ELSE 0 END) - (CASE WHEN DATENAME(DW, COALESCE(CompletionDate, GETUTCDATE())) = 'Saturday' THEN 1 ELSE 0 END) END),
	[MonthDiffCompletedToToday]        AS              CONVERT(smallint, DATEDIFF(MM, CompletionDate, GETUTCDATE())),
	[MonthDiffClosureToToday]          AS              CONVERT(smallint, DATEDIFF(MM, ClosureDate, GETUTCDATE())),
	CONSTRAINT [PK_Problem] PRIMARY KEY CLUSTERED ([Problem_Id] ASC),
	CONSTRAINT [FK_Problem_CustomerKey] FOREIGN KEY ([CustomerKey]) REFERENCES [Dim].[Customer] ([CustomerKey]),
	CONSTRAINT [FK_Problem_OperatorGroupKey] FOREIGN KEY ([OperatorGroupKey]) REFERENCES [Dim].[OperatorGroup] ([OperatorGroupKey]),
	CONSTRAINT [FK_Problem_OperatorKey] FOREIGN KEY ([OperatorKey]) REFERENCES [Dim].[Caller] ([CallerKey]) 
)
GO

CREATE NONCLUSTERED INDEX [IX_Problem_CustomerKey]
	ON [Fact].[Problem] ([CustomerKey] ASC)
GO

CREATE NONCLUSTERED INDEX [IX_Problem_OperatorKey]
	ON [Fact].[Problem] ([OperatorKey] ASC)
GO

CREATE NONCLUSTERED INDEX [IX_Problem_OperatorGroupKey]
	ON [Fact].[Problem] ([OperatorKey] ASC)
GO