CREATE TABLE [Fact].[LeerlingBevordering] (
    [LeerlingId]            INT          NOT NULL,
    [KostenplaatsKey]       INT          NOT NULL,
    [InschrijfDatum]        DATE         NOT NULL,
    [Uitschrijfdatum]       DATE         NOT NULL,
    [VertrekDatum]          DATE         NOT NULL,
    [IsInstromerExtern]     BIT          NOT NULL,
    [IsUitstromerExtern]    BIT          NOT NULL,
    [IsLWOOindicatie]       BIT          NOT NULL,
    [IsPROindicatie]        BIT          NOT NULL,
    [IsZittenblijver]       BIT          NOT NULL,
    [Vertrekreden]          VARCHAR (40) NOT NULL,
    [IsVSV]                 BIT          NOT NULL,
    [Klas]                  VARCHAR (20) NOT NULL,
    [Leerjaar]              INT          NOT NULL,
    [Studie]                VARCHAR (20) NOT NULL,
    [Bevorderingsresultaat] VARCHAR (20) NOT NULL,
    [IsBevorderd]           BIT          NOT NULL,
    [Meetellen]             BIT          NOT NULL,
    [TypeVorigeSchool]      VARCHAR (40) NOT NULL,
    [TypeBasisSchool]       VARCHAR (40) NOT NULL,
    [TypeVervolgSchool]     VARCHAR (40) NOT NULL,
    [ILTcode]               INT          NOT NULL,
	[JaarInschrijvingKey]	INT			 NULL,
	[Leerjaargroep]			CHAR(5)		 NULL,
	[VSO_type]				CHAR(15)	 NULL,
	CONSTRAINT [FK_LeerlingBevordering_KostenplaatsKey] FOREIGN KEY ([KostenplaatsKey]) REFERENCES [Dim].[Kostenplaats]([KostenplaatsKey]),
	CONSTRAINT [FK_LeerlingBevordering_JaarInschrijvingKey] FOREIGN KEY ([JaarInschrijvingKey]) REFERENCES [Dim].[Jaar]([JaarKey]),
);

