CREATE TABLE [Fact].[Salarissen]
(
	[FunctieKey]               INT            NOT NULL,
	[DienstverbandKey]         INT            NOT NULL,
	[MedewerkerKey]            INT            NOT NULL,
	[KostenplaatsKey]          INT            NOT NULL,
	[KostendragerKey]          INT            NOT NULL,
	[Volgnummer_contract]      INT            NOT NULL,
	[Schaal_code]              NVARCHAR (32)  NULL,
	[Schaal]                   NVARCHAR (32)  NULL,
	[Parttime_percentage]      DECIMAL (5,2)  NOT NULL,
	[Werkgever]                NVARCHAR (32)  NOT NULL,
	[Medewerker]               INT            NOT NULL,
	[Cao]                      NVARCHAR (32)  NOT NULL,
	[Begindatum_salaris]       DATE           NULL,
	[Einddatum_salaris]        DATE           NULL,
	[Volgnummer_dienstverband] INT            NOT NULL,
	[Trede]                    INT            NULL,
	[Dienstverband]            INT            NOT NULL,
	[Salaris]                  DECIMAL (14,4) NULL,
	[Caotype]                  NVARCHAR (32)  NULL,
	[Omschrijving]             NVARCHAR (32)  NULL,
	[Soort_onderwijs_code]     NVARCHAR (32)  NULL,
	[Soort_onderwijs]          NVARCHAR (32)  NULL,
	[Bovenschoolse_functie]    INT            NULL,
	[Meenemen_in_GGL_PO]       INT            NULL,
	CONSTRAINT [FK_Salarissen_FunctieKey] FOREIGN KEY ([FunctieKey]) REFERENCES [Dim].[Functie]([FunctieKey]),
	CONSTRAINT [FK_Salarissen_DienstverbandKey] FOREIGN KEY ([DienstverbandKey]) REFERENCES [Dim].[Dienstverband]([DienstverbandKey]),
	CONSTRAINT [FK_Salarissen_MedewerkerKey] FOREIGN KEY ([MedewerkerKey]) REFERENCES [Dim].[Medewerker]([MedewerkerKey]),
	CONSTRAINT [FK_Salarissen_Kostenplaats] FOREIGN KEY ([KostenplaatsKey]) REFERENCES [Dim].[Kostenplaats]([KostenplaatsKey]),
	CONSTRAINT [FK_Salarissen_Kostendrager] FOREIGN KEY ([KostendragerKey]) REFERENCES [Dim].[Kostendrager]([KostendragerKey]),
)