CREATE TABLE [temp].[Changes_Change] (
    [AuthorizationDate]            DATETIME       NULL,
    [CancelDateExtChange]          DATETIME       NULL,
    [CancelledByManager]           NVARCHAR (255) NULL,
    [CancelledByOperator]          NVARCHAR (255) NULL,
    [CardChangedBy]                NVARCHAR (255) NULL,
    [CardCreatedBy]                NVARCHAR (255) NULL,
    [Category]                     NVARCHAR (255) NULL,
    [ChangeDate]                   DATETIME       NULL,
    [ChangeNumber]                 NVARCHAR (255) NOT NULL,
    [ChangeTypeID]                 INT            NOT NULL,
    [Closed]                       BIT            NOT NULL,
    [ClosureDateSimpleChange]      DATETIME       NULL,
    [Coordinator]                  NVARCHAR (255) NULL,
    [CreationDate]                 DATETIME       NULL,
    [CurrentPhaseID]               INT            NOT NULL,
    [CustomerName]                 NVARCHAR (255) NULL,
    [DateCalcTypeEvaluationID]     INT            NOT NULL,
    [DateCalcTypeProgressID]       INT            NOT NULL,
    [DateCalcTypeRequestChangeID]  INT            NOT NULL,
    [DescriptionBrief]             NVARCHAR (255) NOT NULL,
    [EndDateExtChange]             DATETIME       NULL,
    [Evaluation]                   BIT            NOT NULL,
    [ExternalNumber]               NVARCHAR (255) NOT NULL,
    [Impact]                       NVARCHAR (255) NULL,
    [ImplDateExtChange]            DATETIME       NULL,
    [ImplDateSimpleChange]         DATETIME       NULL,
    [Implemented]                  BIT            NOT NULL,
    [NoGoDateExtChange]            DATETIME       NULL,
    [ObjectID]                     NVARCHAR (255) NULL,
    [OriginalIncident]             NVARCHAR (255) NULL,
    [PlannedAuthDateRequestChange] DATETIME       NULL,
    [PlannedFinalDate]             DATETIME       NULL,
    [PlannedImplDate]              DATETIME       NULL,
    [PlannedStartDateSimpleChange] DATETIME       NULL,
    [Priority]                     NVARCHAR (255) NULL,
    [Rejected]                     BIT            NOT NULL,
    [RejectionDate]                DATETIME       NULL,
    [RequestDate]                  DATETIME       NULL,
    [StartDateSimpleChange]        DATETIME       NULL,
    [Started]                      BIT            NOT NULL,
    [Status]                       NVARCHAR (255) NULL,
    [Subcategory]                  NVARCHAR (255) NULL,
    [SubmissionDateRequestChange]  DATETIME       NULL,
    [Template]                     NVARCHAR (255) NULL,
    [TimeSpent]                    BIGINT         NOT NULL,
    [Type]                         NVARCHAR (255) NULL,
    [Urgency]                      BIT            NOT NULL,
    [OperatorGroup]                NVARCHAR (255) NULL,
    [CallerName]                   NVARCHAR (255) NOT NULL,
    [SourceDatabaseKey]            INT            NOT NULL,
    [ChangedAt]                    DATETIME       NULL,
    [CH_ID]                        INT            NULL,
    [T2_Known]                     BIT            NOT NULL,
    [T2_keyNumber]                 BIGINT         NULL,
    [T2_RN]                        INT            NULL,
    [T2_RNdesc]                    INT            NULL,
    [AuditDWKey]                   INT            NOT NULL
);



