CREATE TABLE [temp].[ChangeActivities_ChangeActivity] (
    [ActivityChange]         NVARCHAR (255) NULL,
    [ActivityNumber]         NVARCHAR (255) NOT NULL,
    [ActivityTemplate]       NVARCHAR (255) NULL,
    [Approved]               BIT            NOT NULL,
    [ApprovedDate]           DATETIME       NULL,
    [BriefDescription]       NVARCHAR (255) NOT NULL,
    [CardChangedBy]          NVARCHAR (255) NULL,
    [CardCreatedBy]          NVARCHAR (255) NULL,
    [Category]               NVARCHAR (255) NULL,
    [ChangeBriefDescription] NVARCHAR (255) NOT NULL,
    [ChangeDate]             DATETIME       NULL,
    [ChangePhase]            INT            NOT NULL,
    [CreationDate]           DATETIME       NULL,
    [CurrentPlanTimeTaken]   BIGINT         NOT NULL,
    [MayStart]               BIT            NOT NULL,
    [OriginalPlanTimeTaken]  BIGINT         NOT NULL,
    [PlannedFinalDate]       DATETIME       NULL,
    [PlannedStartDate]       DATETIME       NULL,
    [Rejected]               BIT            NOT NULL,
    [RejectedDate]           DATETIME       NULL,
    [Resolved]               BIT            NOT NULL,
    [ResolvedDate]           DATETIME       NULL,
    [Skipped]                BIT            NOT NULL,
    [SkippedDate]            DATETIME       NULL,
    [Started]                BIT            NOT NULL,
    [StartedDate]            DATETIME       NULL,
    [Status]                 NVARCHAR (255) NULL,
    [Subcategory]            NVARCHAR (255) NULL,
    [TimeTaken]              BIGINT         NOT NULL,
    [OperatorGroup]          NVARCHAR (255) NULL,
    [OperatorName]           NVARCHAR (255) NULL,
    [SourceDatabaseKey]      INT            NOT NULL,
    [ChangedAt]              DATETIME       NULL,
    [AC_ID]                  INT            NULL,
    [T2_Known]               BIT            NOT NULL,
    [T2_keyNumber]           BIGINT         NULL,
    [T2_RN]                  INT            NULL,
    [T2_RNdesc]              INT            NULL,
    [AuditDWKey]             INT            NOT NULL
);

