CREATE TABLE [temp].[Incidents_Incident] (
    [CardChangedBy]       NVARCHAR (255) NULL,
    [CardCreatedBy]       NVARCHAR (255) NULL,
    [Category]            NVARCHAR (255) NOT NULL,
    [ChangeDate]          DATETIME       NULL,
    [Closed]              BIT            NOT NULL,
    [ClosureDate]         DATETIME       NULL,
    [Completed]           BIT            NOT NULL,
    [CompletionDate]      DATETIME       NULL,
    [ConfigurationID]     NVARCHAR (255) NULL,
    [CreationDate]        DATETIME       NULL,
    [CustomerName]        NVARCHAR (255) NULL,
    [Duration]            NVARCHAR (255) NULL,
    [DurationActual]      BIGINT         NOT NULL,
    [DurationAdjusted]    BIGINT         NOT NULL,
    [DurationOnHold]      BIGINT         NOT NULL,
    [EntryType]           NVARCHAR (255) NULL,
    [ExternalNumber]      NVARCHAR (255) NOT NULL,
    [Impact]              NVARCHAR (255) NOT NULL,
    [IncidentDate]        DATETIME       NULL,
    [IncidentDescription] NVARCHAR (255) NOT NULL,
    [IncidentNumber]      NVARCHAR (255) NOT NULL,
    [IncidentType]        NVARCHAR (255) NOT NULL,
    [IsMajorIncident]     BIT            NOT NULL,
    [LineID]              INT            NOT NULL,
    [MajorIncident]       NVARCHAR (255) NULL,
    [ObjectID]            NVARCHAR (255) NULL,
    [Onhold]              BIT            NOT NULL,
    [OnHoldDate]          DATETIME       NULL,
    [Priority]            NVARCHAR (255) NULL,
    [ServiceWindow]       NVARCHAR (255) NULL,
    [Sla]                 NVARCHAR (255) NULL,
    [SlaAchievedID]       INT            NOT NULL,
    [SlaContract]         NVARCHAR (255) NULL,
    [SlaTargetDate]       DATETIME       NULL,
    [StandardSolution]    NVARCHAR (255) NULL,
    [Status]              NVARCHAR (255) NULL,
    [Subcategory]         NVARCHAR (255) NOT NULL,
    [Supplier]            NVARCHAR (255) NULL,
    [TargetDate]          DATETIME       NULL,
    [TimeSpentFirstLine]  BIGINT         NOT NULL,
    [TimeSpentSecondLine] BIGINT         NOT NULL,
    [TotalTime]           BIGINT         NOT NULL,
    [OperatorGroup]       NVARCHAR (255) NOT NULL,
    [OperatorName]        NVARCHAR (255) NOT NULL,
    [CallerName]          NVARCHAR (255) NOT NULL,
    [SourceDatabaseKey]   INT            NOT NULL,
    [ChangedAt]           DATETIME       NULL,
    [IN_ID]               INT            NULL,
    [T2_Known]            BIT            NOT NULL,
    [T2_keyNumber]        BIGINT         NULL,
    [T2_RN]               INT            NULL,
    [T2_RNdesc]           INT            NULL,
    [AuditDWKey]          INT            NOT NULL
);



