CREATE TABLE [temp].[Objects_Object] (
    [Attention]           NVARCHAR (255) NULL,
    [Branch]              NVARCHAR (255) NULL,
    [Budgetholder]        NVARCHAR (255) NULL,
    [ChangeDate]          DATETIME       NULL,
    [City]                NVARCHAR (255) NULL,
    [Class]               NVARCHAR (255) NULL,
    [Comments]            NVARCHAR (255) NULL,
    [Configuration]       NVARCHAR (255) NULL,
    [Contact]             NVARCHAR (255) NULL,
    [Group]               NVARCHAR (255) NULL,
    [Hostname]            NVARCHAR (255) NULL,
    [IPAddress]           NVARCHAR (255) NULL,
    [LeaseContractNumber] NVARCHAR (255) NULL,
    [LeaseEndDate]        DATETIME       NULL,
    [LeasePeriod]         INT            NULL,
    [LeasePrice]          MONEY          NULL,
    [LeaseStartDate]      DATETIME       NULL,
    [Model]               NVARCHAR (255) NULL,
    [ObjectID]            NVARCHAR (255) NULL,
    [ObjectType]          NVARCHAR (255) NULL,
    [OrderNumber]         NVARCHAR (255) NULL,
    [Person]              NVARCHAR (255) NULL,
    [PurchaseDate]        DATETIME       NULL,
    [PurchasePrice]       MONEY          NULL,
    [ResidualValue]       MONEY          NULL,
    [Room]                NVARCHAR (255) NULL,
    [SerialNumber]        NVARCHAR (255) NULL,
    [Specification]       NVARCHAR (255) NULL,
    [Staffgroup]          NVARCHAR (255) NULL,
    [Status]              NVARCHAR (255) NULL,
    [Supplier]            NVARCHAR (255) NULL,
    [User]                NVARCHAR (255) NULL,
    [SourceDatabaseKey]   INT            NOT NULL,
    [ChangedAt]           DATETIME       NULL,
    [OB_ID]               INT            NULL,
    [T2_Known]            BIT            NOT NULL,
    [T2_keyNumber]        BIGINT         NULL,
    [T2_RN]               INT            NULL,
    [T2_RNdesc]           INT            NULL,
    [AuditDWKey]          INT            NOT NULL
);

