CREATE TABLE [temp].[Problems_Problem] (
    [ActualCosts]              MONEY          NOT NULL,
    [ActualTimeSpent]          BIGINT         NOT NULL,
    [CardChangedBy]            NVARCHAR (255) NULL,
    [CardCreatedBy]            NVARCHAR (255) NULL,
    [CategoryKnownError]       NVARCHAR (255) NOT NULL,
    [CategoryProblem]          NVARCHAR (255) NOT NULL,
    [ChangeDate]               DATETIME       NULL,
    [Closed]                   BIT            NOT NULL,
    [ClosedKownError]          BIT            NOT NULL,
    [ClosedProblem]            BIT            NOT NULL,
    [ClosureDate]              DATETIME       NULL,
    [ClosureDateKnownError]    DATETIME       NULL,
    [ClosureDateProblem]       DATETIME       NULL,
    [Completed]                BIT            NOT NULL,
    [CompletedKnownError]      BIT            NOT NULL,
    [CompletedProblem]         BIT            NOT NULL,
    [CompletionDate]           DATETIME       NULL,
    [CompletionDateKnownError] DATETIME       NULL,
    [CompletionDateProblem]    DATETIME       NULL,
    [Costs]                    MONEY          NOT NULL,
    [CostsKnownError]          MONEY          NOT NULL,
    [CostsProblem]             MONEY          NOT NULL,
    [CreationDate]             DATETIME       NULL,
    [DurationActual]           BIGINT         NOT NULL,
    [DurationActualKnownError] BIGINT         NOT NULL,
    [DurationActualProblem]    BIGINT         NOT NULL,
    [DurationKnownError]       NVARCHAR (255) NULL,
    [DurationProblem]          NVARCHAR (255) NULL,
    [EstimatedCosts]           MONEY          NOT NULL,
    [EstimatedTimeSpent]       BIGINT         NOT NULL,
    [Impact]                   NVARCHAR (255) NULL,
    [ImpactKnownError]         NVARCHAR (255) NULL,
    [KnownErrorDate]           DATETIME       NULL,
    [KnownErrorDescription]    NVARCHAR (255) NOT NULL,
    [Manager]                  NVARCHAR (255) NOT NULL,
    [Priority]                 NVARCHAR (255) NULL,
    [ProblemCause]             NVARCHAR (255) NULL,
    [ProblemDate]              DATETIME       NULL,
    [ProblemDescription]       NVARCHAR (255) NOT NULL,
    [Problemnumber]            NVARCHAR (255) NOT NULL,
    [ProblemType]              NVARCHAR (255) NULL,
    [ReasonArchiving]          NVARCHAR (255) NULL,
    [RemainingCosts]           MONEY          NOT NULL,
    [Status]                   NVARCHAR (255) NULL,
    [StatusProcessFeedback]    NVARCHAR (255) NULL,
    [SubcategoryKnownError]    NVARCHAR (255) NOT NULL,
    [SubcategoryProblem]       NVARCHAR (255) NOT NULL,
    [TargetDate]               DATETIME       NULL,
    [TargetDateKnownError]     DATETIME       NULL,
    [TimeRemaining]            BIGINT         NOT NULL,
    [TimeSpent]                BIGINT         NOT NULL,
    [TimespentKnownError]      BIGINT         NOT NULL,
    [TimespentProblem]         BIGINT         NOT NULL,
    [Type]                     INT            NOT NULL,
    [Urgency]                  NVARCHAR (255) NULL,
    [OperatorGroup]            NVARCHAR (255) NULL,
    [OperatorName]             NVARCHAR (255) NOT NULL,
    [SourceDatabaseKey]        INT            NOT NULL,
    [ChangedAt]                DATETIME       NULL,
    [PR_ID]                    INT            NULL,
    [T2_Known]                 BIT            NOT NULL,
    [T2_keyNumber]             BIGINT         NULL,
    [T2_RN]                    INT            NULL,
    [T2_RNdesc]                INT            NULL,
    [AuditDWKey]               INT            NOT NULL
);

