CREATE TABLE [dbo].[artikel] (
    [unid]              UNIQUEIDENTIFIER                                   NOT NULL,
    [dataanmk]          DATETIME                                           NULL,
    [datwijzig]         DATETIME                                           NULL,
    [uidaanmk]          UNIQUEIDENTIFIER                                   NULL,
    [uidwijzig]         UNIQUEIDENTIFIER                                   NULL,
    [status]            INT                                                NULL,
    [archiefid]         UNIQUEIDENTIFIER                                   NULL,
    [archiefdatum]      DATETIME                                           NULL,
    [artikelnr]         NVARCHAR (20)                                      NULL,
    [naam]              NVARCHAR (45)                                      NULL,
    [adviesprijs]       MONEY                                              NULL,
    [omschrijving]      NVARCHAR (MAX)                                     NULL,
    [btwid]             UNIQUEIDENTIFIER                                   NULL,
    [productgroepid]    UNIQUEIDENTIFIER                                   NULL,
    [productid]         UNIQUEIDENTIFIER                                   NULL,
    [inkoopprijs]       MONEY                                              NULL,
    [minvoorraad]       INT                                                NULL,
    [minbestelling]     INT                                                NULL,
    [levertijd]         INT                                                NULL,
    [levertijdid]       UNIQUEIDENTIFIER                                   NULL,
    [leverancierid]     UNIQUEIDENTIFIER                                   NULL,
    [extraopz1]         UNIQUEIDENTIFIER                                   NULL,
    [extraopz2]         UNIQUEIDENTIFIER                                   NULL,
    [extraopz3]         UNIQUEIDENTIFIER                                   NULL,
    [extraopz4]         UNIQUEIDENTIFIER                                   NULL,
    [extraopz5]         UNIQUEIDENTIFIER                                   NULL,
    [extraopz6]         UNIQUEIDENTIFIER                                   NULL,
    [extramemo]         NVARCHAR (MAX)                                     NULL,
    [extravrij4]        NVARCHAR (40)                                      NULL,
    [extravrij3]        NVARCHAR (40)                                      NULL,
    [extravrij2]        NVARCHAR (40)                                      NULL,
    [extravrij1]        NVARCHAR (40)                                      NULL,
    [recurring_invoice] INT                                                NULL,
    [AuditDWKey]    INT                                                NULL,
    [ValidFrom]         DATETIME2 (0) GENERATED ALWAYS AS ROW START HIDDEN CONSTRAINT [DF_dboartikelSysStart] DEFAULT (CONVERT([datetime2](0),'0000-01-01 00:00:00')) NOT NULL,
    [ValidTo]           DATETIME2 (0) GENERATED ALWAYS AS ROW END HIDDEN   CONSTRAINT [DF_dboartikelSysEnd] DEFAULT (CONVERT([datetime2](0),'9999-12-31 23:59:59')) NOT NULL,
    CONSTRAINT [pk_dboartikel ] PRIMARY KEY CLUSTERED ([unid] ASC) WITH (DATA_COMPRESSION = PAGE),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[History].[artikel], DATA_CONSISTENCY_CHECK=ON));

