CREATE TABLE [dbo].[factuur] (
    [unid]                 UNIQUEIDENTIFIER                                   NOT NULL,
    [dataanmk]             DATETIME                                           NULL,
    [datwijzig]            DATETIME                                           NULL,
    [uidaanmk]             UNIQUEIDENTIFIER                                   NULL,
    [uidwijzig]            UNIQUEIDENTIFIER                                   NULL,
    [factuurnr]            NVARCHAR (12)                                      NULL,
    [doccode]              NVARCHAR (12)                                      NULL,
    [documentid]           UNIQUEIDENTIFIER                                   NULL,
    [document]             NVARCHAR (MAX)                                     NULL,
    [projectid]            UNIQUEIDENTIFIER                                   NULL,
    [factuurdatum]         DATETIME                                           NULL,
    [bedrag]               MONEY                                              NULL,
    [samenvatting]         NVARCHAR (MAX)                                     NULL,
    [periodevan]           DATETIME                                           NULL,
    [periodetot]           DATETIME                                           NULL,
    [factuurtype]          INT                                                NULL,
    [fsoort]               INT                                                NULL,
    [verwerktexact]        INT                                                NULL,
    [verwerktfinancials]   INT                                                NULL,
    [verwerktafas]         INT                                                NULL,
    [verwerktcash]         INT                                                NULL,
    [verwerktcoda]         INT                                                NULL,
    [verwerktking]         INT                                                NULL,
    [andereklantid]        UNIQUEIDENTIFIER                                   NULL,
    [rappeldatum]          DATETIME                                           NULL,
    [notitie]              NVARCHAR (MAX)                                     NULL,
    [factuurbehandelaarid] UNIQUEIDENTIFIER                                   NULL,
    [behandelingstatusid]  UNIQUEIDENTIFIER                                   NULL,
    [AuditDWKey]       INT                                                NULL,
    [ValidFrom]            DATETIME2 (0) GENERATED ALWAYS AS ROW START HIDDEN CONSTRAINT [DF_dbofactuurSysStart] DEFAULT (CONVERT([datetime2](0),'0000-01-01 00:00:00')) NOT NULL,
    [ValidTo]              DATETIME2 (0) GENERATED ALWAYS AS ROW END HIDDEN   CONSTRAINT [DF_dbofactuurSysEnd] DEFAULT (CONVERT([datetime2](0),'9999-12-31 23:59:59')) NOT NULL,
    CONSTRAINT [pk_dbofactuur ] PRIMARY KEY CLUSTERED ([unid] ASC) WITH (DATA_COMPRESSION = PAGE),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[History].[factuur], DATA_CONSISTENCY_CHECK=ON));

