CREATE TABLE [dbo].[invoice] (
    [unid]                      UNIQUEIDENTIFIER                                   NOT NULL,
    [dataanmk]                  DATETIME                                           NULL,
    [datwijzig]                 DATETIME                                           NULL,
    [uidaanmk]                  UNIQUEIDENTIFIER                                   NULL,
    [uidwijzig]                 UNIQUEIDENTIFIER                                   NULL,
    [companyid]                 UNIQUEIDENTIFIER                                   NULL,
    [motherprojectid]           UNIQUEIDENTIFIER                                   NULL,
    [debtorid]                  UNIQUEIDENTIFIER                                   NULL,
    [contactpersonid]           UNIQUEIDENTIFIER                                   NULL,
    [start_span]                DATETIME                                           NULL,
    [end_span]                  DATETIME                                           NULL,
    [document_date]             DATETIME                                           NULL,
    [price_ex_vat]              MONEY                                              NULL,
    [span_type]                 INT                                                NULL,
    [span_amount]               INT                                                NULL,
    [span_description]          INT                                                NULL,
    [hour_table_grouping]       INT                                                NULL,
    [group_by_week]             BIT                                                NULL,
    [use_email]                 BIT                                                NULL,
    [invoicenr]                 NVARCHAR (20)                                      NULL,
    [corrected_invoiceid]       UNIQUEIDENTIFIER                                   NULL,
    [specify_per_child_project] BIT                                                NULL,
    [payment_conditionid]       UNIQUEIDENTIFIER                                   NULL,
    [free_invoiceid]            UNIQUEIDENTIFIER                                   NULL,
    [nr_of_intervals]           INT                                                NULL,
    [show_hourtypename]         BIT                                                NULL,
    [vat_price]                 MONEY                                              NULL,
    [AuditDWKey]            INT                                                NULL,
    [ValidFrom]                 DATETIME2 (0) GENERATED ALWAYS AS ROW START HIDDEN CONSTRAINT [DF_dboinvoiceSysStart] DEFAULT (CONVERT([datetime2](0),'0000-01-01 00:00:00')) NOT NULL,
    [ValidTo]                   DATETIME2 (0) GENERATED ALWAYS AS ROW END HIDDEN   CONSTRAINT [DF_dboinvoiceSysEnd] DEFAULT (CONVERT([datetime2](0),'9999-12-31 23:59:59')) NOT NULL,
    CONSTRAINT [pk_dboinvoice ] PRIMARY KEY CLUSTERED ([unid] ASC) WITH (DATA_COMPRESSION = PAGE),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[History].[invoice], DATA_CONSISTENCY_CHECK=ON));

