CREATE TABLE [dbo].[klant] (
    [unid]                                     UNIQUEIDENTIFIER                                   NOT NULL,
    [dataanmk]                                 DATETIME                                           NULL,
    [datwijzig]                                DATETIME                                           NULL,
    [uidaanmk]                                 UNIQUEIDENTIFIER                                   NULL,
    [uidwijzig]                                UNIQUEIDENTIFIER                                   NULL,
    [status]                                   INT                                                NULL,
    [archiefid]                                UNIQUEIDENTIFIER                                   NULL,
    [archiefdatum]                             DATETIME                                           NULL,
    [ag_vnr]                                   INT                                                NULL,
    [pg_vnr]                                   INT                                                NULL,
    [pl_vnr]                                   INT                                                NULL,
    [bedrijf]                                  NVARCHAR (60)                                      NULL,
    [accountviewzoekcode]                      NVARCHAR (10)                                      NULL,
    [cashzoekcode]                             NVARCHAR (10)                                      NULL,
    [exactzoekcode]                            NVARCHAR (6)                                       NULL,
    [financialszoekcode]                       NVARCHAR (6)                                       NULL,
    [kingzoekcode]                             NVARCHAR (10)                                      NULL,
    [betalingsconditieid]                      UNIQUEIDENTIFIER                                   NULL,
    [spec1]                                    NVARCHAR (70)                                      NULL,
    [tel1]                                     NVARCHAR (25)                                      NULL,
    [fax1]                                     NVARCHAR (25)                                      NULL,
    [fac_gebruiken]                            INT                                                NULL,
    [fac_bedrijf]                              NVARCHAR (60)                                      NULL,
    [fac_spec1]                                NVARCHAR (70)                                      NULL,
    [fac_tav]                                  NVARCHAR (70)                                      NULL,
    [fac_spec2]                                NVARCHAR (70)                                      NULL,
    [fac_tel1]                                 NVARCHAR (25)                                      NULL,
    [fac_aantal_kopien]                        INT                                                NULL,
    [fac_andereklantid]                        UNIQUEIDENTIFIER                                   NULL,
    [g_rekening_procent]                       MONEY                                              NULL,
    [grootteid]                                UNIQUEIDENTIFIER                                   NULL,
    [debnr]                                    NVARCHAR (6)                                       NULL,
    [potnr]                                    NVARCHAR (6)                                       NULL,
    [www]                                      NVARCHAR (80)                                      NULL,
    [email]                                    NVARCHAR (80)                                      NULL,
    [datexport]                                DATETIME                                           NULL,
    [behandelaarid]                            UNIQUEIDENTIFIER                                   NULL,
    [oprichtingsjaar]                          NVARCHAR (4)                                       NULL,
    [rechtsvormid]                             UNIQUEIDENTIFIER                                   NULL,
    [kvknr]                                    NVARCHAR (30)                                      NULL,
    [rektype]                                  INT                                                NULL,
    [reknr]                                    NVARCHAR (40)                                      NULL,
    [btwnr]                                    NVARCHAR (30)                                      NULL,
    [typeringid]                               UNIQUEIDENTIFIER                                   NULL,
    [aantekeningen]                            NVARCHAR (MAX)                                     NULL,
    [notitie]                                  NVARCHAR (MAX)                                     NULL,
    [vrijvelda]                                UNIQUEIDENTIFIER                                   NULL,
    [vrijveldb]                                NVARCHAR (40)                                      NULL,
    [vrijveldc]                                NVARCHAR (40)                                      NULL,
    [vrijveldd]                                NVARCHAR (40)                                      NULL,
    [vrijvelde]                                NVARCHAR (40)                                      NULL,
    [foto]                                     NVARCHAR (250)                                     NULL,
    [verwerktcoda]                             INT                                                NULL,
    [attentieid]                               UNIQUEIDENTIFIER                                   NULL,
    [attentiemelding]                          NVARCHAR (200)                                     NULL,
    [geocode_lat]                              FLOAT (53)                                         NULL,
    [geocode_lon]                              FLOAT (53)                                         NULL,
    [afkorting]                                NVARCHAR (10)                                      NULL,
    [print_invoice]                            INT                                                NULL,
    [use_invoice_email]                        INT                                                NULL,
    [invoice_mail_salutation]                  NVARCHAR (MAX)                                     NULL,
    [special_debtor]                           BIT                                                NULL,
    [invoiceemailtemplateid]                   UNIQUEIDENTIFIER                                   NULL,
    [invoice_stationeryid]                     UNIQUEIDENTIFIER                                   NULL,
    [regioid]                                  UNIQUEIDENTIFIER                                   NULL,
    [straat1]                                  NVARCHAR (50)                                      NULL,
    [nummer1]                                  NVARCHAR (20)                                      NULL,
    [postcode1]                                NVARCHAR (15)                                      NULL,
    [staat1]                                   NVARCHAR (25)                                      NULL,
    [plaats1]                                  NVARCHAR (30)                                      NULL,
    [land1id]                                  UNIQUEIDENTIFIER                                   NULL,
    [straat2]                                  NVARCHAR (50)                                      NULL,
    [nummer2]                                  NVARCHAR (20)                                      NULL,
    [postcode2]                                NVARCHAR (15)                                      NULL,
    [staat2]                                   NVARCHAR (25)                                      NULL,
    [plaats2]                                  NVARCHAR (30)                                      NULL,
    [land2id]                                  UNIQUEIDENTIFIER                                   NULL,
    [fac_straat1]                              NVARCHAR (50)                                      NULL,
    [fac_nummer1]                              NVARCHAR (20)                                      NULL,
    [fac_postcode1]                            NVARCHAR (15)                                      NULL,
    [fac_staat1]                               NVARCHAR (25)                                      NULL,
    [fac_plaats1]                              NVARCHAR (30)                                      NULL,
    [fac_land1id]                              UNIQUEIDENTIFIER                                   NULL,
    [extraopz1]                                UNIQUEIDENTIFIER                                   NULL,
    [extraopz2]                                UNIQUEIDENTIFIER                                   NULL,
    [extraopz3]                                UNIQUEIDENTIFIER                                   NULL,
    [extraopz4]                                UNIQUEIDENTIFIER                                   NULL,
    [extraopz5]                                UNIQUEIDENTIFIER                                   NULL,
    [extraopz6]                                UNIQUEIDENTIFIER                                   NULL,
    [extravrij6]                               NVARCHAR (40)                                      NULL,
    [extramemo]                                NVARCHAR (MAX)                                     NULL,
    [extravrij5]                               NVARCHAR (40)                                      NULL,
    [extravrij4]                               NVARCHAR (40)                                      NULL,
    [extravrij3]                               NVARCHAR (40)                                      NULL,
    [extravrij2]                               NVARCHAR (40)                                      NULL,
    [extravrij1]                               NVARCHAR (40)                                      NULL,
    [rek_biccode]                              NVARCHAR (14)                                      NULL,
    [invoice_mail_combine_invoice_attachments] INT                                                NULL,
    [invoice_attention]                        NVARCHAR (MAX)                                     NULL,
    [geocode_state]                            INT                                                NULL,
    [use_invoicereminder_email]                BIT                                                NULL,
    [invoice_reminder_planid]                  UNIQUEIDENTIFIER                                   NULL,
    [AuditDWKey]                           INT                                                NULL,
    [ValidFrom]                                DATETIME2 (0) GENERATED ALWAYS AS ROW START HIDDEN CONSTRAINT [DF_dboklantSysStart] DEFAULT (CONVERT([datetime2](0),'0000-01-01 00:00:00')) NOT NULL,
    [ValidTo]                                  DATETIME2 (0) GENERATED ALWAYS AS ROW END HIDDEN   CONSTRAINT [DF_dboklantSysEnd] DEFAULT (CONVERT([datetime2](0),'9999-12-31 23:59:59')) NOT NULL,
    CONSTRAINT [pk_dboklant ] PRIMARY KEY CLUSTERED ([unid] ASC) WITH (DATA_COMPRESSION = PAGE),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[History].[klant], DATA_CONSISTENCY_CHECK=ON));

