CREATE TABLE [dbo].[orcp] (
    [unid]             UNIQUEIDENTIFIER                                   NOT NULL,
    [dataanmk]         DATETIME                                           NULL,
    [datwijzig]        DATETIME                                           NULL,
    [uidaanmk]         UNIQUEIDENTIFIER                                   NULL,
    [uidwijzig]        UNIQUEIDENTIFIER                                   NULL,
    [orid]             UNIQUEIDENTIFIER                                   NULL,
    [status]           INT                                                NULL,
    [attentieid]       UNIQUEIDENTIFIER                                   NULL,
    [attentiemelding]  NVARCHAR (200)                                     NULL,
    [bedrijfarchief]   BIT                                                NULL,
    [voertaalid]       UNIQUEIDENTIFIER                                   NULL,
    [functie]          NVARCHAR (50)                                      NULL,
    [spec2]            NVARCHAR (50)                                      NULL,
    [verantwoordingid] UNIQUEIDENTIFIER                                   NULL,
    [vrijvelda]        UNIQUEIDENTIFIER                                   NULL,
    [vrijveldb]        NVARCHAR (40)                                      NULL,
    [vrijveldc]        NVARCHAR (40)                                      NULL,
    [vrijveldd]        NVARCHAR (40)                                      NULL,
    [vrijvelde]        NVARCHAR (40)                                      NULL,
    [datexport]        DATETIME                                           NULL,
    [aantekening]      NVARCHAR (MAX)                                     NULL,
    [memop]            NVARCHAR (MAX)                                     NULL,
    [personid]         UNIQUEIDENTIFIER                                   NULL,
    [land1pid]         UNIQUEIDENTIFIER                                   NULL,
    [extraopz1]        UNIQUEIDENTIFIER                                   NULL,
    [extraopz2]        UNIQUEIDENTIFIER                                   NULL,
    [extraopz3]        UNIQUEIDENTIFIER                                   NULL,
    [extraopz4]        UNIQUEIDENTIFIER                                   NULL,
    [extramemo]        NVARCHAR (MAX)                                     NULL,
    [extravrij4]       NVARCHAR (40)                                      NULL,
    [extravrij3]       NVARCHAR (40)                                      NULL,
    [extravrij2]       NVARCHAR (40)                                      NULL,
    [extravrij1]       NVARCHAR (40)                                      NULL,
    [AuditDWKey]   INT                                                NULL,
    [ValidFrom]        DATETIME2 (0) GENERATED ALWAYS AS ROW START HIDDEN CONSTRAINT [DF_dboorcpSysStart] DEFAULT (CONVERT([datetime2](0),'0000-01-01 00:00:00')) NOT NULL,
    [ValidTo]          DATETIME2 (0) GENERATED ALWAYS AS ROW END HIDDEN   CONSTRAINT [DF_dboorcpSysEnd] DEFAULT (CONVERT([datetime2](0),'9999-12-31 23:59:59')) NOT NULL,
    CONSTRAINT [pk_dboorcp ] PRIMARY KEY CLUSTERED ([unid] ASC) WITH (DATA_COMPRESSION = PAGE),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[History].[orcp], DATA_CONSISTENCY_CHECK=ON));

