CREATE TABLE [dbo].[projectlead] (
    [unid]               UNIQUEIDENTIFIER                                   NOT NULL,
    [dataanmk]           DATETIME                                           NULL,
    [datwijzig]          DATETIME                                           NULL,
    [uidaanmk]           UNIQUEIDENTIFIER                                   NULL,
    [uidwijzig]          UNIQUEIDENTIFIER                                   NULL,
    [status]             INT                                                NULL,
    [attentieid]         UNIQUEIDENTIFIER                                   NULL,
    [attentiemelding]    NVARCHAR (200)                                     NULL,
    [leadnumber]         NVARCHAR (20)                                      NULL,
    [leadname]           NVARCHAR (70)                                      NULL,
    [vestigingid]        UNIQUEIDENTIFIER                                   NULL,
    [behandeldid]        UNIQUEIDENTIFIER                                   NULL,
    [projecttype]        INT                                                NULL,
    [bewaakdatum]        DATETIME                                           NULL,
    [klantid]            UNIQUEIDENTIFIER                                   NULL,
    [notes]              NVARCHAR (MAX)                                     NULL,
    [contactpersoonid]   UNIQUEIDENTIFIER                                   NULL,
    [acquisition_goalid] UNIQUEIDENTIFIER                                   NULL,
    [productgroepid]     UNIQUEIDENTIFIER                                   NULL,
    [productid]          UNIQUEIDENTIFIER                                   NULL,
    [sales_target]       MONEY                                              NULL,
    [informerid]         UNIQUEIDENTIFIER                                   NULL,
    [informername]       NVARCHAR (60)                                      NULL,
    [archiefid]          UNIQUEIDENTIFIER                                   NULL,
    [archiefdatum]       DATETIME                                           NULL,
    [AuditDWKey]     INT                                                NULL,
    [ValidFrom]          DATETIME2 (0) GENERATED ALWAYS AS ROW START HIDDEN CONSTRAINT [DF_dboprojectleadSysStart] DEFAULT (CONVERT([datetime2](0),'0000-01-01 00:00:00')) NOT NULL,
    [ValidTo]            DATETIME2 (0) GENERATED ALWAYS AS ROW END HIDDEN   CONSTRAINT [DF_dboprojectleadSysEnd] DEFAULT (CONVERT([datetime2](0),'9999-12-31 23:59:59')) NOT NULL,
    CONSTRAINT [pk_dboprojectlead ] PRIMARY KEY CLUSTERED ([unid] ASC) WITH (DATA_COMPRESSION = PAGE),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[History].[projectlead], DATA_CONSISTENCY_CHECK=ON));

