CREATE TABLE [Magister].[leerlinggegevens] (
    [Begindatum]                         DATE         NULL,
    [Einddatum]                          DATE         NULL,
    [Vertrekdatum]                       DATE         NULL,
    [BerekendeIltCode]                   VARCHAR (4)  NULL,
    [ExterneInstromer]                   BIT          NULL,
    [ExterneUitstromer]                  BIT          NULL,
    [LWOO_indicatie]                     BIT          NULL,
    [NietMeetellenMetOfficieleTellingen] BIT          NULL,
    [PRO_indicatie]                      BIT          NULL,
    [Zittenblijver]                      BIT          NULL,
    [BRINnummer]                         VARCHAR (4)  NULL,
    [CodeNevenvestiging]                 VARCHAR (2)  NULL,
    [DatumEersteAanmelding]              DATE         NULL,
    [Klas]                               VARCHAR (16) NULL,
    [Leerjaar]                           VARCHAR (1)  NULL,
    [LesperiodeOmschrijving]             VARCHAR (1)  NULL,
    [TypeVervolgschool]                  VARCHAR (32) NULL,
    [BehaaldBevorderingsresultaat]       BIT          NULL,
    [Bevorderingsresultaat]              VARCHAR (16) NULL,
    [Basisschool]                        VARCHAR (64) NULL,
    [Stamnummer]                         CHAR (6)     NULL,
    [Studie]                             VARCHAR (16) NULL,
    [Vertrekreden]                       VARCHAR (32) NULL,
    [VertrekredenVSV]                    BIT          NULL,
    [Vooropleiding]                      VARCHAR (1)  NULL,
    [LocatieOmschrijving]                VARCHAR (32) NULL,
    [TypeBasisschool]                    VARCHAR (32) NULL,
    [TypeVorigeschool]                   VARCHAR (32) NULL,
    [LocatieCode]                        CHAR (6)     NULL,
    [BRINnummer2]                        VARCHAR (4)  NULL,
    [CodeNevenvestiging2]                VARCHAR (2)  NULL,
    [Vertrekreden2]                      VARCHAR (32) NULL,
    [LocatieOmschrijving2]               VARCHAR (32) NULL,
    [LocatieCode2]                       CHAR (6)     NULL
);

