CREATE TABLE [Staging].[project] (
    [unid]                                     UNIQUEIDENTIFIER NULL,
    [dataanmk]                                 DATETIME         NULL,
    [datwijzig]                                DATETIME         NULL,
    [uidaanmk]                                 UNIQUEIDENTIFIER NULL,
    [uidwijzig]                                UNIQUEIDENTIFIER NULL,
    [status]                                   INT              NULL,
    [archiefid]                                UNIQUEIDENTIFIER NULL,
    [archiefdatum]                             DATETIME         NULL,
    [acquisition_goalid]                       UNIQUEIDENTIFIER NULL,
    [attentieid]                               UNIQUEIDENTIFIER NULL,
    [attentiemelding]                          NVARCHAR (200)   NULL,
    [projectgroepid]                           UNIQUEIDENTIFIER NULL,
    [heeft_andere_eindklant]                   BIT              NULL,
    [eindklantid]                              UNIQUEIDENTIFIER NULL,
    [contactpersoon_eindklant]                 NVARCHAR (40)    NULL,
    [las_tonen_cp_eindklant]                   BIT              NULL,
    [is_template]                              BIT              NULL,
    [template_name]                            NVARCHAR (60)    NULL,
    [fgbkid]                                   UNIQUEIDENTIFIER NULL,
    [projectnr]                                NVARCHAR (20)    NULL,
    [vestigingid]                              UNIQUEIDENTIFIER NULL,
    [vestiging]                                NVARCHAR (40)    NULL,
    [projectnaam]                              NVARCHAR (70)    NULL,
    [productgroepid]                           UNIQUEIDENTIFIER NULL,
    [productid]                                UNIQUEIDENTIFIER NULL,
    [behandeldid]                              UNIQUEIDENTIFIER NULL,
    [projecttype]                              INT              NULL,
    [periodetype]                              INT              NULL,
    [datacceptatie]                            DATETIME         NULL,
    [leverdatum]                               DATETIME         NULL,
    [startdatum]                               DATETIME         NULL,
    [einddatum]                                DATETIME         NULL,
    [beeindigddatum]                           DATETIME         NULL,
    [workflow_verstuurd]                       DATETIME         NULL,
    [beeindigd]                                BIT              NULL,
    [fklantkenmerk]                            NVARCHAR (75)    NULL,
    [fandereklant]                             BIT              NULL,
    [fklantnaam]                               NVARCHAR (60)    NULL,
    [fspec1]                                   NVARCHAR (70)    NULL,
    [ftav]                                     NCHAR (70)       NULL,
    [fspec2]                                   NVARCHAR (70)    NULL,
    [cklantnaam]                               NVARCHAR (60)    NULL,
    [cspec1]                                   NVARCHAR (70)    NULL,
    [ctav]                                     NVARCHAR (40)    NULL,
    [cspec2]                                   NVARCHAR (70)    NULL,
    [aklantnaam]                               NVARCHAR (60)    NULL,
    [aspec1]                                   NVARCHAR (70)    NULL,
    [atav]                                     NVARCHAR (40)    NULL,
    [aspec2]                                   NVARCHAR (70)    NULL,
    [ftel1]                                    NVARCHAR (25)    NULL,
    [f_andere_dot]                             BIT              NULL,
    [f_product_andere_dot]                     BIT              NULL,
    [invoice_templateid]                       UNIQUEIDENTIFIER NULL,
    [f_btwid]                                  UNIQUEIDENTIFIER NULL,
    [f_bijlage]                                BIT              NULL,
    [f_nd_op_bijlage]                          BIT              NULL,
    [f_comm_op_bijlage]                        BIT              NULL,
    [f_proj_naam_op_bijlage]                   BIT              NULL,
    [f_proj_nr_op_bijlage]                     BIT              NULL,
    [f_opslagpercentage_op_bijlage]            BIT              NULL,
    [f_tariefnaam_op_bijlage]                  BIT              NULL,
    [f_email]                                  NVARCHAR (40)    NULL,
    [fprojecttype]                             INT              NULL,
    [fper]                                     INT              NULL,
    [fsoort]                                   INT              NULL,
    [fprojectmin]                              MONEY            NULL,
    [fprojectmax]                              MONEY            NULL,
    [fheeftprojectmax]                         BIT              NULL,
    [ink_in_mnd_lim]                           BIT              NULL,
    [ink_in_project_lim]                       BIT              NULL,
    [fprojectprijs]                            MONEY            NULL,
    [factuurdatum]                             DATETIME         NULL,
    [fmoederproject]                           INT              NULL,
    [fmoederprojectid]                         UNIQUEIDENTIFIER NULL,
    [falleen_moeder_tonen]                     BIT              NULL,
    [f_uurtabel_weergave]                      INT              NULL,
    [holdfactuur]                              BIT              NULL,
    [uurtypen_op_factuur]                      BIT              NULL,
    [cmoederproject]                           INT              NULL,
    [cmoederprojectid]                         UNIQUEIDENTIFIER NULL,
    [cklant1]                                  NVARCHAR (40)    NULL,
    [cklant2]                                  NVARCHAR (40)    NULL,
    [cogdid]                                   UNIQUEIDENTIFIER NULL,
    [contractstatusid]                         UNIQUEIDENTIFIER NULL,
    [aanvraag_vnr]                             INT              NULL,
    [interessecijferid]                        UNIQUEIDENTIFIER NULL,
    [interessefaseid]                          UNIQUEIDENTIFIER NULL,
    [nultarief]                                BIT              NULL,
    [verschotten]                              MONEY            NULL,
    [las_uren_on_hold]                         BIT              NULL,
    [verwerktcoda]                             INT              NULL,
    [invuldatum]                               DATETIME         NULL,
    [afkorting]                                NVARCHAR (10)    NULL,
    [use_invoice_email]                        INT              NULL,
    [print_invoice]                            INT              NULL,
    [invoice_stationeryid]                     UNIQUEIDENTIFIER NULL,
    [betalingsconditieid]                      UNIQUEIDENTIFIER NULL,
    [invoiceemailtemplateid]                   UNIQUEIDENTIFIER NULL,
    [astraat]                                  NVARCHAR (50)    NULL,
    [anummer]                                  NVARCHAR (20)    NULL,
    [apostcode]                                NVARCHAR (15)    NULL,
    [astaat]                                   NVARCHAR (25)    NULL,
    [aplaats]                                  NVARCHAR (30)    NULL,
    [alandid]                                  UNIQUEIDENTIFIER NULL,
    [cstraat]                                  NVARCHAR (50)    NULL,
    [cnummer]                                  NVARCHAR (20)    NULL,
    [cpostcode]                                NVARCHAR (15)    NULL,
    [cstaat]                                   NVARCHAR (25)    NULL,
    [cplaats]                                  NVARCHAR (30)    NULL,
    [clandid]                                  UNIQUEIDENTIFIER NULL,
    [fstraat]                                  NVARCHAR (50)    NULL,
    [fnummer]                                  NVARCHAR (20)    NULL,
    [fpostcode]                                NVARCHAR (15)    NULL,
    [fstaat]                                   NVARCHAR (25)    NULL,
    [fplaats]                                  NVARCHAR (30)    NULL,
    [flandid]                                  UNIQUEIDENTIFIER NULL,
    [extraopz1]                                UNIQUEIDENTIFIER NULL,
    [extraopz2]                                UNIQUEIDENTIFIER NULL,
    [extraopz3]                                UNIQUEIDENTIFIER NULL,
    [extraopz4]                                UNIQUEIDENTIFIER NULL,
    [extraopz5]                                UNIQUEIDENTIFIER NULL,
    [exveld002]                                INT              NULL,
    [extraopz6]                                UNIQUEIDENTIFIER NULL,
    [extravrij1]                               NVARCHAR (40)    NULL,
    [extravrij2]                               NVARCHAR (40)    NULL,
    [extravrij3]                               NVARCHAR (40)    NULL,
    [extravrij4]                               NVARCHAR (40)    NULL,
    [extravrij5]                               NVARCHAR (40)    NULL,
    [extravrij6]                               NVARCHAR (40)    NULL,
    [sales_channel]                            NVARCHAR (35)    NULL,
    [lift3_invoicedate]                        DATETIME         NULL,
    [sales_target]                             MONEY            NULL,
    [use_customer_approval]                    BIT              NULL,
    [deviating_approval_contactid]             UNIQUEIDENTIFIER NULL,
    [invoice_mail_combine_invoice_attachments] INT              NULL,
    [hour_note_required]                       BIT              NULL,
    [customer_approval_salutation]             NVARCHAR (70)    NULL,
    [invoice_shift_span_type]                  INT              NULL,
    [invoice_shift_span_amount]                INT              NULL,
    [invoice_shift_span_relative_to]           INT              NULL,
    [customer_approval_empty_periods]          INT              NULL,
    [lead_sourceid]                            UNIQUEIDENTIFIER NULL,
    [invoice_document_format]                  INT              NULL,
    [invoice_ubl_configurationid]              UNIQUEIDENTIFIER NULL,
    [AuditDWKey]                               INT              NULL
);
