CREATE TABLE [Staging].[voordracht] (
    [unid]                         UNIQUEIDENTIFIER NULL,
    [dataanmk]                     DATETIME         NULL,
    [datwijzig]                    DATETIME         NULL,
    [uidaanmk]                     UNIQUEIDENTIFIER NULL,
    [uidwijzig]                    UNIQUEIDENTIFIER NULL,
    [status]                       INT              NULL,
    [projectid]                    UNIQUEIDENTIFIER NULL,
    [aanvraagid]                   UNIQUEIDENTIFIER NULL,
    [uurprijs]                     MONEY            NULL,
    [utv]                          NVARCHAR (1)     NULL,
    [nultarief]                    BIT              NULL,
    [btwid]                        UNIQUEIDENTIFIER NULL,
    [intern]                       BIT              NULL,
    [productid]                    UNIQUEIDENTIFIER NULL,
    [grootboekid]                  UNIQUEIDENTIFIER NULL,
    [datacceptatie]                DATETIME         NULL,
    [toeslag]                      MONEY            NULL,
    [uurprijs_hi]                  BIT              NULL,
    [werknemertype]                INT              NULL,
    [toestel]                      NVARCHAR (15)    NULL,
    [activiteitgroep_voordrachtid] UNIQUEIDENTIFIER NULL,
    [werklast]                     INT              NULL,
    [geldbudget]                   INT              NULL,
    [geenwerklast]                 BIT              NULL,
    [startdatum]                   DATETIME         NULL,
    [sdv]                          NVARCHAR (1)     NULL,
    [einddatum]                    DATETIME         NULL,
    [edv]                          NVARCHAR (1)     NULL,
    [invuldatum]                   DATETIME         NULL,
    [wn_invuldatum]                DATETIME         NULL,
    [uuruidwijzig]                 UNIQUEIDENTIFIER NULL,
    [uurdatwijzig]                 DATETIME         NULL,
    [inkooptarief]                 MONEY            NULL,
    [tarief_doorbelasting]         MONEY            NULL,
    [nomination_phaseid]           UNIQUEIDENTIFIER NULL,
    [extraopz1]                    UNIQUEIDENTIFIER NULL,
    [extraopz2]                    UNIQUEIDENTIFIER NULL,
    [extraopz3]                    UNIQUEIDENTIFIER NULL,
    [extraopz4]                    UNIQUEIDENTIFIER NULL,
    [extraopz5]                    UNIQUEIDENTIFIER NULL,
    [extraopz6]                    UNIQUEIDENTIFIER NULL,
    [extravrij6]                   NVARCHAR (40)    NULL,
    [extravrij5]                   NVARCHAR (40)    NULL,
    [extravrij4]                   NVARCHAR (40)    NULL,
    [extravrij3]                   NVARCHAR (40)    NULL,
    [extravrij2]                   NVARCHAR (40)    NULL,
    [extravrij1]                   NVARCHAR (40)    NULL,
    [employeeid]                   UNIQUEIDENTIFIER NULL,
    [description]                  NVARCHAR (20)    NULL,
    [budget_and_planning_groupid]  UNIQUEIDENTIFIER NULL,
    [employeetypeid]               UNIQUEIDENTIFIER NULL,
    [AuditDWKey]                   INT              NULL
);
