CREATE TABLE [Staging].[werknemer] (
    [km_submitdate]               DATETIME         NULL,
    [achtervoegsel]               NVARCHAR (8)     NULL,
    [anaam]                       NVARCHAR (30)    NULL,
    [email]                       NVARCHAR (75)    NULL,
    [foto]                        NVARCHAR (250)   NULL,
    [gebplaats]                   NVARCHAR (35)    NULL,
    [land1id]                     UNIQUEIDENTIFIER NULL,
    [las_toon_in_smoelenboek]     BIT              NULL,
    [linkedin]                    NVARCHAR (120)   NULL,
    [meisjesnaam]                 NVARCHAR (30)    NULL,
    [nummer1]                     NVARCHAR (20)    NULL,
    [paspoortgeldigtot]           DATETIME         NULL,
    [paspoortnr]                  NVARCHAR (15)    NULL,
    [paspoorttypeid]              UNIQUEIDENTIFIER NULL,
    [plaats1]                     NVARCHAR (30)    NULL,
    [postcode1]                   NVARCHAR (15)    NULL,
    [regeling1]                   BIT              NULL,
    [regeling1nr]                 NVARCHAR (20)    NULL,
    [regeling1tot]                DATETIME         NULL,
    [regeling1van]                DATETIME         NULL,
    [regeling2]                   BIT              NULL,
    [regeling2nr]                 NVARCHAR (20)    NULL,
    [regeling2tot]                DATETIME         NULL,
    [regeling2van]                DATETIME         NULL,
    [regeling3]                   BIT              NULL,
    [regeling3nr]                 NVARCHAR (20)    NULL,
    [regeling3tot]                DATETIME         NULL,
    [regeling3van]                DATETIME         NULL,
    [regeling4]                   BIT              NULL,
    [regeling4nr]                 NVARCHAR (20)    NULL,
    [regeling4tot]                DATETIME         NULL,
    [regeling4van]                DATETIME         NULL,
    [rek1banknaam]                NVARCHAR (20)    NULL,
    [rek1bankplaats]              NVARCHAR (20)    NULL,
    [rek1biccode]                 NVARCHAR (14)    NULL,
    [rek2banknaam]                NVARCHAR (20)    NULL,
    [rek2bankplaats]              NVARCHAR (20)    NULL,
    [reknr2]                      NVARCHAR (40)    NULL,
    [rektype2]                    INT              NULL,
    [rnaam]                       NVARCHAR (20)    NULL,
    [sofinr]                      NVARCHAR (15)    NULL,
    [sofinummer_buitenland]       BIT              NULL,
    [sos_landid]                  UNIQUEIDENTIFIER NULL,
    [sos_naam]                    NVARCHAR (100)   NULL,
    [sos_nummer]                  NVARCHAR (20)    NULL,
    [sos_plaats]                  NVARCHAR (30)    NULL,
    [sos_postcode]                NVARCHAR (15)    NULL,
    [sos_relatieid]               UNIQUEIDENTIFIER NULL,
    [sos_straat]                  NVARCHAR (50)    NULL,
    [sos_tel1]                    NVARCHAR (25)    NULL,
    [sos_tel1_omschrijving]       NVARCHAR (40)    NULL,
    [sos_tel2]                    NVARCHAR (25)    NULL,
    [sos_tel2_omschrijving]       NVARCHAR (40)    NULL,
    [staat1]                      NVARCHAR (50)    NULL,
    [straat1]                     NVARCHAR (50)    NULL,
    [tel1]                        NVARCHAR (25)    NULL,
    [tel2]                        NVARCHAR (25)    NULL,
    [tel3]                        NVARCHAR (25)    NULL,
    [teloms1]                     NVARCHAR (40)    NULL,
    [teloms2]                     NVARCHAR (40)    NULL,
    [teloms3]                     NVARCHAR (40)    NULL,
    [tussen]                      NVARCHAR (10)    NULL,
    [verwerktcoda]                INT              NULL,
    [vnaam]                       NVARCHAR (50)    NULL,
    [unid]                        UNIQUEIDENTIFIER NULL,
    [dataanmk]                    DATETIME         NULL,
    [datwijzig]                   DATETIME         NULL,
    [uidaanmk]                    UNIQUEIDENTIFIER NULL,
    [uidwijzig]                   UNIQUEIDENTIFIER NULL,
    [status]                      INT              NULL,
    [archiefid]                   UNIQUEIDENTIFIER NULL,
    [archiefdatum]                DATETIME         NULL,
    [inits]                       NVARCHAR (10)    NULL,
    [titel]                       NVARCHAR (15)    NULL,
    [datexport]                   DATETIME         NULL,
    [geslacht]                    INT              NULL,
    [geboren]                     DATETIME         NULL,
    [geboortejaar]                INT              NULL,
    [sollicitatie_aanleidingid]   UNIQUEIDENTIFIER NULL,
    [sollicitatie_aanleiding]     NVARCHAR (25)    NULL,
    [gesolliciteerd_op_functieid] UNIQUEIDENTIFIER NULL,
    [gesolliciteerd_op_functie]   NVARCHAR (30)    NULL,
    [geblandid]                   UNIQUEIDENTIFIER NULL,
    [nationaliteitid]             UNIQUEIDENTIFIER NULL,
    [opleidingid]                 UNIQUEIDENTIFIER NULL,
    [richtingid]                  UNIQUEIDENTIFIER NULL,
    [rijbewijs]                   BIT              NULL,
    [auto]                        BIT              NULL,
    [ovid]                        UNIQUEIDENTIFIER NULL,
    [cvref]                       NVARCHAR (10)    NULL,
    [persnr]                      NVARCHAR (6)     NULL,
    [pmwnr]                       NVARCHAR (6)     NULL,
    [belastinggroep]              INT              NULL,
    [uurtarief]                   MONEY            NULL,
    [inkoopprijs]                 MONEY            NULL,
    [reknr1]                      NVARCHAR (40)    NULL,
    [rektype1]                    INT              NULL,
    [studiestatusid]              UNIQUEIDENTIFIER NULL,
    [leefsituatieid]              UNIQUEIDENTIFIER NULL,
    [stdbeschikbaarheid]          INT              NULL,
    [invuldatum]                  DATETIME         NULL,
    [wn_invuldatum]               DATETIME         NULL,
    [leverancierid]               UNIQUEIDENTIFIER NULL,
    [vestigingid]                 UNIQUEIDENTIFIER NULL,
    [vestiging]                   NVARCHAR (40)    NULL,
    [budgethouderid]              UNIQUEIDENTIFIER NULL,
    [datumindienst]               DATETIME         NULL,
    [hi_datumindienst]            BIT              NULL,
    [Datum_StartDatumContract]    DATETIME         NULL,
    [datumuitdienst]              DATETIME         NULL,
    [datpotwn]                    DATETIME         NULL,
    [Datum_PotentieelWerknemer]   DATETIME         NULL,
    [datwn]                       DATETIME         NULL,
    [attentieid]                  UNIQUEIDENTIFIER NULL,
    [attentiemelding]             NVARCHAR (200)   NULL,
    [urenmanagerid]               UNIQUEIDENTIFIER NULL,
    [boekhoud_url]                NVARCHAR (120)   NULL,
    [geocode_lat]                 FLOAT (53)       NULL,
    [geocode_lon]                 FLOAT (53)       NULL,
    [beschikbaar_vanaf]           DATETIME         NULL,
    [HR_ContactPersoon]           NVARCHAR (35)    NULL,
    [Leidinggevende]              NVARCHAR (35)    NULL,
    [graduation_date]             DATETIME         NULL,
    [geocode_state]               INT              NULL,
    [extraopz1]                   UNIQUEIDENTIFIER NULL,
    [extraopz2]                   UNIQUEIDENTIFIER NULL,
    [extraopz3]                   UNIQUEIDENTIFIER NULL,
    [extraopz4]                   UNIQUEIDENTIFIER NULL,
    [extraopz5]                   UNIQUEIDENTIFIER NULL,
    [extraopz6]                   UNIQUEIDENTIFIER NULL,
    [pmwopz3]                     UNIQUEIDENTIFIER NULL,
    [pmwopz4]                     UNIQUEIDENTIFIER NULL,
    [pmwopz5]                     UNIQUEIDENTIFIER NULL,
    [pmwvrij2]                    NVARCHAR (40)    NULL,
    [pmwopz6]                     UNIQUEIDENTIFIER NULL,
    [pmwvrij1]                    NVARCHAR (40)    NULL,
    [pmwvrij4]                    NVARCHAR (40)    NULL,
    [pmwvrij3]                    NVARCHAR (40)    NULL,
    [pmwvrij6]                    NVARCHAR (40)    NULL,
    [pmwopz1]                     UNIQUEIDENTIFIER NULL,
    [pmwopz2]                     UNIQUEIDENTIFIER NULL,
    [pmwvrij5]                    NVARCHAR (40)    NULL,
    [exveld003]                   UNIQUEIDENTIFIER NULL,
    [exveld002]                   UNIQUEIDENTIFIER NULL,
    [exveld005]                   UNIQUEIDENTIFIER NULL,
    [exveld004]                   UNIQUEIDENTIFIER NULL,
    [extravrij5]                  NVARCHAR (40)    NULL,
    [extravrij4]                  NVARCHAR (40)    NULL,
    [extravrij3]                  NVARCHAR (40)    NULL,
    [extravrij2]                  NVARCHAR (40)    NULL,
    [functie]                     NVARCHAR (35)    NULL,
    [business_unit]               NVARCHAR (35)    NULL,
    [extra_team]                  NVARCHAR (40)    NULL,
    [extra_niveau]                NVARCHAR (40)    NULL,
    [nextappointment_jaar]        NVARCHAR (35)    NULL,
    [nextappointment_maand]       NVARCHAR (35)    NULL,
    [employeetypeid]              UNIQUEIDENTIFIER NULL,
    [recruiterid]                 UNIQUEIDENTIFIER NULL,
    [hr_managerid]                UNIQUEIDENTIFIER NULL,
    [informerid]                  UNIQUEIDENTIFIER NULL,
    [informername]                NVARCHAR (60)    NULL,
    [business_unitid]             UNIQUEIDENTIFIER NULL,
    [extra_niveauid]              UNIQUEIDENTIFIER NULL, 
    [extra_teamid]                UNIQUEIDENTIFIER NULL, 
    [functieid]                   UNIQUEIDENTIFIER NULL,
    [HR_ContactPersoonid]         UNIQUEIDENTIFIER NULL,
    [leidinggevendeid]            UNIQUEIDENTIFIER NULL,
    [nextappointment_jaarid]      UNIQUEIDENTIFIER NULL,
    [nextappointment_maandid]     UNIQUEIDENTIFIER NULL,
    [AuditDWKey]                  INT              NULL
);
