GRANT SELECT,INSERT,DELETE ON SCHEMA::[Staging] TO [etl_writer];
GO
--GRANT ADMINISTER DATABASE BULK OPERATIONS TO [etl_writer];
GO
GRANT EXECUTE ON SCHEMA::[Load] TO [etl_writer];
GO
GRANT EXECUTE ON SCHEMA::[log] TO [etl_writer];
