CREATE TABLE [FileImport_Jira].[Incidents_CWC] (
    [Project]                                        NVARCHAR (MAX) NULL,
    [Key]                                            NVARCHAR (MAX) NULL,
    [Summary]                                        NVARCHAR (MAX) NULL,
    [Issue Type]                                     NVARCHAR (MAX) NULL,
    [Status]                                         NVARCHAR (MAX) NULL,
    [Priority]                                       NVARCHAR (MAX) NULL,
    [Resolution]                                     NVARCHAR (MAX) NULL,
    [Assignee]                                       NVARCHAR (MAX) NULL,
    [Reporter]                                       NVARCHAR (MAX) NULL,
    [Creator]                                        NVARCHAR (MAX) NULL,
    [Created]                                        REAL           NULL,
    [Last Viewed]                                    NVARCHAR (MAX) NULL,
    [Updated]                                        REAL           NULL,
    [Resolved]                                       REAL           NULL,
    [Affects Version/s]                              NVARCHAR (MAX) NULL,
    [Fix Version/s]                                  NVARCHAR (MAX) NULL,
    [Component/s]                                    NVARCHAR (MAX) NULL,
    [Due Date]                                       REAL           NULL,
    [Votes]                                          REAL           NULL,
    [Watchers]                                       REAL           NULL,
    [Images]                                         NVARCHAR (MAX) NULL,
    [Original Estimate]                              NVARCHAR (MAX) NULL,
    [Remaining Estimate]                             NVARCHAR (MAX) NULL,
    [Time Spent]                                     NVARCHAR (MAX) NULL,
    [Work Ratio]                                     NVARCHAR (MAX) NULL,
    [Sub-tasks]                                      NVARCHAR (MAX) NULL,
    [Linked Issues]                                  NVARCHAR (MAX) NULL,
    [Environment]                                    NVARCHAR (MAX) NULL,
    [Description]                                    NVARCHAR (MAX) NULL,
    [Security Level]                                 NVARCHAR (MAX) NULL,
    [Progress]                                       NVARCHAR (MAX) NULL,
    [Σ Progress]                                     NVARCHAR (MAX) NULL,
    [Σ Time Spent]                                   NVARCHAR (MAX) NULL,
    [Σ Remaining Estimate]                           NVARCHAR (MAX) NULL,
    [Σ Original Estimate]                            NVARCHAR (MAX) NULL,
    [Labels]                                         NVARCHAR (MAX) NULL,
    [Profile Title 5]                                NVARCHAR (MAX) NULL,
    [Eerstvolgende uitzending]                       NVARCHAR (MAX) NULL,
    [Maken/bewerken]                                 NVARCHAR (MAX) NULL,
    [Time to Complete]                               NVARCHAR (MAX) NULL,
    [Video Resolution Other]                         NVARCHAR (MAX) NULL,
    [Video Bitrate Other]                            NVARCHAR (MAX) NULL,
    [Member Registration]                            NVARCHAR (MAX) NULL,
    [Skin Type]                                      NVARCHAR (MAX) NULL,
    [Explanation]                                    NVARCHAR (MAX) NULL,
    [Language]                                       NVARCHAR (MAX) NULL,
    [ProfileType 3]                                  NVARCHAR (MAX) NULL,
    [Type]                                           NVARCHAR (MAX) NULL,
    [ProfileType 4]                                  NVARCHAR (MAX) NULL,
    [Scenario]                                       NVARCHAR (MAX) NULL,
    [ProfileType 5]                                  NVARCHAR (MAX) NULL,
    [URL Name]                                       NVARCHAR (MAX) NULL,
    [Landingpage only/portal]                        NVARCHAR (MAX) NULL,
    [Language#]                                      NVARCHAR (MAX) NULL,
    [Profile Title 3]                                NVARCHAR (MAX) NULL,
    [Design]                                         NVARCHAR (MAX) NULL,
    [Profile Title 4]                                NVARCHAR (MAX) NULL,
    [Webcast Type#]                                  NVARCHAR (MAX) NULL,
    [Webcast/Huisstijlboek/Logo/Other]               NVARCHAR (MAX) NULL,
    [video resolution]                               NVARCHAR (MAX) NULL,
    [Custom registration fields]                     NVARCHAR (MAX) NULL,
    [Customer#]                                      NVARCHAR (MAX) NULL,
    [Aftelklok]                                      NVARCHAR (MAX) NULL,
    [Screensharing]                                  NVARCHAR (MAX) NULL,
    [Studiosetting]                                  NVARCHAR (MAX) NULL,
    [Browser]                                        NVARCHAR (MAX) NULL,
    [Landingpage only Confluence (PwR)]              NVARCHAR (MAX) NULL,
    [Video Bitrate]                                  NVARCHAR (MAX) NULL,
    [Video Resolution1]                              NVARCHAR (MAX) NULL,
    [Portal Confluence (PwR)]                        NVARCHAR (MAX) NULL,
    [Skin resolution(s) IR]                          NVARCHAR (MAX) NULL,
    [IR Confluence (SD wiki)]                        NVARCHAR (MAX) NULL,
    [Marketing Confluence (SD wiki)]                 NVARCHAR (MAX) NULL,
    [Profile Title 2]                                NVARCHAR (MAX) NULL,
    [User name]                                      NVARCHAR (MAX) NULL,
    [User type]                                      NVARCHAR (MAX) NULL,
    [Email address]                                  NVARCHAR (MAX) NULL,
    [Notifications]                                  NVARCHAR (MAX) NULL,
    [Portal / Landingpage only / Player only]        NVARCHAR (MAX) NULL,
    [Profile Type 2]                                 NVARCHAR (MAX) NULL,
    [Type Encoder]                                   NVARCHAR (MAX) NULL,
    [Slide capture]                                  NVARCHAR (MAX) NULL,
    [Who will use it?]                               NVARCHAR (MAX) NULL,
    [DCN]                                            NVARCHAR (MAX) NULL,
    [intended purpose]                               NVARCHAR (MAX) NULL,
    [Problem description]                            NVARCHAR (MAX) NULL,
    [What is the result?]                            NVARCHAR (MAX) NULL,
    [Impact on organization]                         NVARCHAR (MAX) NULL,
    [additional comment]                             NVARCHAR (MAX) NULL,
    [Reason]                                         NVARCHAR (MAX) NULL,
    [Customer Color 1]                               NVARCHAR (MAX) NULL,
    [Customer color 2]                               NVARCHAR (MAX) NULL,
    [Customer color 3]                               NVARCHAR (MAX) NULL,
    [Title]                                          NVARCHAR (MAX) NULL,
    [Context]                                        NVARCHAR (MAX) NULL,
    [Naam spreker 4]                                 NVARCHAR (MAX) NULL,
    [Starttijd]                                      NVARCHAR (MAX) NULL,
    [Titel/Functie spreker 4]                        NVARCHAR (MAX) NULL,
    [Crewcall]                                       NVARCHAR (MAX) NULL,
    [Naam spreker 5]                                 NVARCHAR (MAX) NULL,
    [Titel/Functie spreker 5]                        NVARCHAR (MAX) NULL,
    [Gewenste datum bezoek]                          NVARCHAR (MAX) NULL,
    [ProfileType 1]                                  NVARCHAR (MAX) NULL,
    [Request participants]                           NVARCHAR (MAX) NULL,
    [Stoptijd]                                       NVARCHAR (MAX) NULL,
    [Relevant (technisch) contactpersoon op locatie] NVARCHAR (MAX) NULL,
    [Gewenste deadline implementatie]                NVARCHAR (MAX) NULL,
    [Profile Title 1]                                NVARCHAR (MAX) NULL,
    [Naam spreker 2]                                 NVARCHAR (MAX) NULL,
    [Titel/Functie spreker 2]                        NVARCHAR (MAX) NULL,
    [Naam spreker 3]                                 NVARCHAR (MAX) NULL,
    [Aantal talen]                                   NVARCHAR (MAX) NULL,
    [Titel/Functie spreker 3]                        NVARCHAR (MAX) NULL,
    [Planned date]                                   NVARCHAR (MAX) NULL,
    [Solution]                                       NVARCHAR (MAX) NULL,
    [Locatie materiaal]                              NVARCHAR (MAX) NULL,
    [Showstopper]                                    NVARCHAR (MAX) NULL,
    [Domain]                                         NVARCHAR (MAX) NULL,
    [Gewenste resolutie]                             NVARCHAR (MAX) NULL,
    [Customer action]                                NVARCHAR (MAX) NULL,
    [Gewenste resolutie (anders)]                    NVARCHAR (MAX) NULL,
    [Customer response]                              NVARCHAR (MAX) NULL,
    [Video in webcast plaatsen]                      NVARCHAR (MAX) NULL,
    [Naam spreker 1]                                 NVARCHAR (MAX) NULL,
    [Urgent]                                         NVARCHAR (MAX) NULL,
    [Satisfaction]                                   NVARCHAR (MAX) NULL,
    [Titel/Functie spreker 1]                        NVARCHAR (MAX) NULL,
    [Account]                                        NVARCHAR (MAX) NULL,
    [Environment1]                                   NVARCHAR (MAX) NULL,
    [Customer]                                       NVARCHAR (MAX) NULL,
    [Iteration]                                      NVARCHAR (MAX) NULL,
    [Webcast ID]                                     NVARCHAR (MAX) NULL,
    [IP Ranges]                                      NVARCHAR (MAX) NULL,
    [Time to Analyze]                                NVARCHAR (MAX) NULL,
    [Slide Ranges]                                   NVARCHAR (MAX) NULL,
    [Testing Status]                                 NVARCHAR (MAX) NULL,
    [Team]                                           NVARCHAR (MAX) NULL,
    [Customer Request Type]                          NVARCHAR (MAX) NULL,
    [Time to resolution]                             NVARCHAR (MAX) NULL,
    [Lead time]                                      NVARCHAR (MAX) NULL,
    [House Style URL]                                NVARCHAR (MAX) NULL,
    [Assignee1]                                      NVARCHAR (MAX) NULL,
    [File URL]                                       NVARCHAR (MAX) NULL,
    [Internal server URL]                            NVARCHAR (MAX) NULL,
    [Player only Confluence]                         NVARCHAR (MAX) NULL,
    [Portal Confluence (Accounts)]                   NVARCHAR (MAX) NULL,
    [Landingpage only Confluence (Accounts)]         NVARCHAR (MAX) NULL,
    [Cuts]                                           NVARCHAR (MAX) NULL,
    [Epic Color]                                     NVARCHAR (MAX) NULL,
    [Herstellen / knippen]                           NVARCHAR (MAX) NULL,
    [Rank]                                           NVARCHAR (MAX) NULL,
    [Webcast Type]                                   NVARCHAR (MAX) NULL,
    [Resolution1]                                    NVARCHAR (MAX) NULL,
    [Test Sessions]                                  NVARCHAR (MAX) NULL,
    [Raised During]                                  NVARCHAR (MAX) NULL,
    [Resolution Other]                               NVARCHAR (MAX) NULL,
    [Alternative portal URL]                         NVARCHAR (MAX) NULL,
    [Logo URL]                                       NVARCHAR (MAX) NULL,
    [Assignee2]                                      NVARCHAR (MAX) NULL,
    [Business Value]                                 NVARCHAR (MAX) NULL,
    [Target Images Folder URL]                       NVARCHAR (MAX) NULL,
    [Speakers from Top Left to Bottom Right]         NVARCHAR (MAX) NULL,
    [Sprint]                                         NVARCHAR (MAX) NULL,
    [Epic Link]                                      NVARCHAR (MAX) NULL,
    [Epic Name]                                      NVARCHAR (MAX) NULL,
    [Scenario#]                                      NVARCHAR (MAX) NULL,
    [Source Media URL]                               NVARCHAR (MAX) NULL,
    [Epic Status]                                    NVARCHAR (MAX) NULL,
    [Container Width]                                NVARCHAR (MAX) NULL,
    [Container Height]                               NVARCHAR (MAX) NULL,
    [Aspect Ratio]                                   NVARCHAR (MAX) NULL,
    [(CHART) Date of First Response]                 REAL           NULL,
    [Aspect Ratio Other]                             NVARCHAR (MAX) NULL,
    [Flagged]                                        NVARCHAR (MAX) NULL,
    [Registration Type]                              NVARCHAR (MAX) NULL,
    [Epic/Theme]                                     NVARCHAR (MAX) NULL,
    [Assignee3]                                      NVARCHAR (MAX) NULL,
    [Images Folder URL]                              NVARCHAR (MAX) NULL,
    [Story Points]                                   NVARCHAR (MAX) NULL,
    [Caller]                                         NVARCHAR (MAX) NULL,
    [Signed]                                         NVARCHAR (MAX) NULL,
    [Source Client Code]                             NVARCHAR (MAX) NULL,
    [Phone Number]                                   NVARCHAR (MAX) NULL,
    [Target Client Code]                             NVARCHAR (MAX) NULL,
    [Source Skin Name]                               NVARCHAR (MAX) NULL,
    [Target Skin Name]                               NVARCHAR (MAX) NULL,
    [AuditDWKey]                                     INT            NULL
);



