select 
	C1.COLUMN_NAME, C2.Column_Name
from INFORMATION_SCHEMA.COLUMNS C1
full JOIN [DWH-PROD01.OGD.LOCAL].[LIFT_ARCHIVE].INFORMATION_SCHEMA.COLUMNS C2 
	ON (C1.TABLE_SCHEMA = C2.TABLE_SCHEMA COLLATE SQL_Latin1_General_CP1_CI_AS 
		AND C1.TABLE_NAME = C2.TABLE_NAME COLLATE SQL_Latin1_General_CP1_CI_AS 
		AND C1.COLUMN_NAME = C2.COLUMN_NAME COLLATE SQL_Latin1_General_CP1_CI_AS)
WHERE C1.TABLE_SCHEMA = 'dbo' AND C1.TABLE_NAME = 'werknemer'
