--CREATE USER [Resource-DWH-ACC-SQL-Security-TOPdesk] FROM EXTERNAL PROVIDER;

CREATE MASTER KEY ENCRYPTION BY PASSWORD = ''  

CREATE DATABASE SCOPED CREDENTIAL sa_ogdw
WITH IDENTITY = 'sa_ogdw', 
SECRET = '';

CREATE EXTERNAL DATA SOURCE [TOPdesk_DW]
WITH
(
	TYPE=RDBMS,
	LOCATION='ogdw.database.windows.net',
	DATABASE_NAME='TOPdesk_DW',
	CREDENTIAL=sa_ogdw
);