ALTER TABLE [mdm].[tbl_3_40_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_40_EN_PD]  ALTER COLUMN [uda_40_1004]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_40_EN_PD]  ALTER COLUMN [uda_40_1449]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_40_EN_PD]  ALTER COLUMN [uda_40_1565]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_40_EN_PD]  ALTER COLUMN [uda_40_2837]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_40_EN_PD]  ALTER COLUMN [uda_40_2909]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tblSyncRelationship]  ALTER COLUMN [LastSyncAttemptErrorInfo]nvarchar (MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_26_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN]  ALTER COLUMN [uda_67_2722]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN]  ALTER COLUMN [uda_67_2723]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN]  ALTER COLUMN [uda_67_2724]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN]  ALTER COLUMN [uda_67_2725]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN]  ALTER COLUMN [uda_67_2726]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN]  ALTER COLUMN [uda_67_2727]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN]  ALTER COLUMN [uda_67_2729]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN]  ALTER COLUMN [uda_67_2730]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN]  ALTER COLUMN [uda_67_2731]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN]  ALTER COLUMN [uda_67_2732]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN]  ALTER COLUMN [uda_67_2733]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN]  ALTER COLUMN [uda_67_2734]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN]  ALTER COLUMN [uda_67_2735]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN]  ALTER COLUMN [uda_67_2736]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN]  ALTER COLUMN [uda_67_2737]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN]  ALTER COLUMN [uda_67_2738]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN]  ALTER COLUMN [uda_67_2739]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN]  ALTER COLUMN [uda_67_2740]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN]  ALTER COLUMN [uda_67_2741]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN]  ALTER COLUMN [uda_67_2742]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN]  ALTER COLUMN [uda_67_2743]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN]  ALTER COLUMN [uda_67_2744]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN]  ALTER COLUMN [uda_67_2745]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN]  ALTER COLUMN [uda_67_2746]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_51_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[ReportLabels_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[ReportLabels_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[ReportLabels_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[ReportLabels_Leaf]  ALTER COLUMN [Language]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[ReportLabels_Leaf]  ALTER COLUMN [Translation]nvarchar (2000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_38_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_38_EN]  ALTER COLUMN [uda_38_946]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_38_EN]  ALTER COLUMN [uda_38_1450]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tblDBErrors]  ALTER COLUMN [Text]nvarchar (MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tblDBErrors]  ALTER COLUMN [Category]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tblDBErrors]  ALTER COLUMN [Comment]nvarchar (MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_VL]  ALTER COLUMN [MemberCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_2_VL]  ALTER COLUMN [Description]nvarchar (2000) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_2_12_HP]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_45_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[CustomerType_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[CustomerType_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[CustomerType_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_31_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_73_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_6_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_58_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_CS]  ALTER COLUMN [Description]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_41_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tblSystem]  ALTER COLUMN [SchemaVersion]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tblSystem]  ALTER COLUMN [EnterUserID]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tblSystem]  ALTER COLUMN [LastChgUserID]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_26_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_26_EN_HS]  ALTER COLUMN [uda_26_645]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_26_EN_HS]  ALTER COLUMN [uda_26_646]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_26_EN_HS]  ALTER COLUMN [uda_26_648]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_26_EN_HS]  ALTER COLUMN [uda_26_651]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_26_EN_HS]  ALTER COLUMN [uda_26_652]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_26_EN_HS]  ALTER COLUMN [uda_26_653]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_26_EN_HS]  ALTER COLUMN [uda_26_654]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_14_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_51_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_51_EN_HS]  ALTER COLUMN [uda_51_1267]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_51_EN_HS]  ALTER COLUMN [uda_51_1270]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SalesDistrict_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[SalesDistrict_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SalesDistrict_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SalesDistrict_Leaf]  ALTER COLUMN [SalesLocation]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_38_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tblDBUpgradeHistory]  ALTER COLUMN [EnterUser]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN]  ALTER COLUMN [uda_28_696]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN]  ALTER COLUMN [uda_28_700]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN]  ALTER COLUMN [uda_28_701]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN]  ALTER COLUMN [uda_28_702]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN]  ALTER COLUMN [uda_28_703]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN]  ALTER COLUMN [uda_28_706]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN]  ALTER COLUMN [uda_28_708]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN]  ALTER COLUMN [uda_28_709]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN]  ALTER COLUMN [uda_28_710]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN]  ALTER COLUMN [uda_28_711]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN]  ALTER COLUMN [uda_28_712]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN]  ALTER COLUMN [uda_28_713]nvarchar (510) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN]  ALTER COLUMN [uda_28_1271]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_62_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_62_EN_PD]  ALTER COLUMN [uda_62_2617]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_62_EN_PD]  ALTER COLUMN [uda_62_2618]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_62_EN_PD]  ALTER COLUMN [uda_62_2619]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_62_EN_PD]  ALTER COLUMN [uda_62_2620]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1153]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1154]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1155]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1156]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1157]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1158]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1159]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1160]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1161]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1162]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1163]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1164]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1165]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1166]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1167]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1168]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1169]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1170]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1171]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1172]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1173]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1174]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1175]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1176]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1177]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1178]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1179]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1180]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1181]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1204]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1205]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1207]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1208]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1209]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1451]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1452]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1453]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_1454]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_2754]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN]  ALTER COLUMN [uda_47_2755]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimCustomer_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[DimCustomer_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimCustomer_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimCustomer_Leaf]  ALTER COLUMN [Fullname]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimCustomer_Leaf]  ALTER COLUMN [CustomerGroup]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimCustomer_Leaf]  ALTER COLUMN [SLA]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimCustomer_Leaf]  ALTER COLUMN [EndUserServiceType]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimCustomer_Leaf]  ALTER COLUMN [SysAdminServiceType]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimCustomer_Leaf]  ALTER COLUMN [RequiredSecurityClearance]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimCustomer_Leaf]  ALTER COLUMN [Postcode]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimCustomer_Leaf]  ALTER COLUMN [SupportWindow]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimCustomer_Leaf]  ALTER COLUMN [TelephoneNumber]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimCustomer_Leaf]  ALTER COLUMN [SysAdminTeam]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimCustomer_Leaf]  ALTER COLUMN [OutsourcingType]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimCustomer_Leaf]  ALTER COLUMN [CustomerSector]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimCustomer_Leaf]  ALTER COLUMN [ServicesType]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimCustomer_Leaf]  ALTER COLUMN [DebitNumber]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_31_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_73_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_73_EN_HS]  ALTER COLUMN [uda_73_2890]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_73_EN_HS]  ALTER COLUMN [uda_73_2891]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_58_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_2_10_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_41_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tblSystemSettingGroup]  ALTER COLUMN [GroupName]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tblSystemSettingGroup]  ALTER COLUMN [Description]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_HS]  ALTER COLUMN [uda_67_2722]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_HS]  ALTER COLUMN [uda_67_2723]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_HS]  ALTER COLUMN [uda_67_2724]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_HS]  ALTER COLUMN [uda_67_2725]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_HS]  ALTER COLUMN [uda_67_2726]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_HS]  ALTER COLUMN [uda_67_2727]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_HS]  ALTER COLUMN [uda_67_2729]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_HS]  ALTER COLUMN [uda_67_2730]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_HS]  ALTER COLUMN [uda_67_2731]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_HS]  ALTER COLUMN [uda_67_2732]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_HS]  ALTER COLUMN [uda_67_2733]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_HS]  ALTER COLUMN [uda_67_2734]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_HS]  ALTER COLUMN [uda_67_2735]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_HS]  ALTER COLUMN [uda_67_2736]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_HS]  ALTER COLUMN [uda_67_2737]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_HS]  ALTER COLUMN [uda_67_2738]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_HS]  ALTER COLUMN [uda_67_2739]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_HS]  ALTER COLUMN [uda_67_2740]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_HS]  ALTER COLUMN [uda_67_2741]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_HS]  ALTER COLUMN [uda_67_2742]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_HS]  ALTER COLUMN [uda_67_2743]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_HS]  ALTER COLUMN [uda_67_2744]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_HS]  ALTER COLUMN [uda_67_2745]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_HS]  ALTER COLUMN [uda_67_2746]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_15_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SalesLocation_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[SalesLocation_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SalesLocation_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SalesLocation_Leaf]  ALTER COLUMN [SubRegion]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_38_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_38_EN_HS]  ALTER COLUMN [uda_38_1450]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_38_EN_HS]  ALTER COLUMN [uda_38_946]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_34_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_63_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_63_EN]  ALTER COLUMN [uda_63_2637]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_63_EN]  ALTER COLUMN [uda_63_2640]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_63_EN]  ALTER COLUMN [uda_63_2751]nvarchar (MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_63_EN]  ALTER COLUMN [uda_63_2752]nvarchar (MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_63_EN]  ALTER COLUMN [uda_63_2753]nvarchar (MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_63_EN]  ALTER COLUMN [uda_63_2758]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_12_CM_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimCustomerGroup_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[DimCustomerGroup_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimCustomerGroup_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_6_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_11_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_41_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tblSystemSetting]  ALTER COLUMN [SettingName]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tblSystemSetting]  ALTER COLUMN [SettingValue]nvarchar (MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tblSystemSetting]  ALTER COLUMN [Description]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tblSystemSetting]  ALTER COLUMN [MinValue]nvarchar (400) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tblSystemSetting]  ALTER COLUMN [MaxValue]nvarchar (400) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tblSystemSetting]  ALTER COLUMN [ListCode]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_26_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_26_EN_PD]  ALTER COLUMN [uda_26_645]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_26_EN_PD]  ALTER COLUMN [uda_26_646]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_26_EN_PD]  ALTER COLUMN [uda_26_648]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_26_EN_PD]  ALTER COLUMN [uda_26_651]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_26_EN_PD]  ALTER COLUMN [uda_26_652]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_26_EN_PD]  ALTER COLUMN [uda_26_653]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_26_EN_PD]  ALTER COLUMN [uda_26_654]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_15_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_51_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_51_EN_PD]  ALTER COLUMN [uda_51_1267]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_51_EN_PD]  ALTER COLUMN [uda_51_1270]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[Salutation_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[Salutation_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[Salutation_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tblEvent]  ALTER COLUMN [EventName]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tblEvent]  ALTER COLUMN [ErrorMsg]nvarchar (MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_23_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_23_EN]  ALTER COLUMN [uda_23_572]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_23_EN]  ALTER COLUMN [uda_23_573]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_23_EN]  ALTER COLUMN [uda_23_574]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_23_EN]  ALTER COLUMN [uda_23_575]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_23_EN]  ALTER COLUMN [uda_23_576]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_23_EN]  ALTER COLUMN [uda_23_577]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_23_EN]  ALTER COLUMN [uda_23_1109]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_63_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1153]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1154]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1155]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1156]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1157]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1158]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1159]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1160]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1161]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1162]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1163]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1164]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1165]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1166]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1167]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1168]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1169]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1170]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1171]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1172]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1173]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1174]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1175]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1176]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1177]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1178]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1179]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1180]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1181]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1204]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1205]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1207]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1208]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1209]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1451]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1452]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1453]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_1454]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_2754]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_HS]  ALTER COLUMN [uda_47_2755]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimDate3_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[DimDate3_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimDate3_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimDate3_Leaf]  ALTER COLUMN [NL_Weekdag]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimDate3_Leaf]  ALTER COLUMN [EN_Weekday]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimDate3_Leaf]  ALTER COLUMN [EN_Month]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimDate3_Leaf]  ALTER COLUMN [NL_Maand]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimDate3_Leaf]  ALTER COLUMN [NL_WeekdayShort]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimDate3_Leaf]  ALTER COLUMN [NL_MonthShort]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_31_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_73_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_73_EN_PD]  ALTER COLUMN [uda_73_2890]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_73_EN_PD]  ALTER COLUMN [uda_73_2891]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_7_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_58_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_11_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tblUserGroup]  ALTER COLUMN [SID]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tblUserGroup]  ALTER COLUMN [Description]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_27_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_27_EN]  ALTER COLUMN [uda_27_671]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_27_EN]  ALTER COLUMN [uda_27_672]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_27_EN]  ALTER COLUMN [uda_27_673]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_27_EN]  ALTER COLUMN [uda_27_674]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_PD]  ALTER COLUMN [uda_67_2722]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_PD]  ALTER COLUMN [uda_67_2723]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_PD]  ALTER COLUMN [uda_67_2724]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_PD]  ALTER COLUMN [uda_67_2725]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_PD]  ALTER COLUMN [uda_67_2726]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_PD]  ALTER COLUMN [uda_67_2727]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_PD]  ALTER COLUMN [uda_67_2729]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_PD]  ALTER COLUMN [uda_67_2730]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_PD]  ALTER COLUMN [uda_67_2731]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_PD]  ALTER COLUMN [uda_67_2732]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_PD]  ALTER COLUMN [uda_67_2733]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_PD]  ALTER COLUMN [uda_67_2734]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_PD]  ALTER COLUMN [uda_67_2735]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_PD]  ALTER COLUMN [uda_67_2736]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_PD]  ALTER COLUMN [uda_67_2737]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_PD]  ALTER COLUMN [uda_67_2738]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_PD]  ALTER COLUMN [uda_67_2739]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_PD]  ALTER COLUMN [uda_67_2740]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_PD]  ALTER COLUMN [uda_67_2741]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_PD]  ALTER COLUMN [uda_67_2742]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_PD]  ALTER COLUMN [uda_67_2743]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_PD]  ALTER COLUMN [uda_67_2744]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_PD]  ALTER COLUMN [uda_67_2745]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_67_EN_PD]  ALTER COLUMN [uda_67_2746]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_52_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SecurityClearance_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[SecurityClearance_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SecurityClearance_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_38_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_38_EN_PD]  ALTER COLUMN [uda_38_1450]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_38_EN_PD]  ALTER COLUMN [uda_38_946]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tblExternalSystem]  ALTER COLUMN [Description]nvarchar (4000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_23_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_63_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_63_EN_HS]  ALTER COLUMN [uda_63_2637]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_63_EN_HS]  ALTER COLUMN [uda_63_2640]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_63_EN_HS]  ALTER COLUMN [uda_63_2751]nvarchar (MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_63_EN_HS]  ALTER COLUMN [uda_63_2752]nvarchar (MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_63_EN_HS]  ALTER COLUMN [uda_63_2753]nvarchar (MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_63_EN_HS]  ALTER COLUMN [uda_63_2758]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_12_CN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimensionOrFact_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[DimensionOrFact_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimensionOrFact_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_32_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_74_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_7_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_59_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_2_11_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_41_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_27_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_69_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_69_EN]  ALTER COLUMN [uda_69_2804]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_69_EN]  ALTER COLUMN [uda_69_2814]nvarchar (20) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_69_EN]  ALTER COLUMN [uda_69_2815]nvarchar (20) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_15_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_52_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[ServicesType_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[ServicesType_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[ServicesType_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_39_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tblFile]  ALTER COLUMN [FileName]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tblFile]  ALTER COLUMN [FileContentType]nvarchar (400) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_23_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_23_EN_HS]  ALTER COLUMN [uda_23_1109]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_23_EN_HS]  ALTER COLUMN [uda_23_572]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_23_EN_HS]  ALTER COLUMN [uda_23_573]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_23_EN_HS]  ALTER COLUMN [uda_23_574]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_23_EN_HS]  ALTER COLUMN [uda_23_575]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_23_EN_HS]  ALTER COLUMN [uda_23_576]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_23_EN_HS]  ALTER COLUMN [uda_23_577]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_12_CN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_2_12_CN_HS]  ALTER COLUMN [Description]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1153]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1154]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1155]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1156]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1157]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1158]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1159]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1160]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1161]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1162]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1163]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1164]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1165]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1166]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1167]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1168]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1169]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1170]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1171]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1172]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1173]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1174]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1175]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1176]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1177]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1178]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1179]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1180]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1181]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1204]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1205]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1207]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1208]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1209]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1451]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1452]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1453]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_1454]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_2754]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_47_EN_PD]  ALTER COLUMN [uda_47_2755]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimSLA_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[DimSLA_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimSLA_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_32_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_74_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_59_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN]  ALTER COLUMN [uda_42_1025]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN]  ALTER COLUMN [uda_42_1026]nvarchar (454) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN]  ALTER COLUMN [uda_42_1027]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN]  ALTER COLUMN [uda_42_1031]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN]  ALTER COLUMN [uda_42_1032]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN]  ALTER COLUMN [uda_42_1033]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN]  ALTER COLUMN [uda_42_1034]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN]  ALTER COLUMN [uda_42_1035]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN]  ALTER COLUMN [uda_42_1039]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN]  ALTER COLUMN [uda_42_1040]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN]  ALTER COLUMN [uda_42_1042]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tblUserPreference]  ALTER COLUMN [PreferenceName]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tblUserPreference]  ALTER COLUMN [PreferenceValue]nvarchar (MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_27_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_27_EN_HS]  ALTER COLUMN [uda_27_671]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_27_EN_HS]  ALTER COLUMN [uda_27_672]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_27_EN_HS]  ALTER COLUMN [uda_27_673]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_27_EN_HS]  ALTER COLUMN [uda_27_674]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_69_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_16_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceColumnTranslation_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[SourceColumnTranslation_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceColumnTranslation_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceColumnTranslation_Leaf]  ALTER COLUMN [SourceDatabase]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceColumnTranslation_Leaf]  ALTER COLUMN [DWStagingTableName]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceColumnTranslation_Leaf]  ALTER COLUMN [DWColumn]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceColumnTranslation_Leaf]  ALTER COLUMN [SourceColumn]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_39_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_63_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_63_EN_PD]  ALTER COLUMN [uda_63_2637]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_63_EN_PD]  ALTER COLUMN [uda_63_2640]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_63_EN_PD]  ALTER COLUMN [uda_63_2751]nvarchar (MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_63_EN_PD]  ALTER COLUMN [uda_63_2752]nvarchar (MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_63_EN_PD]  ALTER COLUMN [uda_63_2753]nvarchar (MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_63_EN_PD]  ALTER COLUMN [uda_63_2758]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_12_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_48_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[DimSupportWindow_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[DimSupportWindow_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimSupportWindow_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimSupportWindow_Leaf]  ALTER COLUMN [MaStart]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimSupportWindow_Leaf]  ALTER COLUMN [MaEind]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimSupportWindow_Leaf]  ALTER COLUMN [DiStart]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimSupportWindow_Leaf]  ALTER COLUMN [DiEind]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimSupportWindow_Leaf]  ALTER COLUMN [WoStart]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimSupportWindow_Leaf]  ALTER COLUMN [WoEind]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimSupportWindow_Leaf]  ALTER COLUMN [DoStart]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimSupportWindow_Leaf]  ALTER COLUMN [DoEind]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimSupportWindow_Leaf]  ALTER COLUMN [VrStart]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimSupportWindow_Leaf]  ALTER COLUMN [VrEind]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimSupportWindow_Leaf]  ALTER COLUMN [ZaStart]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimSupportWindow_Leaf]  ALTER COLUMN [ZaEind]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimSupportWindow_Leaf]  ALTER COLUMN [ZoStart]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimSupportWindow_Leaf]  ALTER COLUMN [ZoEind]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_7_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_59_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_2_11_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TelefonieStoringen_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[TelefonieStoringen_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TelefonieStoringen_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TelefonieStoringen_Leaf]  ALTER COLUMN [Classificatie]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TelefonieStoringen_Leaf]  ALTER COLUMN [Oorzaak]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TelefonieStoringen_Leaf]  ALTER COLUMN [StartTijd]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TelefonieStoringen_Leaf]  ALTER COLUMN [EindTijd]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_69_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_69_EN_HS]  ALTER COLUMN [uda_69_2804]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_69_EN_HS]  ALTER COLUMN [uda_69_2814]nvarchar (20) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_69_EN_HS]  ALTER COLUMN [uda_69_2815]nvarchar (20) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_16_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_52_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceDefinitions_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[SourceDefinitions_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceDefinitions_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceDefinitions_Leaf]  ALTER COLUMN [DatabaseType]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceDefinitions_Leaf]  ALTER COLUMN [ImportIncidents]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceDefinitions_Leaf]  ALTER COLUMN [ImportChanges]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceDefinitions_Leaf]  ALTER COLUMN [ConnectionString]nvarchar (2000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceDefinitions_Leaf]  ALTER COLUMN [Enabled]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceDefinitions_Leaf]  ALTER COLUMN [SourceType]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceDefinitions_Leaf]  ALTER COLUMN [ImportFileType]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceDefinitions_Leaf]  ALTER COLUMN [DatabaseLabel]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceDefinitions_Leaf]  ALTER COLUMN [Query]nvarchar (510) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceDefinitions_Leaf]  ALTER COLUMN [ConnectionName]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_39_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tblList]  ALTER COLUMN [ListCode]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tblList]  ALTER COLUMN [ListName]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tblList]  ALTER COLUMN [ListOption]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_CS]  ALTER COLUMN [Description]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_64_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_2_12_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_2_12_EN_HS]  ALTER COLUMN [uda_12_389]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_12_EN_HS]  ALTER COLUMN [uda_12_390]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_12_EN_HS]  ALTER COLUMN [uda_12_391]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_12_EN_HS]  ALTER COLUMN [uda_12_394]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_12_EN_HS]  ALTER COLUMN [uda_12_395]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_12_EN_HS]  ALTER COLUMN [uda_12_396]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_12_EN_HS]  ALTER COLUMN [uda_12_397]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_12_EN_HS]  ALTER COLUMN [uda_12_404]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_48_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimTime_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[DimTime_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimTime_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimTime_Leaf]  ALTER COLUMN [am_pm]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[DimTime_Leaf]  ALTER COLUMN [Time_half_hour_of_day]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_32_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_74_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_8_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tblUser]  ALTER COLUMN [SID]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tblUser]  ALTER COLUMN [UserName]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tblUser]  ALTER COLUMN [Description]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tblUser]  ALTER COLUMN [EmailAddress]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN_HS]  ALTER COLUMN [uda_42_1025]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN_HS]  ALTER COLUMN [uda_42_1026]nvarchar (454) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN_HS]  ALTER COLUMN [uda_42_1027]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN_HS]  ALTER COLUMN [uda_42_1031]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN_HS]  ALTER COLUMN [uda_42_1032]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN_HS]  ALTER COLUMN [uda_42_1033]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN_HS]  ALTER COLUMN [uda_42_1034]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN_HS]  ALTER COLUMN [uda_42_1035]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN_HS]  ALTER COLUMN [uda_42_1039]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN_HS]  ALTER COLUMN [uda_42_1040]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN_HS]  ALTER COLUMN [uda_42_1042]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[Test_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[Test_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[Test_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[AddressType_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[AddressType_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[AddressType_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_27_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_27_EN_PD]  ALTER COLUMN [uda_27_671]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_27_EN_PD]  ALTER COLUMN [uda_27_672]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_27_EN_PD]  ALTER COLUMN [uda_27_673]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_27_EN_PD]  ALTER COLUMN [uda_27_674]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_53_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[SourceHierarchy_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[SourceHierarchy_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceHierarchy_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceHierarchy_Leaf]  ALTER COLUMN [DimTable]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceHierarchy_Leaf]  ALTER COLUMN [Hierarchy]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceHierarchy_Leaf]  ALTER COLUMN [ChildID]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceHierarchy_Leaf]  ALTER COLUMN [ChildColumn]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceHierarchy_Leaf]  ALTER COLUMN [ChildValue]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceHierarchy_Leaf]  ALTER COLUMN [ParentID]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceHierarchy_Leaf]  ALTER COLUMN [SourceName]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tblLocalizedStrings]  ALTER COLUMN [ResourceName]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tblLocalizedStrings]  ALTER COLUMN [LocalizedValue]nvarchar (MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_23_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_23_EN_PD]  ALTER COLUMN [uda_23_1109]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_23_EN_PD]  ALTER COLUMN [uda_23_572]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_23_EN_PD]  ALTER COLUMN [uda_23_573]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_23_EN_PD]  ALTER COLUMN [uda_23_574]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_23_EN_PD]  ALTER COLUMN [uda_23_575]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_23_EN_PD]  ALTER COLUMN [uda_23_576]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_23_EN_PD]  ALTER COLUMN [uda_23_577]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_64_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_48_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[Domain_ImportType_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[Domain_ImportType_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[Domain_ImportType_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_33_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_33_EN]  ALTER COLUMN [uda_33_808]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_33_EN]  ALTER COLUMN [uda_33_809]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_33_EN]  ALTER COLUMN [uda_33_832]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_TR]  ALTER COLUMN [MemberCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_TR]  ALTER COLUMN [OldValue]nvarchar (MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_TR]  ALTER COLUMN [OldCode]nvarchar (MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_TR]  ALTER COLUMN [NewValue]nvarchar (MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_TR]  ALTER COLUMN [NewCode]nvarchar (MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_8_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_59_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_12_CN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_2_12_CN]  ALTER COLUMN [Description]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[Test_sourcetranslation_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[Test_sourcetranslation_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[Test_sourcetranslation_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[Test_sourcetranslation_Leaf]  ALTER COLUMN [Translatedvalue]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[Test_sourcetranslation_Leaf]  ALTER COLUMN [inputvalue]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[Test_sourcetranslation_Leaf]  ALTER COLUMN [Klantnaam]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[AMColumnDefinition_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[AMColumnDefinition_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[AMColumnDefinition_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[AMColumnDefinition_Leaf]  ALTER COLUMN [Anchor1]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[AMColumnDefinition_Leaf]  ALTER COLUMN [Role1]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[AMColumnDefinition_Leaf]  ALTER COLUMN [Anchor2]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[AMColumnDefinition_Leaf]  ALTER COLUMN [Role2]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_69_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_69_EN_PD]  ALTER COLUMN [uda_69_2804]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_69_EN_PD]  ALTER COLUMN [uda_69_2814]nvarchar (20) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_69_EN_PD]  ALTER COLUMN [uda_69_2815]nvarchar (20) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_16_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_53_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceTranslations_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[SourceTranslations_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceTranslations_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceTranslations_Leaf]  ALTER COLUMN [SourceName]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceTranslations_Leaf]  ALTER COLUMN [DWTableName]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceTranslations_Leaf]  ALTER COLUMN [DWColumnName2]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceTranslations_Leaf]  ALTER COLUMN [TranslatedColumnName]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceTranslations_Leaf]  ALTER COLUMN [SourceValue]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceTranslations_Leaf]  ALTER COLUMN [TranslatedValue]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceTranslations_Leaf]  ALTER COLUMN [TranslationType]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceTranslations_Leaf]  ALTER COLUMN [DWColumnName]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SourceTranslations_Leaf]  ALTER COLUMN [AMAnchorName]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_39_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tblNotificationQueue]  ALTER COLUMN [Message]nvarchar (MAX) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tblNotificationQueue]  ALTER COLUMN [PriorityRank]nvarchar (510) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_31_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_64_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_2_12_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_12_EN_PD]  ALTER COLUMN [uda_12_389]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_12_EN_PD]  ALTER COLUMN [uda_12_390]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_12_EN_PD]  ALTER COLUMN [uda_12_391]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_12_EN_PD]  ALTER COLUMN [uda_12_394]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_12_EN_PD]  ALTER COLUMN [uda_12_395]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_12_EN_PD]  ALTER COLUMN [uda_12_396]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_12_EN_PD]  ALTER COLUMN [uda_12_397]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_12_EN_PD]  ALTER COLUMN [uda_12_404]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[Domain_ServiceType_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[Domain_ServiceType_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[Domain_ServiceType_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_33_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_60_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_60_EN]  ALTER COLUMN [uda_60_1555]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_60_EN]  ALTER COLUMN [uda_60_1556]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_13_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN_PD]  ALTER COLUMN [uda_42_1025]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN_PD]  ALTER COLUMN [uda_42_1026]nvarchar (454) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN_PD]  ALTER COLUMN [uda_42_1027]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN_PD]  ALTER COLUMN [uda_42_1031]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN_PD]  ALTER COLUMN [uda_42_1032]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN_PD]  ALTER COLUMN [uda_42_1033]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN_PD]  ALTER COLUMN [uda_42_1034]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN_PD]  ALTER COLUMN [uda_42_1035]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN_PD]  ALTER COLUMN [uda_42_1039]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN_PD]  ALTER COLUMN [uda_42_1040]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_42_EN_PD]  ALTER COLUMN [uda_42_1042]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [product]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [build]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [TABLE_CATALOG]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [TABLE_SCHEMA]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [TABLE_NAME]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [COLUMN_NAME]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [COLUMN_DEFAULT]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [IS_NULLABLE]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [DATA_TYPE]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [CHARACTER_MAXIMUM_LENGTH]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [CHARACTER_OCTET_LENGTH]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [NUMERIC_PRECISION]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [NUMERIC_PRECISION_RADIX]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [NUMERIC_SCALE]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [DATETIME_PRECISION]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [CHARACTER_SET_CATALOG]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [CHARACTER_SET_SCHEMA]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [CHARACTER_SET_NAME]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [COLLATION_CATALOG]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [COLLATION_SCHEMA]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [COLLATION_NAME]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [DOMAIN_CATALOG]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [DOMAIN_SCHEMA]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Columns_Leaf]  ALTER COLUMN [DOMAIN_NAME]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[AMTieDefinition_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[AMTieDefinition_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[AMTieDefinition_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[AMTieDefinition_Leaf]  ALTER COLUMN [DWColumn]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[AMTieDefinition_Leaf]  ALTER COLUMN [Comment]nvarchar (454) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[AMTieDefinition_Leaf]  ALTER COLUMN [AM_import]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[AMTieDefinition_Leaf]  ALTER COLUMN [AM_Schema]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[AMTieDefinition_Leaf]  ALTER COLUMN [AM_AnchorName]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[AMTieDefinition_Leaf]  ALTER COLUMN [AM_AnchorMnemonic]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[AMTieDefinition_Leaf]  ALTER COLUMN [AM_AttributeName]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[AMTieDefinition_Leaf]  ALTER COLUMN [AM_AttributeMnemonic]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[AMTieDefinition_Leaf]  ALTER COLUMN [AM_KnotName]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[AMTieDefinition_Leaf]  ALTER COLUMN [AM_KnotMnemonic]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[AMTieDefinition_Leaf]  ALTER COLUMN [timestamp]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN_HS]  ALTER COLUMN [uda_28_1271]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN_HS]  ALTER COLUMN [uda_28_696]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN_HS]  ALTER COLUMN [uda_28_700]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN_HS]  ALTER COLUMN [uda_28_701]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN_HS]  ALTER COLUMN [uda_28_702]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN_HS]  ALTER COLUMN [uda_28_703]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN_HS]  ALTER COLUMN [uda_28_706]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN_HS]  ALTER COLUMN [uda_28_708]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN_HS]  ALTER COLUMN [uda_28_709]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN_HS]  ALTER COLUMN [uda_28_710]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN_HS]  ALTER COLUMN [uda_28_711]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN_HS]  ALTER COLUMN [uda_28_712]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_28_EN_HS]  ALTER COLUMN [uda_28_713]nvarchar (510) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_70_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_70_EN]  ALTER COLUMN [uda_70_2832]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_70_EN]  ALTER COLUMN [uda_70_2833]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_70_EN]  ALTER COLUMN [uda_70_2834]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_17_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_53_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[SSIS_Types_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[SSIS_Types_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SSIS_Types_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SSIS_Types_Leaf]  ALTER COLUMN [SqlType]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SSIS_Types_Leaf]  ALTER COLUMN [CastToSSIS]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[SSIS_Types_Leaf]  ALTER COLUMN [BimlType]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_44_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_32_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_2_12_HP_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_48_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[Domain_SourceType_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[Domain_SourceType_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[Domain_SourceType_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_33_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_33_EN_HS]  ALTER COLUMN [uda_33_808]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_33_EN_HS]  ALTER COLUMN [uda_33_809]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_33_EN_HS]  ALTER COLUMN [uda_33_832]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_VL]  ALTER COLUMN [MemberCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_VL]  ALTER COLUMN [Description]nvarchar (2000) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_2_8_EN_PD]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_60_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_8_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_43_EN]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [mdm].[tbl_3_43_EN]  ALTER COLUMN [uda_43_1059]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_43_EN]  ALTER COLUMN [uda_43_1060]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_43_EN]  ALTER COLUMN [uda_43_1061]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_43_EN]  ALTER COLUMN [uda_43_1062]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Tables_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[TOPdesk_Tables_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Tables_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Tables_Leaf]  ALTER COLUMN [product]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Tables_Leaf]  ALTER COLUMN [build]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Tables_Leaf]  ALTER COLUMN [TABLE_CATALOG]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Tables_Leaf]  ALTER COLUMN [TABLE_SCHEMA]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Tables_Leaf]  ALTER COLUMN [TABLE_NAME]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[TOPdesk_Tables_Leaf]  ALTER COLUMN [TABLE_TYPE]nvarchar (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[AnywhereSkillTranslation_Leaf]  ALTER COLUMN [BatchTag]nvarchar (100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 
ALTER TABLE [stg].[AnywhereSkillTranslation_Leaf]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[AnywhereSkillTranslation_Leaf]  ALTER COLUMN [NewCode]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [stg].[AnywhereSkillTranslation_Leaf]  ALTER COLUMN [Customer]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_3_70_EN_AN]  ALTER COLUMN [Comment]nvarchar (1000) COLLATE SQL_Latin1_General_CP1_CS_AS NULL; 
ALTER TABLE [mdm].[tbl_2_17_EN_HS]  ALTER COLUMN [Code]nvarchar (500) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL; 