CREATE TABLE [FileImport].[Changes]
(
	[CardCreatedBy]                NVARCHAR (85)                               NULL,
	[RequestDate]                  DATETIME2 (7)                               NULL,
	[Department]                   NVARCHAR (60)                               NULL,
	[Rejected]                     BIT                                         NULL,
	[ProcessingStatus]             NVARCHAR (50)                               NULL,
	[RejectionDate]                DATETIME2 (7)                               NULL,
	[AuthorizationDate]            DATETIME2 (7)                               NULL,
	[OperatorSimpleChange]         NVARCHAR (80)                               NULL,
	[OperatorEvaluationExtChange]  NVARCHAR (80)                               NULL,
	[OperatorProgressExtChange]    NVARCHAR (80)                               NULL,
	[OperatorRequestChange]        NVARCHAR (80)                               NULL,
	[OperatorGroup]                NVARCHAR (93)                               NULL,
	[Category]                     NVARCHAR (30)                               NULL,
	[Coordinator]                  NVARCHAR (93)                               NULL,
	[CreationDate]                 DATETIME2 (7)                               NULL,
	[ChangeDate]                   DATETIME2 (7)                               NULL,
	[ClosureDateSimpleChange]      DATETIME2 (7)                               NULL,
	[SubmissionDateRequestChange]  DATETIME2 (7)                               NULL,
	[NoGoDateExtChange]            DATETIME2 (7)                               NULL,
	[CancelDateExtChange]          DATETIME2 (7)                               NULL,
	[DateCalcTypeEvaluation]       NVARCHAR (30)                               NULL,
	[DateCalcTypeProgress]         NVARCHAR (30)                               NULL,
	[DateCalcTypeRequestChange]    NVARCHAR (30)                               NULL,
	[CallerEmail]                  NVARCHAR (100)                              NULL,
	[Evaluation]                   BIT                                         NULL,
	[ExternalNumber]               NVARCHAR (60)                               NULL,
	[CancelledByOperator]          NVARCHAR (93)                               NULL,
	[CancelledByManager]           NVARCHAR (93)                               NULL,
	[Implemented]                  BIT                                         NULL,
	[PlannedAuthDateRequestChange] DATETIME2 (7)                               NULL,
	[PlannedFinalDate]             DATETIME2 (7)                               NULL,
	[PlannedImplDate]              DATETIME2 (7)                               NULL,
	[PlannedStartDateSimpleChange] DATETIME2 (7)                               NULL,
	[TimeSpent]                    BIGINT                                      NULL,
	[EndDateExtChange]             DATETIME2 (7)                               NULL,
	[StartDateSimpleChange]        DATETIME2 (7)                               NULL,
	[Closed]                       BIT                                         NULL,
	[Started]                      BIT                                         NULL,
	[CurrentPhase]                 NVARCHAR (50)                               NULL,
	[Impact]                       NVARCHAR (30)                               NULL,
	[ImplDateSimpleChange]         DATETIME2 (7)                               NULL,
	[ImplDateExtChange]            DATETIME2 (7)                               NULL,
	[CustomerName]                 NVARCHAR (60)                               NULL,
	[DescriptionBrief]             NVARCHAR (80)                               NULL,
	[CallerName]                   NVARCHAR (93)                               NULL,
	[ObjectID]                     NVARCHAR (60)                               NULL,
	[OriginalIncident]             NVARCHAR (30)                               NULL,
	[Priority]                     NVARCHAR (30)                               NULL,
	[Template]                     NVARCHAR (80)                               NULL,
	[Type]                         NVARCHAR (40)                               NULL,
	[ChangeType]                   NVARCHAR (50)                               NULL,
	[Status]                       NVARCHAR (30)                               NULL,
	[Subcategory]                  NVARCHAR (30)                               NULL,
	[CallerTelephoneNumber]        NVARCHAR (25)                               NULL,
	[Urgency]                      BIT                                         NULL,
	[CallerBranch]                 NVARCHAR (60)                               NULL,
	[CardChangedBy]                NVARCHAR (85)                               NULL,
	[CallerLocation]               NVARCHAR (50)                               NULL,
	[IsUrgent]                     BIT                                         NULL,
	[ChangeNumber]                 VARCHAR (36)                                NOT NULL,
	[AuditDWKey]                   INT                                         NOT NULL,
	[SourceDatabaseKey]            INT                                         NOT NULL,
	[ValidFrom]                    DATETIME2 (0) GENERATED ALWAYS AS ROW START CONSTRAINT [DF_FileImportChangesSysStart] DEFAULT (CONVERT([datetime2](0),'0000-01-01 00:00:00')) NOT NULL,
	[ValidTo]                      DATETIME2 (0) GENERATED ALWAYS AS ROW END   CONSTRAINT [DF_FileImportChangesSysEnd] DEFAULT (CONVERT([datetime2](0),'9999-12-31 23:59:59')) NOT NULL,
	CONSTRAINT [PK_FileImportChanges] PRIMARY KEY CLUSTERED ([ChangeNumber] ASC, [AuditDWKey] ASC) WITH (DATA_COMPRESSION = PAGE),
	PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[history].[Changes], DATA_CONSISTENCY_CHECK=ON))