CREATE TABLE [FileImport].[Incidents]
(
	[DurationAdjusted]      BIGINT                                      NULL,
	[CardCreatedBy]         NVARCHAR (85)                               NULL,
	[NumberOfDaysCurrent]   INT                                         NULL,
	[Department]            NVARCHAR (60)                               NULL,
	[Closed]                BIT                                         NULL,
	[OperatorName]          NVARCHAR (93)                               NULL,
	[OperatorGroup]         NVARCHAR (93)                               NULL,
	[TimeSpentFirstLine]    BIGINT                                      NULL,
	[TimeSpentSecondLine]   BIGINT                                      NULL,
	[Category]              NVARCHAR (30)                               NULL,
	[ConfigurationID]       NVARCHAR (30)                               NULL,
	[CreationDate]          DATETIME2 (7)                               NULL,
	[ChangeDate]            DATETIME2 (7)                               NULL,
	[IncidentDate]          DATETIME2 (7)                               NULL,
	[ClosureDate]           DATETIME2 (7)                               NULL,
	[TargetDate]            DATETIME2 (7)                               NULL,
	[CompletionDate]        DATETIME2 (7)                               NULL,
	[OnHoldDate]            DATETIME2 (7)                               NULL,
	[Duration]              NVARCHAR (60)                               NULL,
	[DurationOnHold]        BIGINT                                      NULL,
	[CallerEmail]           NVARCHAR (100)                              NULL,
	[ExternalNumber]        NVARCHAR (60)                               NULL,
	[SlaAchieved]           NVARCHAR (50)                               NULL,
	[DurationActual]        BIGINT                                      NULL,
	[Completed]             BIT                                         NULL,
	[TotalTime]             BIGINT                                      NULL,
	[CallerGender]          NVARCHAR (10)                               NULL,
	[Impact]                NVARCHAR (30)                               NULL,
	[IsMajorIncident]       BIT                                         NULL,
	[CustomerName]          NVARCHAR (60)                               NULL,
	[IncidentDescription]   NVARCHAR (80)                               NULL,
	[Supplier]              NVARCHAR (60)                               NULL,
	[Line]                  NVARCHAR (50)                               NULL,
	[MajorIncident]         NVARCHAR (30)                               NULL,
	[CallerMobileNumber]    NVARCHAR (25)                               NULL,
	[CallerName]            NVARCHAR (93)                               NULL,
	[ObjectID]              NVARCHAR (60)                               NULL,
	[Onhold]                BIT                                         NULL,
	[CallerCity]            NVARCHAR (30)                               NULL,
	[Priority]              NVARCHAR (30)                               NULL,
	[ServiceWindow]         NVARCHAR (100)                              NULL,
	[Sla]                   NVARCHAR (75)                               NULL,
	[SlaTargetDate]         DATETIME2 (7)                               NULL,
	[SlaContract]           NVARCHAR (40)                               NULL,
	[SlaLevel]              NVARCHAR (20)                               NULL,
	[EntryType]             NVARCHAR (30)                               NULL,
	[IncidentType]          NVARCHAR (30)                               NULL,
	[StandardSolution]      NVARCHAR (80)                               NULL,
	[Status]                NVARCHAR (30)                               NULL,
	[Subcategory]           NVARCHAR (30)                               NULL,
	[CallerTelephoneNumber] NVARCHAR (25)                               NULL,
	[CallerBranch]          NVARCHAR (60)                               NULL,
	[CardChangedBy]         NVARCHAR (85)                               NULL,
	[CallerLocation]        NVARCHAR (50)                               NULL,
	[IncidentNumber]        VARCHAR (36)                                NOT NULL,
	[AuditDWKey]            INT                                         NOT NULL,
	[SourceDatabaseKey]     INT                                         NOT NULL,
	[ValidFrom]             DATETIME2 (0) GENERATED ALWAYS AS ROW START CONSTRAINT [DF_FileImportIncidentsSysStart] DEFAULT (CONVERT([datetime2](0),'0000-01-01 00:00:00')) NOT NULL,
	[ValidTo]               DATETIME2 (0) GENERATED ALWAYS AS ROW END   CONSTRAINT [DF_FileImportIncidentsSysEnd] DEFAULT (CONVERT([datetime2](0),'9999-12-31 23:59:59')) NOT NULL,
	CONSTRAINT [PK_FileImportIncidents] PRIMARY KEY CLUSTERED ([IncidentNumber] ASC, [AuditDWKey] ASC) WITH (DATA_COMPRESSION = PAGE),
	PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[history].[Incidents], DATA_CONSISTENCY_CHECK=ON))
GO

CREATE NONCLUSTERED INDEX [NCIX_FileImportIncidentSDK]
	ON [FileImport].[Incidents] ([SourceDatabaseKey] ASC)
	INCLUDE ([IncidentNumber], [AuditDWKey])
GO