CREATE TABLE [Dim].[ColourSchema]
(
	[Code]               INT            NOT NULL,
	[Name]               NVARCHAR (250) NULL,
	[Omschrijving]       NVARCHAR (100) NULL,
	[Inc_Aangemeld1]     NVARCHAR (100) NULL,
	[Inc_Aangemeld2]     NVARCHAR (100) NULL,
	[Inc_Aangemeld3]     NVARCHAR (100) NULL,
	[Inc_Aangemeld4]     NVARCHAR (100) NULL,
	[Inc_Afgemeld1]      NVARCHAR (100) NULL,
	[Inc_Afgemeld2]      NVARCHAR (100) NULL,
	[Inc_Afgemeld3]      NVARCHAR (100) NULL,
	[Inc_Afgemeld4]      NVARCHAR (100) NULL,
	[Inc_Openstaand1]    NVARCHAR (100) NULL,
	[Inc_Openstaand2]    NVARCHAR (100) NULL,
	[Inc_Openstaand3]    NVARCHAR (100) NULL,
	[Inc_Openstaand4]    NVARCHAR (100) NULL,
	[Inc_Gereed1]        NVARCHAR (100) NULL,
	[Inc_workload]       NVARCHAR (100) NULL,
	[Cha_Aangemeld1]     NVARCHAR (100) NULL,
	[Cha_Aangemeld2]     NVARCHAR (100) NULL,
	[Cha_Aangemeld3]     NVARCHAR (100) NULL,
	[Cha_Aangemeld4]     NVARCHAR (100) NULL,
	[Cha_Afgemeld1]      NVARCHAR (100) NULL,
	[Cha_Afgemeld2]      NVARCHAR (100) NULL,
	[Cha_Afgemeld3]      NVARCHAR (100) NULL,
	[Cha_Afgemeld4]      NVARCHAR (100) NULL,
	[Cha_Openstaand1]    NVARCHAR (100) NULL,
	[Cha_Openstaand2]    NVARCHAR (100) NULL,
	[Cha_Openstaand3]    NVARCHAR (100) NULL,
	[Cha_Openstaand4]    NVARCHAR (100) NULL,
	[Cha_Gereed1]        NVARCHAR (100) NULL,
	[Cha_workload]       NVARCHAR (100) NULL,
	[Line_target]        NVARCHAR (100) NULL,
	[Line_mean]          NVARCHAR (100) NULL,
	[DataLabel]          NVARCHAR (100) NULL,
	[DataLabelPerc]      NVARCHAR (100) NULL,
	[Call_Opgenomen]     NVARCHAR (100) NULL,
	[Call_Opgenomen1]    NVARCHAR (100) NULL,
	[Call_Opgenomen2]    NVARCHAR (100) NULL,
	[Call_Opgenomen3]    NVARCHAR (100) NULL,
	[Call_Opgenomen4]    NVARCHAR (100) NULL,
	[Call_Nietopgenomen] NVARCHAR (100) NULL,
	[Call_workload]      NVARCHAR (100) NULL,
	CONSTRAINT [PK_ColourSchema] PRIMARY KEY CLUSTERED ([Code] ASC)
)