CREATE TABLE [Dim].[Object]
(
	[ObjectKey]           INT            IDENTITY (1,1) NOT FOR REPLICATION,
	[CallerKey]           INT            NOT NULL,
	[CustomerKey]         INT            NOT NULL,
	[SourceDatabaseKey]   INT            NOT NULL,
	[ChangeDate]          DATE           NULL,
	[ChangeTime]          TIME (0)       NULL,
	[ObjectID]            NVARCHAR (255) NULL,
	[Class]               NVARCHAR (255) NULL,
	[ObjectType]          NVARCHAR (255) NULL,
	[Model]               NVARCHAR (255) NULL,
	[PurchasePrice]       MONEY          NULL,
	[PurchaseDate]        DATE           NULL,
	[PurchaseTime]        TIME (0)       NULL,
	[Budgetholder]        NVARCHAR (255) NULL,
	[Supplier]            NVARCHAR (255) NULL,
	[SerialNumber]        NVARCHAR (255) NULL,
	[Contact]             NVARCHAR (255) NULL,
	[Attention]           NVARCHAR (255) NULL,
	[Configuration]       NVARCHAR (255) NULL,
	[User]                NVARCHAR (255) NULL,
	[Group]               NVARCHAR (255) NULL,
	[Hostname]            NVARCHAR (255) NULL,
	[IPAddress]           NVARCHAR (255) NULL,
	[LeaseStartDate]      DATE           NULL,
	[LeaseStartTime]      TIME (0)       NULL,
	[LeaseContractNumber] NVARCHAR (255) NULL,
	[LeaseEndDate]        DATE           NULL,
	[LeaseEndTime]        TIME (0)       NULL,
	[LeasePeriod]         INT            NULL,
	[LeasePrice]          MONEY          NULL,
	[LicentieType]        NVARCHAR (255) NULL,
	[Comments]            NVARCHAR (255) NULL,
	[OrderNumber]         NVARCHAR (255) NULL,
	[Person]              NVARCHAR (255) NULL,
	[Staffgroup]          NVARCHAR (255) NULL,
	[City]                NVARCHAR (255) NULL,
	[ResidualValue]       MONEY          NULL,
	[Room]                NVARCHAR (255) NULL,
	[Specification]       NVARCHAR (255) NULL,
	[Status]              NVARCHAR (255) NULL,
	[Branch]              NVARCHAR (255) NULL,
	CONSTRAINT [PK_Object] PRIMARY KEY CLUSTERED ([ObjectKey] ASC),
	CONSTRAINT [FK_Object_CallerKey] FOREIGN KEY ([CallerKey]) REFERENCES [Dim].[Caller] ([CallerKey]),
	CONSTRAINT [FK_Object_CustomerKey] FOREIGN KEY ([CustomerKey]) REFERENCES [Dim].[Customer] ([CustomerKey])
)