CREATE TABLE [Dim].[SLA]
(
	[Code]                            INT            NOT NULL,
	[Name]                            NVARCHAR (250) NULL,
	[CallResponseTimeValue]           DECIMAL (9, 2) NULL,
	[CallResponseTimeRate]            DECIMAL (9, 2) NULL,
	[CallDurationValue]               DECIMAL (9, 2) NULL,
	[CallDurationRate]                DECIMAL (9, 2) NULL,
	[MailResponseTimeValue]           DECIMAL (9, 2) NULL,
	[MailResponseTimeRate]            DECIMAL (9, 2) NULL,
	[IncidentFirstlineResolveRate]    DECIMAL (9, 2) NULL,
	[IncidentVerstoringResolveRate]   DECIMAL (9, 2) NULL,
	[IncidentFirstlineDuration]       DECIMAL (9, 2) NULL,
	[IncidentSecondlineDuration]      DECIMAL (9, 2) NULL,
	[StandardChangeDurationRate]      DECIMAL (9, 2) NULL,
	[IncidentVerstoringP1ResolveRate] DECIMAL (9, 2) NULL,
	[IncidentVerstoringP2ResolveRate] DECIMAL (9, 2) NULL,
	[IncidentVerstoringP3ResolveRate] DECIMAL (9, 2) NULL,
	[IncidentAanvraagP5ResolveRate]   DECIMAL (9, 2) NULL,
	[IncidentVraagP5ResolveRate]      DECIMAL (9, 2) NULL,
	[KlachtResolveRate]               DECIMAL (9, 2) NULL,
	[ProblemResolveRate]              DECIMAL (9, 2) NULL,
	[ChangeAuthTimeValue]             DECIMAL (9)    NULL,
	[ChangeAuthTimeRate]              DECIMAL (9, 2) NULL,
	[ChangeClosingTimeValue]          DECIMAL (9)    NULL,
	[ChangeClosingTimeRate]           DECIMAL (9, 2) NULL,
	[LastChgDateTime]                 DATETIME2 (3)  NOT NULL,
	[SLAKey]                          INT            IDENTITY (1,1) NOT FOR REPLICATION,
	CONSTRAINT [PK_SLA] PRIMARY KEY CLUSTERED ([Code] ASC)
)