CREATE TABLE [dbo].[activiteitgroep_voordracht] (
    [unid]              UNIQUEIDENTIFIER                                   NOT NULL,
    [dataanmk]          DATETIME                                           NULL,
    [datwijzig]         DATETIME                                           NULL,
    [uidaanmk]          UNIQUEIDENTIFIER                                   NULL,
    [uidwijzig]         UNIQUEIDENTIFIER                                   NULL,
    [status]            INT                                                NULL,
    [projectid]         UNIQUEIDENTIFIER                                   NULL,
    [aanvraagid]        UNIQUEIDENTIFIER                                   NULL,
    [uurprijs]          MONEY                                              NULL,
    [utv]               NVARCHAR (1)                                       NULL,
    [nultarief]         BIT                                                NULL,
    [btwid]             UNIQUEIDENTIFIER                                   NULL,
    [intern]            BIT                                                NULL,
    [productid]         UNIQUEIDENTIFIER                                   NULL,
    [grootboekid]       UNIQUEIDENTIFIER                                   NULL,
    [datacceptatie]     DATETIME                                           NULL,
    [toeslag]           MONEY                                              NULL,
    [activiteitgroepid] UNIQUEIDENTIFIER                                   NULL,
    [employeetypeid]    UNIQUEIDENTIFIER                                   NULL,
    [budget_uren]       INT                                                NULL,
    [totale_werklast]   INT                                                NULL,
    [startdatum_groep]  DATETIME                                           NULL,
    [sdv_groep]         NVARCHAR (1)                                       NULL,
    [einddatum_groep]   DATETIME                                           NULL,
    [edv_groep]         NVARCHAR (1)                                       NULL,
    [AuditDWKey]        INT                                                NULL,
    [ValidFrom]         DATETIME2 (0) GENERATED ALWAYS AS ROW START HIDDEN CONSTRAINT [DF_dboactiviteitgroep_voordrachtSysStart] DEFAULT (CONVERT([datetime2](0),'0000-01-01 00:00:00')) NOT NULL,
    [ValidTo]           DATETIME2 (0) GENERATED ALWAYS AS ROW END HIDDEN   CONSTRAINT [DF_dboactiviteitgroep_voordrachtSysEnd] DEFAULT (CONVERT([datetime2](0),'9999-12-31 23:59:59')) NOT NULL,
    CONSTRAINT [pk_dboactiviteitgroep_voordracht] PRIMARY KEY CLUSTERED ([unid] ASC) WITH (DATA_COMPRESSION = PAGE),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[History].[activiteitgroep_voordracht], DATA_CONSISTENCY_CHECK=ON));

