CREATE TABLE [dbo].[contactpersoon] (
    [unid]               UNIQUEIDENTIFIER                                   NOT NULL,
    [dataanmk]           DATETIME                                           NULL,
    [datwijzig]          DATETIME                                           NULL,
    [uidaanmk]           UNIQUEIDENTIFIER                                   NULL,
    [uidwijzig]          UNIQUEIDENTIFIER                                   NULL,
    [klantid]            UNIQUEIDENTIFIER                                   NULL,
    [status]             INT                                                NULL,
    [attentieid]         UNIQUEIDENTIFIER                                   NULL,
    [attentiemelding]    NVARCHAR (200)                                     NULL,
    [bedrijfarchief]     BIT                                                NULL,
    [anaam]              NVARCHAR (30)                                      NULL,
    [tvoegsel]           NVARCHAR (10)                                      NULL,
    [rnaam]              NVARCHAR (20)                                      NULL,
    [vletters]           NVARCHAR (12)                                      NULL,
    [titel]              NVARCHAR (18)                                      NULL,
    [achtervoegsel]      NVARCHAR (8)                                       NULL,
    [geslacht]           INT                                                NULL,
    [geboren]            DATETIME                                           NULL,
    [voertaalid]         UNIQUEIDENTIFIER                                   NULL,
    [afdeling]           NVARCHAR (60)                                      NULL,
    [functie]            NVARCHAR (50)                                      NULL,
    [spec2]              NVARCHAR (50)                                      NULL,
    [verantwoordingid]   UNIQUEIDENTIFIER                                   NULL,
    [rolid]              UNIQUEIDENTIFIER                                   NULL,
    [rol]                NVARCHAR (30)                                      NULL,
    [vrijvelda]          UNIQUEIDENTIFIER                                   NULL,
    [vrijveldb]          NVARCHAR (40)                                      NULL,
    [vrijveldc]          NVARCHAR (40)                                      NULL,
    [vrijveldd]          NVARCHAR (40)                                      NULL,
    [vrijvelde]          NVARCHAR (40)                                      NULL,
    [tel1]               NVARCHAR (25)                                      NULL,
    [teloms1]            NVARCHAR (20)                                      NULL,
    [tel2]               NVARCHAR (25)                                      NULL,
    [teloms2]            NVARCHAR (20)                                      NULL,
    [fax1]               NVARCHAR (25)                                      NULL,
    [faxoms1]            NVARCHAR (20)                                      NULL,
    [email]              NVARCHAR (70)                                      NULL,
    [email_opt_in]       BIT                                                NULL,
    [email_hoofdpersoon] BIT                                                NULL,
    [datexport]          DATETIME                                           NULL,
    [tel1p]              NVARCHAR (25)                                      NULL,
    [teloms1p]           NVARCHAR (15)                                      NULL,
    [tel2p]              NVARCHAR (25)                                      NULL,
    [teloms2p]           NVARCHAR (15)                                      NULL,
    [emailp]             NVARCHAR (75)                                      NULL,
    [kingcpnummer]       INT                                                NULL,
    [linkedin]           NVARCHAR (120)                                     NULL,
    [foto]               NVARCHAR (250)                                     NULL,
    [personid]           UNIQUEIDENTIFIER                                   NULL,
    [straat1p]           NVARCHAR (50)                                      NULL,
    [nummer1p]           NVARCHAR (20)                                      NULL,
    [postcode1p]         NVARCHAR (15)                                      NULL,
    [staat1p]            NVARCHAR (25)                                      NULL,
    [plaats1p]           NVARCHAR (30)                                      NULL,
    [land1pid]           UNIQUEIDENTIFIER                                   NULL,
    [extraopz1]          UNIQUEIDENTIFIER                                   NULL,
    [extraopz2]          UNIQUEIDENTIFIER                                   NULL,
    [extraopz3]          UNIQUEIDENTIFIER                                   NULL,
    [extraopz4]          UNIQUEIDENTIFIER                                   NULL,
    [extraopz5]          UNIQUEIDENTIFIER                                   NULL,
    [exveld002]          NVARCHAR (250)                                     NULL,
    [extraopz6]          UNIQUEIDENTIFIER                                   NULL,
    [extravrij6]         NVARCHAR (40)                                      NULL,
    [extravrij5]         NVARCHAR (40)                                      NULL,
    [extravrij4]         NVARCHAR (40)                                      NULL,
    [extravrij3]         NVARCHAR (40)                                      NULL,
    [extravrij2]         NVARCHAR (40)                                      NULL,
    [extravrij1]         NVARCHAR (40)                                      NULL,
    [AuditDWKey]         INT                                                NULL,
    [ValidFrom]          DATETIME2 (0) GENERATED ALWAYS AS ROW START HIDDEN CONSTRAINT [DF_dbocontactpersoonSysStart] DEFAULT (CONVERT([datetime2](0),'0000-01-01 00:00:00')) NOT NULL,
    [ValidTo]            DATETIME2 (0) GENERATED ALWAYS AS ROW END HIDDEN   CONSTRAINT [DF_dbocontactpersoonSysEnd] DEFAULT (CONVERT([datetime2](0),'9999-12-31 23:59:59')) NOT NULL,
    CONSTRAINT [pk_dbocontactpersoon] PRIMARY KEY CLUSTERED ([unid] ASC) WITH (DATA_COMPRESSION = PAGE),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[History].[contactpersoon], DATA_CONSISTENCY_CHECK=ON));

