CREATE TABLE [dbo].[voordracht] (
    [unid]                         UNIQUEIDENTIFIER                                   NOT NULL,
    [dataanmk]                     DATETIME                                           NULL,
    [datwijzig]                    DATETIME                                           NULL,
    [uidaanmk]                     UNIQUEIDENTIFIER                                   NULL,
    [uidwijzig]                    UNIQUEIDENTIFIER                                   NULL,
    [status]                       INT                                                NULL,
    [projectid]                    UNIQUEIDENTIFIER                                   NULL,
    [aanvraagid]                   UNIQUEIDENTIFIER                                   NULL,
    [uurprijs]                     MONEY                                              NULL,
    [utv]                          NVARCHAR (1)                                       NULL,
    [nultarief]                    BIT                                                NULL,
    [btwid]                        UNIQUEIDENTIFIER                                   NULL,
    [intern]                       BIT                                                NULL,
    [productid]                    UNIQUEIDENTIFIER                                   NULL,
    [grootboekid]                  UNIQUEIDENTIFIER                                   NULL,
    [datacceptatie]                DATETIME                                           NULL,
    [toeslag]                      MONEY                                              NULL,
    [uurprijs_hi]                  BIT                                                NULL,
    [werknemertype]                INT                                                NULL,
    [employeetypeid]               UNIQUEIDENTIFIER                                   NULL,
    [toestel]                      NVARCHAR (15)                                      NULL,
    [activiteitgroep_voordrachtid] UNIQUEIDENTIFIER                                   NULL,
    [werklast]                     INT                                                NULL,
    [geldbudget]                   INT                                                NULL,
    [geenwerklast]                 BIT                                                NULL,
    [startdatum]                   DATETIME                                           NULL,
    [sdv]                          NVARCHAR (1)                                       NULL,
    [einddatum]                    DATETIME                                           NULL,
    [edv]                          NVARCHAR (1)                                       NULL,
    [invuldatum]                   DATETIME                                           NULL,
    [wn_invuldatum]                DATETIME                                           NULL,
    [uuruidwijzig]                 UNIQUEIDENTIFIER                                   NULL,
    [uurdatwijzig]                 DATETIME                                           NULL,
    [inkooptarief]                 MONEY                                              NULL,
    [tarief_doorbelasting]         MONEY                                              NULL,
    [extraopz1]                    UNIQUEIDENTIFIER                                   NULL,
    [extraopz2]                    UNIQUEIDENTIFIER                                   NULL,
    [extraopz3]                    UNIQUEIDENTIFIER                                   NULL,
    [extraopz4]                    UNIQUEIDENTIFIER                                   NULL,
    [extraopz5]                    UNIQUEIDENTIFIER                                   NULL,
    [extraopz6]                    UNIQUEIDENTIFIER                                   NULL,
    [extravrij6]                   NVARCHAR (40)                                      NULL,
    [extravrij5]                   NVARCHAR (40)                                      NULL,
    [extravrij4]                   NVARCHAR (40)                                      NULL,
    [extravrij3]                   NVARCHAR (40)                                      NULL,
    [extravrij2]                   NVARCHAR (40)                                      NULL,
    [extravrij1]                   NVARCHAR (40)                                      NULL,
    [nomination_phaseid]           UNIQUEIDENTIFIER                                   NULL,
    [employeeid]                   UNIQUEIDENTIFIER                                   NULL,
    [description]                  NVARCHAR (20)                                      NULL,
    [AuditDWKey]                   INT                                                NULL,
    [ValidFrom]                    DATETIME2 (0) GENERATED ALWAYS AS ROW START HIDDEN CONSTRAINT [DF_dbovoordrachtSysStart] DEFAULT (CONVERT([datetime2](0),'0000-01-01 00:00:00')) NOT NULL,
    [ValidTo]                      DATETIME2 (0) GENERATED ALWAYS AS ROW END HIDDEN   CONSTRAINT [DF_dbovoordrachtSysEnd] DEFAULT (CONVERT([datetime2](0),'9999-12-31 23:59:59')) NOT NULL,
    CONSTRAINT [pk_dbovoordracht] PRIMARY KEY CLUSTERED ([unid] ASC) WITH (DATA_COMPRESSION = PAGE),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[History].[voordracht], DATA_CONSISTENCY_CHECK=ON));

