CREATE TABLE [dbo].[wcontract] (
    [unid]                         UNIQUEIDENTIFIER                                   NOT NULL,
    [dataanmk]                     DATETIME                                           NULL,
    [datwijzig]                    DATETIME                                           NULL,
    [uidaanmk]                     UNIQUEIDENTIFIER                                   NULL,
    [uidwijzig]                    UNIQUEIDENTIFIER                                   NULL,
    [status]                       INT                                                NULL,
    [archiefid]                    UNIQUEIDENTIFIER                                   NULL,
    [archiefdatum]                 DATETIME                                           NULL,
    [werknemerid]                  UNIQUEIDENTIFIER                                   NULL,
    [contractsoortid]              UNIQUEIDENTIFIER                                   NULL,
    [procent_naar_0]               BIT                                                NULL,
    [procent]                      MONEY                                              NULL,
    [contractsoort]                NVARCHAR (30)                                      NULL,
    [retour]                       BIT                                                NULL,
    [pensioengegevens_volledig]    BIT                                                NULL,
    [verzekeringen_volledig]       BIT                                                NULL,
    [salaris]                      MONEY                                              NULL,
    [nettobruto]                   INT                                                NULL,
    [salperiodeid]                 UNIQUEIDENTIFIER                                   NULL,
    [salaris_schaal]               NVARCHAR (10)                                      NULL,
    [toeslag]                      MONEY                                              NULL,
    [toeslag_bn]                   INT                                                NULL,
    [toeslag_periodeid]            UNIQUEIDENTIFIER                                   NULL,
    [toeslag_typeid]               UNIQUEIDENTIFIER                                   NULL,
    [lvnloop_rek_bedrag]           MONEY                                              NULL,
    [lvnloop_rek_perc]             MONEY                                              NULL,
    [lvnloop_rek_levid]            UNIQUEIDENTIFIER                                   NULL,
    [lvnloop_rekening]             NVARCHAR (15)                                      NULL,
    [spaarloon]                    MONEY                                              NULL,
    [spaarloon_bn]                 INT                                                NULL,
    [spaarloon_periodeid]          UNIQUEIDENTIFIER                                   NULL,
    [premiespaarloon]              MONEY                                              NULL,
    [premiespaarloon_bn]           INT                                                NULL,
    [premiespaarloon_periodeid]    UNIQUEIDENTIFIER                                   NULL,
    [pensioen]                     MONEY                                              NULL,
    [pensioen_bn]                  INT                                                NULL,
    [pensioen_periodeid]           UNIQUEIDENTIFIER                                   NULL,
    [pensioen_type]                NVARCHAR (30)                                      NULL,
    [pensioen_leverancierid]       UNIQUEIDENTIFIER                                   NULL,
    [wao_gat]                      MONEY                                              NULL,
    [wao_gat_bn]                   INT                                                NULL,
    [wao_gat_periodeid]            UNIQUEIDENTIFIER                                   NULL,
    [wao_gat_type]                 NVARCHAR (30)                                      NULL,
    [wao_gat_leverancierid]        UNIQUEIDENTIFIER                                   NULL,
    [ziektekosten]                 MONEY                                              NULL,
    [ziektekosten_bn]              INT                                                NULL,
    [ziektekosten_periodeid]       UNIQUEIDENTIFIER                                   NULL,
    [ziektekosten_type]            NVARCHAR (30)                                      NULL,
    [ziektekn_leverancierid]       UNIQUEIDENTIFIER                                   NULL,
    [onkostenvergoeding]           MONEY                                              NULL,
    [onkostenvergoeding_bn]        INT                                                NULL,
    [onkostenvergoeding_periodeid] UNIQUEIDENTIFIER                                   NULL,
    [reiskosten]                   MONEY                                              NULL,
    [reiskosten_bn]                INT                                                NULL,
    [reiskosten_periodeid]         UNIQUEIDENTIFIER                                   NULL,
    [functie]                      NVARCHAR (40)                                      NULL,
    [vestigingid]                  UNIQUEIDENTIFIER                                   NULL,
    [vestiging]                    NVARCHAR (40)                                      NULL,
    [startdatum]                   DATETIME                                           NULL,
    [einddatum]                    DATETIME                                           NULL,
    [oplbudget]                    MONEY                                              NULL,
    [oplperiodeid]                 UNIQUEIDENTIFIER                                   NULL,
    [oplbudget_bn]                 INT                                                NULL,
    [vakdagen]                     MONEY                                              NULL,
    [bonusregeling]                MONEY                                              NULL,
    [bonusregeling_bn]             INT                                                NULL,
    [bonusregeling_periodeid]      UNIQUEIDENTIFIER                                   NULL,
    [eb_auto]                      MONEY                                              NULL,
    [eb_auto_bn]                   INT                                                NULL,
    [eb_auto_periodeid]            UNIQUEIDENTIFIER                                   NULL,
    [eb_auto_type]                 NVARCHAR (30)                                      NULL,
    [eb_auto_kenteken]             NVARCHAR (15)                                      NULL,
    [eb_tel]                       MONEY                                              NULL,
    [eb_tel_bn]                    INT                                                NULL,
    [eb_tel_periodeid]             UNIQUEIDENTIFIER                                   NULL,
    [eb_tel_type]                  NVARCHAR (30)                                      NULL,
    [eb_tel_nr]                    NVARCHAR (30)                                      NULL,
    [eb_pc]                        MONEY                                              NULL,
    [eb_pc_bn]                     INT                                                NULL,
    [eb_pc_periodeid]              UNIQUEIDENTIFIER                                   NULL,
    [eb_pc_type]                   NVARCHAR (30)                                      NULL,
    [eb_pc_nr]                     NVARCHAR (30)                                      NULL,
    [eb_reisvergoeding]            MONEY                                              NULL,
    [eb_reisvergoeding_bn]         INT                                                NULL,
    [eb_reisvergoeding_periodeid]  UNIQUEIDENTIFIER                                   NULL,
    [begin_overuren]               MONEY                                              NULL,
    [begin_per_overuren]           DATETIME                                           NULL,
    [vakperiodeid]                 UNIQUEIDENTIFIER                                   NULL,
    [studentenregeling]            BIT                                                NULL,
    [procesid]                     UNIQUEIDENTIFIER                                   NULL,
    [budgethouderid]               UNIQUEIDENTIFIER                                   NULL,
    [proeftijdid]                  UNIQUEIDENTIFIER                                   NULL,
    [opzegtermijnid]               UNIQUEIDENTIFIER                                   NULL,
    [belastinggroep]               INT                                                NULL,
    [uurtarief]                    MONEY                                              NULL,
    [inkoopprijs]                  MONEY                                              NULL,
    [vorig_wcontractid]            UNIQUEIDENTIFIER                                   NULL,
    [adv_regeling]                 BIT                                                NULL,
    [adv_percentage]               MONEY                                              NULL,
    [verwerktcoda]                 INT                                                NULL,
    [prive_km_quotum]              INT                                                NULL,
    [interne_mw]                   BIT                                                NULL,
    [extraopz1]                    UNIQUEIDENTIFIER                                   NULL,
    [extraopz2]                    UNIQUEIDENTIFIER                                   NULL,
    [extraopz3]                    UNIQUEIDENTIFIER                                   NULL,
    [extraopz4]                    UNIQUEIDENTIFIER                                   NULL,
    [extraopz5]                    UNIQUEIDENTIFIER                                   NULL,
    [extraopz6]                    UNIQUEIDENTIFIER                                   NULL,
    [extravrij6]                   NVARCHAR (40)                                      NULL,
    [extravrij5]                   NVARCHAR (40)                                      NULL,
    [extravrij4]                   NVARCHAR (40)                                      NULL,
    [extravrij3]                   NVARCHAR (40)                                      NULL,
    [extravrij2]                   NVARCHAR (40)                                      NULL,
    [extravrij1]                   NVARCHAR (40)                                      NULL,
    [taxcredit]                    BIT                                                NULL,
    [AuditDWKey]                   INT                                                NULL,
    [ValidFrom]                    DATETIME2 (0) GENERATED ALWAYS AS ROW START HIDDEN CONSTRAINT [DF_dbowcontractSysStart] DEFAULT (CONVERT([datetime2](0),'0000-01-01 00:00:00')) NOT NULL,
    [ValidTo]                      DATETIME2 (0) GENERATED ALWAYS AS ROW END HIDDEN   CONSTRAINT [DF_dbowcontractSysEnd] DEFAULT (CONVERT([datetime2](0),'9999-12-31 23:59:59')) NOT NULL,
    CONSTRAINT [pk_dbowcontract] PRIMARY KEY CLUSTERED ([unid] ASC) WITH (DATA_COMPRESSION = PAGE),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[History].[wcontract], DATA_CONSISTENCY_CHECK=ON));

