CREATE TABLE [dbo].[werknemer] (
    [unid]                        UNIQUEIDENTIFIER                                   NOT NULL,
    [dataanmk]                    DATETIME                                           NULL,
    [datwijzig]                   DATETIME                                           NULL,
    [uidaanmk]                    UNIQUEIDENTIFIER                                   NULL,
    [uidwijzig]                   UNIQUEIDENTIFIER                                   NULL,
    [status]                      INT                                                NULL,
    [archiefid]                   UNIQUEIDENTIFIER                                   NULL,
    [archiefdatum]                DATETIME                                           NULL,
    [inits]                       NVARCHAR (10)                                      NULL,
    [titel]                       NVARCHAR (15)                                      NULL,
    [datexport]                   DATETIME                                           NULL,
    [geslacht]                    INT                                                NULL,
    [geboren]                     DATETIME                                           NULL,
    [geboortejaar]                INT                                                NULL,
    [sollicitatie_aanleidingid]   UNIQUEIDENTIFIER                                   NULL,
    [sollicitatie_aanleiding]     NVARCHAR (25)                                      NULL,
    [gesolliciteerd_op_functieid] UNIQUEIDENTIFIER                                   NULL,
    [gesolliciteerd_op_functie]   NVARCHAR (30)                                      NULL,
    [geblandid]                   UNIQUEIDENTIFIER                                   NULL,
    [nationaliteitid]             UNIQUEIDENTIFIER                                   NULL,
    [opleidingid]                 UNIQUEIDENTIFIER                                   NULL,
    [richtingid]                  UNIQUEIDENTIFIER                                   NULL,
    [rijbewijs]                   BIT                                                NULL,
    [auto]                        BIT                                                NULL,
    [ovid]                        UNIQUEIDENTIFIER                                   NULL,
    [cvref]                       NVARCHAR (10)                                      NULL,
    [persnr]                      NVARCHAR (6)                                       NULL,
    [pmwnr]                       NVARCHAR (6)                                       NULL,
    [belastinggroep]              INT                                                NULL,
    [uurtarief]                   MONEY                                              NULL,
    [inkoopprijs]                 MONEY                                              NULL,
    [reknr1]                      NVARCHAR (40)                                      NULL,
    [rektype1]                    INT                                                NULL,
    [studiestatusid]              UNIQUEIDENTIFIER                                   NULL,
    [leefsituatieid]              UNIQUEIDENTIFIER                                   NULL,
    [stdbeschikbaarheid]          INT                                                NULL,
    [invuldatum]                  DATETIME                                           NULL,
    [wn_invuldatum]               DATETIME                                           NULL,
    [leverancierid]               UNIQUEIDENTIFIER                                   NULL,
    [vestigingid]                 UNIQUEIDENTIFIER                                   NULL,
    [vestiging]                   NVARCHAR (40)                                      NULL,
    [budgethouderid]              UNIQUEIDENTIFIER                                   NULL,
    [datumindienst]               DATETIME                                           NULL,
    [hi_datumindienst]            BIT                                                NULL,
    [Datum_StartDatumContract]    DATETIME                                           NULL,
    [datumuitdienst]              DATETIME                                           NULL,
    [Datum_PotentieelWerknemer]   DATETIME                                           NULL,
    [datpotwn]                    DATETIME                                           NULL,
    [datwn]                       DATETIME                                           NULL,
    [attentieid]                  UNIQUEIDENTIFIER                                   NULL,
    [attentiemelding]             NVARCHAR (200)                                     NULL,
    [urenmanagerid]               UNIQUEIDENTIFIER                                   NULL,
    [boekhoud_url]                NVARCHAR (120)                                     NULL,
    [geocode_lat]                 FLOAT (53)                                         NULL,
    [geocode_lon]                 FLOAT (53)                                         NULL,
    [beschikbaar_vanaf]           DATETIME                                           NULL,
    [HR_ContactPersoon]           NVARCHAR (35)                                      NULL,
    [Leidinggevende]              NVARCHAR (35)                                      NULL,
    [extraopz1]                   UNIQUEIDENTIFIER                                   NULL,
    [extraopz2]                   UNIQUEIDENTIFIER                                   NULL,
    [extraopz3]                   UNIQUEIDENTIFIER                                   NULL,
    [extraopz4]                   UNIQUEIDENTIFIER                                   NULL,
    [extraopz5]                   UNIQUEIDENTIFIER                                   NULL,
    [extraopz6]                   UNIQUEIDENTIFIER                                   NULL,
    [pmwopz3]                     UNIQUEIDENTIFIER                                   NULL,
    [pmwopz4]                     UNIQUEIDENTIFIER                                   NULL,
    [pmwopz5]                     UNIQUEIDENTIFIER                                   NULL,
    [pmwvrij2]                    NVARCHAR (40)                                      NULL,
    [pmwopz6]                     UNIQUEIDENTIFIER                                   NULL,
    [pmwvrij1]                    NVARCHAR (40)                                      NULL,
    [pmwvrij4]                    NVARCHAR (40)                                      NULL,
    [pmwvrij3]                    NVARCHAR (40)                                      NULL,
    [pmwvrij6]                    NVARCHAR (40)                                      NULL,
    [pmwopz1]                     UNIQUEIDENTIFIER                                   NULL,
    [pmwopz2]                     UNIQUEIDENTIFIER                                   NULL,
    [pmwvrij5]                    NVARCHAR (40)                                      NULL,
    [exveld003]                   UNIQUEIDENTIFIER                                   NULL,
    [exveld002]                   UNIQUEIDENTIFIER                                   NULL,
    [exveld005]                   UNIQUEIDENTIFIER                                   NULL,
    [exveld004]                   UNIQUEIDENTIFIER                                   NULL,
    [extravrij5]                  NVARCHAR (40)                                      NULL,
    [extravrij4]                  NVARCHAR (40)                                      NULL,
    [extravrij3]                  NVARCHAR (40)                                      NULL,
    [extravrij2]                  NVARCHAR (40)                                      NULL,
    [graduation_date]             DATETIME                                           NULL,
    [geocode_state]               INT                                                NULL,
    [km_submitdate]               DATETIME                                           NULL,
    [anaam]                       NVARCHAR (30)                                      NULL,
    [rnaam]                       NVARCHAR (20)                                      NULL,
    [tussen]                      NVARCHAR (10)                                      NULL,
    [vnaam]                       NVARCHAR (50)                                      NULL,
    [plaats1]                     NVARCHAR (30)                                      NULL,
    [postcode1]                   NVARCHAR (15)                                      NULL,
    [tel1]                        NVARCHAR (25)                                      NULL,
    [email]                       NVARCHAR (75)                                      NULL,
    [functie]                     NVARCHAR (35)                                      NULL,
    [business_unit]               NVARCHAR (35)                                      NULL,
    [extra_team]                  NVARCHAR (35)                                      NULL,
    [extra_niveau]                NVARCHAR (35)                                      NULL,
    [nextappointment_jaar]        NVARCHAR (35)                                      NULL,
    [nextappointment_maand]       NVARCHAR (35)                                      NULL,
    [employeetypeid]              UNIQUEIDENTIFIER NULL,
    [recruiterid]                 UNIQUEIDENTIFIER NULL,
    [hr_managerid]                UNIQUEIDENTIFIER NULL,
    [informerid]                  UNIQUEIDENTIFIER NULL,
    [informername]                NVARCHAR (60)    NULL,
    [business_unitid]             UNIQUEIDENTIFIER NULL,
    [extra_niveauid]              UNIQUEIDENTIFIER NULL, 
    [extra_teamid]                UNIQUEIDENTIFIER NULL, 
    [functieid]                   UNIQUEIDENTIFIER NULL,
    [HR_ContactPersoonid]         UNIQUEIDENTIFIER NULL,
    [leidinggevendeid]            UNIQUEIDENTIFIER NULL,
    [nextappointment_jaarid]      UNIQUEIDENTIFIER NULL,
    [nextappointment_maandid]     UNIQUEIDENTIFIER NULL,
    [AuditDWKey]                  INT                                                NULL,
    [ValidFrom]                   DATETIME2 (0) GENERATED ALWAYS AS ROW START HIDDEN CONSTRAINT [DF_dbowerknemerSysStart] DEFAULT (CONVERT([datetime2](0),'0000-01-01 00:00:00')) NOT NULL,
    [ValidTo]                     DATETIME2 (0) GENERATED ALWAYS AS ROW END HIDDEN   CONSTRAINT [DF_dbowerknemerSysEnd] DEFAULT (CONVERT([datetime2](0),'9999-12-31 23:59:59')) NOT NULL,
    CONSTRAINT [pk_dbowerknemer] PRIMARY KEY CLUSTERED ([unid] ASC) WITH (DATA_COMPRESSION = PAGE),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[History].[werknemer], DATA_CONSISTENCY_CHECK=ON));

